### ISSUE TITLE
Latest version of the docker image is throwing 404 error

### ISSUE THREAD

**Issue by SamyOteroGlez** [kartoza/docker-geoserver#114]
My geoserver container is throwing a 404 if using the latest version (pull made on Friday 22 Nov)
I had to fix the version to 2.15.2 in order to make it work again.
`image: kartoza/geoserver:latest` not working
`image: kartoza/geoserver:2.15.2`

Regards, 
Sam

**Comment by NyakudyaA** [comment]
@SamyOteroGlez Please try again. I built a new one yesterday

**Comment by ecstaticrainbow** [comment]
The latest version still does not work, 2.15.2 is the last version that does not 404

**Comment by FanaticFiz** [comment]
geoserver startup failed with:
```
root@7a3ec85f01b2:/usr/local/tomcat/logs# cat localhost.2019-11-27.log 
27-Nov-2019 14:01:21.683 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
27-Nov-2019 14:01:21.683 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
27-Nov-2019 14:01:21.683 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@4bcfc697')
27-Nov-2019 14:01:33.299 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
27-Nov-2019 14:01:34.029 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
27-Nov-2019 14:01:41.883 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.geoserver.platform.GeoServerContextLoaderListener
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in org.geoserver.rest.RestConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Factory method 'requestMappingHandlerAdapter' threw exception; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.fasterxml.jackson.datatype.jsr310.JavaTimeModule]: Constructor threw exception; nested exception is java.lang.VerifyError: Stack map does not match the one at exception handler 77
Exception Details:
  Location:
    com/fasterxml/jackson/databind/deser/std/StdDeserializer._parseDate(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/util/Date; @77: astore
  Reason:
    Type 'com/fasterxml/jackson/core/JsonParseException' (current frame, stack[0]) is not assignable to 'com/fasterxml/jackson/core/exc/StreamReadException' (stack map, stack[0])
  Current Frame:
    bci: @69
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/JsonParseException' }
  Stackmap Frame:
    bci: @77
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/deser/std/StdDeserializer', 'com/fasterxml/jackson/core/JsonParser', 'com/fasterxml/jackson/databind/DeserializationContext' }
    stack: { 'com/fasterxml/jackson/core/exc/StreamReadException' }

```

**Comment by NyakudyaA** [comment]
Hey, guys, it looks good on my side here Ubuntu:18.04 with Docker version 18.09.7, build 2d0083d
![logs-geoserver](https://user-images.githubusercontent.com/2510900/69730497-dbaef480-1130-11ea-921c-23f7948acd1a.png)

![geoserver-running](https://user-images.githubusercontent.com/2510900/69730517-e5d0f300-1130-11ea-8655-8592966acb72.png)

![logs-server](https://user-images.githubusercontent.com/2510900/69730531-eb2e3d80-1130-11ea-9e2f-f058d6c1f159.png)

**Comment by NyakudyaA** [comment]
> The latest version still does not work, 2.15.2 is the last version that does not 404

I have just pulled and it works on my side. How are you starting up geoserver?

**Comment by ecstaticrainbow** [comment]
I ran the 2 commands listed in the documentation

```
docker run --name "postgis" -d -t kartoza/postgis:9.4-2.1
docker run --name "geoserver"  --link postgis:postgis -p 8080:8080 -d -t kartoza/geoserver
```

**Comment by NyakudyaA** [comment]
> I ran the 2 commands listed in the documentation
> 
> ```
> docker run --name "postgis" -d -t kartoza/postgis:9.4-2.1
> docker run --name "geoserver"  --link postgis:postgis -p 8080:8080 -d -t kartoza/geoserver
> ```

Try using a new postgis image ie
`docker run --name "postgis" -d -t kartoza/postgis:12.0`

It just maybe caused by that or try to run geoserver standalone without any parameters like 
`docker run --name "geoserver"   -p 8080:8080 -d -t kartoza/geoserver`

**Comment by ecstaticrainbow** [comment]
Running geoserver standalone still gives me the 404 page when navigating to: http://localhost:8080/geoserver

Im running the latest version of docker using docker desktop on windows (linux containers)

**Comment by ekbarber** [comment]
Just want to add I'm experiencing the same issue on a Windows 10 host. 2.15.2 works fine, 2.16.0 causes a 404 when going to localhost:8080/geoserver. But localhost:8080 brings up the tomcat manager just fine.

**Comment by NyakudyaA** [comment]
> Just want to add I'm experiencing the same issue on a Windows 10 host. 2.15.2 works fine, 2.16.0 causes a 404 when going to localhost:8080/geoserver. But localhost:8080 brings up the tomcat manager just fine.

Unfortunately, I do not have a windows machine to test. l can only test on mac. I hope this is not a windows specific issue.
 Can you clone the repo and build the image yourself and specify a different base image

```
docker build --build-arg IMAGE_VERSION=8.0-jre8 --build-arg GS_VERSION=2.16.0 -t kartoza/geoserver:2.16.0 .
```
I  think the main things that changed between 2.15.0 and 2.16.0 is the base image I am using
for the latest builds which is `9.0.7-jre8`

**Comment by FanaticFiz** [comment]
Which version of `jackson-databind` you have in `/usr/local/tomcat/webapps/geoserver/WEB-INF/lib`

**Comment by NyakudyaA** [comment]
> Which version of `jackson-databind` you have in `/usr/local/tomcat/webapps/geoserver/WEB-INF/lib`

![jackson](https://user-images.githubusercontent.com/2510900/69735206-043aec80-1139-11ea-8438-ba77a7c75571.png)

**Comment by FanaticFiz** [comment]
I replace it for version jackson-databind-2.9.10.jar
Then restart catalina and geoserver started successfully

**Comment by NyakudyaA** [comment]
> I replace it for version `jackson-databind-2.9.10.jar`
> Then restart catalina and geoserver started successfully

Thanks for the investigation.  I am suprised that the container was and is still working for on ubuntu.

However, I think what introduces these different versions of jackson are the community modules which I was installing ie s3. 

I have fixed this in this PR https://github.com/kartoza/docker-geoserver/pull/116

**Comment by NyakudyaA** [comment]
Busy building a new image. glad if you could test this after a while

**Comment by ecstaticrainbow** [comment]
Happy to test if for you, let me know when the latest image is on dockerhub ♥

**Comment by NyakudyaA** [comment]
> Happy to test if for you, let me know when the latest image is on dockerhub ♥

Thanks, it's ready for testing

**Comment by FanaticFiz** [comment]
Yes, its works now.
