### ISSUE TITLE
External PostGIS / PostgreSQL

### ISSUE THREAD

**Issue by snario** [kartoza/docker-geoserver#12]
How do I reference an external PostgreSQL?

Say,

`postgresql://root@192.168.0.1/data`

**Comment by shane-axiom** [comment]
@snario You should be able to connect to external PostgreSQL instances normally. You just won't be able to use `localhost`, `172.0.0.1`, etc addresses because these will reference the GeoServer Docker container and not the host.

**Comment by timlinux** [comment]
Closing since it is nicely answered by @shane-axiom 

Also see the README for notes on how to link a PG container.
