### ISSUE TITLE
How to add ECW file format support?

### ISSUE THREAD

**Issue by yong2khoo-lm** [kartoza/docker-geoserver#121]
How to change the Dockerfile to allow the support for ECW raster file format?

**Comment by NyakudyaA** [comment]
Hi @kyygit I am working on it.  If you use pre 2.16 images they natively support gdal formats. with 2.16 they changed the formats and I am trying to find out how to install gdal 2.4 into the container which is required without compiling it

**Comment by kyygit** [comment]
Great! Thanks for your fast response~

**Comment by bruceh48** [comment]
@NyakudyaA  Have you had any success getting GDAL 2.4 to work with GS 2.16.x in the Geoserver container?

**Comment by NyakudyaA** [comment]
> @NyakudyaA Have you had any success getting GDAL 2.4 to work with GS 2.16.x in the Geoserver container?

Got it to work partially. The ecw and sid not present though

**Comment by jklimke** [comment]
Are there any advances to make ECW work again in geoserver 2.17 ? what was missing to make it work ?

**Comment by NyakudyaA** [comment]
> Are there any advances to make ECW work again in geoserver 2.17 ? what was missing to make it work ?

You can have a go at it @jklimke , Since geoserver changed the way the gdal plugin is working I tried it once and it didn't work. I haven't tried it again to see if I can get it working.

You can see my question here https://gis.stackexchange.com/questions/347925/configure-the-geoserver-gdal-plugin-on-debian-buster-running-open-jre11

Basically you need to check
* https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L38 by adding the gdal in the path and compare it with https://github.com/kartoza/docker-geoserver/blob/2.15.0/Dockerfile#L43.

**Comment by gubuntu** [comment]
here's a working approach from a friend Kartoza (in Afrikaans)

>  Ek het gisteraand reggekry om 'n kombinasie van GeoServer 2.17 (nuutste), GDAL en die ECW drivers te compile op Ubuntu 20.04. Die down-side is dat ek die support vir KML layers moes uithaal vir eers. Maar dit beteken dat ons nou die nuutste Ubuntu en GeoServer kan loop met support vir ECW layers. Ek dink mens sal weer KML kan bysit as mens dit ook custom compile.  Die ECW libraries en die KML libraries op Ubuntu 20.04 is met verskillende weergawes van die C++ compiler compile.  Dit is lyk my wat die incompatibility veroorsaak op 20.04.  ECW is met 'n outdated compiler compile, maar mens kan dit nie recompile nie want dit is proprietary.  So as mens GDAL en al die drivers / dependencies met dieselfde ou compiler compile, kry jy iets wat werk.

**Comment by NyakudyaA** [comment]
> here's a working approach from a friend of Kartoza's (in Afrikaans)
> 
> > Ek het gisteraand reggekry om 'n kombinasie van GeoServer 2.17 (nuutste), GDAL en die ECW drivers te compile op Ubuntu 20.04. Die down-side is dat ek die support vir KML layers moes uithaal vir eers. Maar dit beteken dat ons nou die nuutste Ubuntu en GeoServer kan loop met support vir ECW layers. Ek dink mens sal weer KML kan bysit as mens dit ook custom compile.  Die ECW libraries en die KML libraries op Ubuntu 20.04 is met verskillende weergawes van die C++ compiler compile.  Dit is lyk my wat die incompatibility veroorsaak op 20.04.  ECW is met 'n outdated compiler compile, maar mens kan dit nie recompile nie want dit is proprietary.  So as mens GDAL en al die drivers / dependencies met dieselfde ou compiler compile, kry jy iets wat werk.

Thanks, @gubuntu. I am not sure what is the best way in terms of compiling using an SDK that you individually download after agreeing to the license terms and then make the image publicly available. Isn't that in breach of the license agreement?

**Comment by gubuntu** [comment]
I don't think we should include ecw in our image for those reasons but this offers an option for users who want it

**Comment by NyakudyaA** [comment]
I think we can close this, I will add an extra description to the readme letting users know that they need to compile gdal with ecw/Sid support because even the instructions from Geoserver seems to confirm this

**Comment by StruninIhor** [comment]
Any updates on this?
I can't find this extra description of how to compile gdal with ECW support using this container.

**Comment by NyakudyaA** [comment]
We haven’t been successful to natively get the gdal plugin to read ecw. I doubt we will spend some time trying this out because of the acceptance of cloud optimized tif

**Comment by StruninIhor** [comment]
Okay, @NyakudyaA, thank you for the quick response. I found a solution that works well for me now: https://github.com/DenisCarriere/Geoserver-Docker.
Maybe we may just move it here someday

**Comment by NyakudyaA** [comment]
Thanks, maybe I can add it as a build arg and users will choose if they need to, building gdal usually take a lot of time
