### ISSUE TITLE
Azure Docker container instance compatibility

### ISSUE THREAD

**Issue by kyygit** [kartoza/docker-geoserver#122]
Hi, I have just tested to host this on the Azure Docker container instance. 
However, it seems that it is not working (unable to reach the site)... Anything that i missed out?

*Note, everything works perfectly in my Windows 10 Pro.

**Comment by NyakudyaA** [comment]
> Hi, I have just tested to host this on the Azure Docker container instance.
> However, it seems that it is not working (unable to reach the site)... Anything that i missed out?
> 
> *Note, everything works perfectly in my Windows 10 Pro.

Hi I have no access to any azure server to test. It would be nice to show the logs and I can look at them

**Comment by NyakudyaA** [comment]
Any update on this. Reopen if you need to

**Comment by stevenjh** [comment]
Hi there, I'm working on this at the moment and running into issues too, same situation as the original poster, a completely standard build runs on windows 10, but not in Azure.

I think it relates to the way volumes are handled so I'm trying to adjust the build to remove volumes, and take advantage of Azure Docker Containers built in[ persistence of the 'home'  directory](https://docs.microsoft.com/en-us/azure/app-service/faq-app-service-linux#i-m-using-my-own-custom-container--i-want-the-platform-to-mount-an-smb-share-to-the---home---directory-).

I've taken the following steps so far, and this results in a local (windows 10 built) image that will start tomcat, but not geoserver.

**.env**
GEOSERVER_DATA_DIR=/home/geoserver/data_dir
FOOTPRINTS_DATA_DIR=/home/geoserver/footprints_dir
GEOWEBCACHE_CACHE_DIR=/home/geoserver/gwc

**Dockerfile**
adjust lines 34,37,38 to reflect above changes - why don't these read from the .env?
remove line 75 for the VOLUME folders

**docker-compose-build.yml**
remove the reference to volumes

Attempts to restart geoserver through tomcat application manager trigger the following logs that seem relevant
```21-Jun-2021 22:15:27.745 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [12147] milliseconds
21-Jun-2021 22:22:51.037 INFO [http-nio-8080-exec-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.geotools.util.factory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
21-Jun-2021 22:22:51.365 WARNING [http-nio-8080-exec-1] it.geosolutions.imageio.gdalframework.GDALUtilities.loadGDAL Failed to load the GDAL native libs. This is not a problem unless you need to use the GDAL plugins: they won't be enabled.
java.lang.UnsatisfiedLinkError: Native Library /usr/local/gdal_native_libs/libgdaljni.so already loaded in another classloader
21-Jun-2021 22:22:51.389 WARNING [http-nio-8080-exec-1] it.geosolutions.imageio.plugins.turbojpeg.TurboJpegUtilities.loadTurboJpeg Failed to load the TurboJpeg native libs. This is not a problem, but the TurboJpeg encoder won't be available: java.lang.UnsatisfiedLinkError: Native Library /opt/libjpeg-turbo/lib64/libturbojpeg.so.0.1.0 already loaded in another classloader
21-Jun-2021 22:22:51.728 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
21-Jun-2021 22:22:51.728 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.  
21-Jun-2021 22:22:51.729 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
21-Jun-2021 22:22:51.730 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.  
21-Jun-2021 22:22:53.247 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'MonitorDAO', but ApplicationContext is unset.
21-Jun-2021 22:22:53.248 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.  
21-Jun-2021 22:22:53.248 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
21-Jun-2021 22:22:53.248 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.  
21-Jun-2021 22:22:53.337 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.
21-Jun-2021 22:22:53.337 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.  
21-Jun-2021 22:22:53.337 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
21-Jun-2021 22:22:53.337 WARNING [http-nio-8080-exec-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.  
21-Jun-2021 22:22:53.795 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
21-Jun-2021 22:22:53.797 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors
21-Jun-2021 22:22:53.815 INFO [http-nio-8080-exec-1] org.geoserver.GeoserverInitStartupListener.contextDestroyed Beginning GeoServer cleanup sequence```

**Comment by stevenjh** [comment]
I've done some more tinkering with this and found that the default build triggered with `docker-compose -f docker-compose-build.yml up -d --build` does work, once tagged, pushed to azure container registry, and then loaded.

It just doesn't recognise the .env file at all during startup.

Setting the environment variables in the Azure Containers _Configuration_ blade _Application Settings_ translates them into the command `docker run` command/environment, allowing the GEOSERVER_DATA_DIR to be set into the home path and persisted across restarts.

So the image is working as is, and it's possible I'm misunderstanding how the .env file is working/applied in a deployed application.
