### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by xiyany** [kartoza/docker-geoserver#123]
Where can I set memory leaks，like https://docs.geoserver.org/stable/en/user/production/container.html#optimize-your-jvm

**Comment by NyakudyaA** [comment]
> Where can I set memory leaks，like https://docs.geoserver.org/stable/en/user/production/container.html#optimize-your-jvm

You can use  the environment variables at startup

* INITIAL_MEMORY
* MAXIMUM_MEMORY
Please look in the README where it mentions Tomcat properties:

**Comment by xiyany** [comment]
Thank you for your prompt reply
