### ISSUE TITLE
GDAL VRT files

### ISSUE THREAD

**Issue by medis87** [kartoza/docker-geoserver#125]
Hi,

I need to publish GDAL VRT files, but it is not in the stores list. I saw the ImageI/O-Ext GDAL Coverage Extension version is:

Module Name: ImageI/O-Ext GDAL Coverage Extension
Module ID: gs-gdal
Version: 1.3.2
Component: GridCoverage2DReader
Message:
JNI GDAL Wrapper Version: 2.2.0
GDAL Version: 1.9.2
GDAL Release Date: 20121008
GDAL Build Info: GDAL 1.9.2, released 2012/10/08

Could it be because of the gdal old version? If yes, how can i update it or how can i publish VRT files? 
I read this tutorial:
https://docs.geoserver.org/latest/en/user/data/raster/gdal.html#linux-packages-and-setup
But it seems every packages and variables are ok.

Thx,
Sophie

**Comment by NyakudyaA** [comment]
> Hi,
> 
> I need to publish GDAL VRT files, but it is not in the stores list. I saw the ImageI/O-Ext GDAL Coverage Extension version is:
> 
> Module Name: ImageI/O-Ext GDAL Coverage Extension
> Module ID: gs-gdal
> Version: 1.3.2
> Component: GridCoverage2DReader
> Message:
> JNI GDAL Wrapper Version: 2.2.0
> GDAL Version: 1.9.2
> GDAL Release Date: 20121008
> GDAL Build Info: GDAL 1.9.2, released 2012/10/08
> 
> Could it be because of the gdal old version? If yes, how can i update it or how can i publish VRT files?
> I read this tutorial:
> https://docs.geoserver.org/latest/en/user/data/raster/gdal.html#linux-packages-and-setup
> But it seems every packages and variable are ok.
> 
> Thx,
> Sophie

Are you sure the extension allows publishing VRT directly? what version
of geoserver are you using

**Comment by medis87** [comment]
Hi,

my Geoserver is 2.16.0.

I'm not really sure, but the other formats aren't in the list, too.

**Comment by NyakudyaA** [comment]
> Hi,
> 
> my Geoserver is 2.16.0.
> 
> I'm not really sure, but the other formats aren't in the list, too.

Hi @medis87 I haven't figured out how to add the gdal formats in geoserver 2.16.0 that's why I haven't really published an official version.
Try to use 2.15.2 and below

**Comment by medis87** [comment]
With 2.15.2 VRT file is in the list, and I could save it, but there is a java error after a try to publish. May be this is, becace we need GDAl 2.2, and not 2.1. I will have a look more deep in our VRT files. Thx.

**Comment by NyakudyaA** [comment]
> With 2.15.2 VRT file is in the list, and I could save it, but there is a java error after a try to publish. May be this is, becace we need GDAl 2.2, and not 2.1. I will have a look more deep in our VRT files. Thx.

Can you share the VRT if you do not mind or post the logs here

**Comment by medis87** [comment]
I attach the whole error message, but I think the main path is:
`Caused by: java.lang.RuntimeException: VRTDerivedRasterBand::IRasterIO:Derived band pixel function 'MSI' not registered.`

[vrt error.txt](https://github.com/kartoza/docker-geoserver/files/4077400/vrt.error.txt)

In our VRT file there is a python function:
```
<VRTDataset rasterXSize="57" rasterYSize="84">
    <SRS>...</SRS>
    <GeoTransform> 758810,  10,  0,  279910,  0, -10 </GeoTransform>
    <VRTRasterBand dataType="Float32" band="1" subClass="VRTDerivedRasterBand">
        <NoDataValue>-99.0</NoDataValue>
        <ComplexSource resampling="nearest">
    <SourceFilename relativeToVRT="1">L2A_82_20200113.tif</SourceFilename>
    <SourceBand>11</SourceBand>
    <NODATA>0</NODATA>
</ComplexSource>
<ComplexSource resampling="nearest">
    <SourceFilename relativeToVRT="1">L2A_82_20200113.tif</SourceFilename>
    <SourceBand>8</SourceBand>
    <NODATA>0</NODATA>
</ComplexSource>
        <PixelFunctionLanguage>Python</PixelFunctionLanguage>
        <PixelFunctionType>MSI</PixelFunctionType>
        <PixelFunctionCode>
            <![CDATA[
import numpy as np

def MSI(in_ar, out_ar, xoff, yoff, xsize, ysize, raster_xsize,raster_ysize, buf_radius, gt, **kwargs):
    # https://github.com/sentinel-hub/custom-scripts/blob/master/sentinel-2/msi/script.js
    # index = B11 / B08
    band1 = in_ar[0].astype(float)
    band2 = in_ar[1].astype(float)
    
    np.seterr(divide="ignore", invalid="ignore")
    
    np.divide(band1, band2, dtype = float, out = out_ar)
    out_ar[np.isnan(out_ar)] = -99.0
    ]]>
        </PixelFunctionCode>
        <SourceTransferType>Float32</SourceTransferType>
    </VRTRasterBand>
</VRTDataset>
```


Should I install python? As I see, it is not in the container.

**Comment by NyakudyaA** [comment]
I think you need to install python in the container
