### ISSUE TITLE
update_passwords.sh is run unconditionally with negative side effects

### ISSUE THREAD

**Issue by NicolaiMogensen** [kartoza/docker-geoserver#127]
`update_passwords.sh` is run unconditionally in the entrypoint with negative side effects when supplying an already existing data_dir.

Not sure if i'm doing it wrong but if i add a new data_dir and edit the `GEOSERVER_DATA_DIR`  in my Dockerfile the `update_scripts.sh` script will run and mangle my `$GEOSERVER_DATA_DIR/security/usergroup/default/users.xml` to be however many rows i had before but all duplicates of the changed admin password resulting in a nasty XML duplicate key error and localhost:8080/geoserver will never get online and tomcat throws a 404. 

If i remove the `update_password.sh` script from the entrypoint everything is working as expected. Is it possible to either add a condition to this script (ie. not running it if an admin row already exist), or fix the `sed` command to not mangle the file if it already has multiple users in it. 

This is only an issue when trying to migrate an already existing data_dir with a security folder.

**Comment by NyakudyaA** [comment]
Hi @NicolaiMogensen You are right the update password script only has a check to see if it has executed before.
 I guess we should add a check also to see if an existing data directory is being used ie migration from one geoserver to another. 
Maybe the quickest way would be to add an environment variable like
`EXISTING_DATA_DIR=true/false` and we only run the script if it's a new installation.
If you have something better I am open to it.

**Comment by NicolaiMogensen** [comment]
I think that's a good solution. Perhaps default it to false so existing images don't get regressions

**Comment by NicolaiMogensen** [comment]
I could open a pull request with something like this added to `entrypoint.sh`
```
if [[ -z "${EXISTING_DATA_DIR}" ]]; then \
    /scripts/update_passwords.sh
fi;
```

**Comment by NyakudyaA** [comment]
> I could open a pull request with something like this added to `entrypoint.sh`
> 
> ```
> if [[ -z "${EXISTING_DATA_DIR}" ]]; then \
>     /scripts/update_passwords.sh
> fi;
> ```

Right on the money. Yes, go ahead and don't forget to add a little explanation to the README
