### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by ozoz77** [kartoza/docker-geoserver#133]
An update of version 2.16.1 to 2.16.2 "may be" required for the latest build (2.16.2) in the read me file.

**For example:**
docker run -d -p 8600:8080 --name geoserver -e STABLE_EXTENSIONS=charts-plugin,charts-plugin kartoza/geoserver:2.16.1

to 

docker run -d -p 8600:8080 --name geoserver -e STABLE_EXTENSIONS=charts-plugin,charts-plugin kartoza/geoserver:2.16.2

**Comment by NyakudyaA** [comment]
Done.
