### ISSUE TITLE
Metadata community extension

### ISSUE THREAD

**Issue by robsalasco** [kartoza/docker-geoserver#136]
Hi!

First, thank you for the awesome work! I'm trying to incorporate the metadata community extension but can't find their name in the community_plugins.txt list. Is it possible to add it? 

https://docs.geoserver.org/latest/en/user/community/metadata/index.html

**Comment by NyakudyaA** [comment]
> Hi!
> 
> First, thank you for the awesome work! I'm trying to incorporate the metadata community extension but can't find their name in the community_plugins.txt list. Is it possible to add it?
> 
> https://docs.geoserver.org/latest/en/user/community/metadata/index.html

Hi @robsalasco , you can make a PR to add it and will merge it,  then the image will be built against it in docker

**Comment by robsalasco** [comment]
yup it's on nightly https://build.geoserver.org/geoserver/master/community-latest/ so... I have to wait I think.

Thank you!
