### ISSUE TITLE
Possible wrong ${CATALINA_HOME}/security folder

### ISSUE THREAD

**Issue by hugomau** [kartoza/docker-geoserver#142]
On script` scripts/update_passwords.sh` and when mapping `${GEOSERVER_DATA_DIR}` to a volume the following code block seems to fail.

```
if [ ! -d "${GEOSERVER_DATA_DIR}/security" ]; then
  cp -r ${CATALINA_HOME}/security ${GEOSERVER_DATA_DIR}
fi
```

Folder `${CATALINA_HOME}/security` does not exist. Is the correct folder `${CATALINA_HOME}/data/security`?

Thank you

**Comment by NyakudyaA** [comment]
> On script` scripts/update_passwords.sh` and when mapping `${GEOSERVER_DATA_DIR}` to a volume the following code block seems to fail.
> 
> ```
> if [ ! -d "${GEOSERVER_DATA_DIR}/security" ]; then
>   cp -r ${CATALINA_HOME}/security ${GEOSERVER_DATA_DIR}
> fi
> ```
> 
> Folder `${CATALINA_HOME}/security` does not exist. Is the correct folder `${CATALINA_HOME}/data/security`?
> 
> Thank you

I will fix this but it doesn’t break anything because of this https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L140

**Comment by hugomau** [comment]
> > On script` scripts/update_passwords.sh` and when mapping `${GEOSERVER_DATA_DIR}` to a volume the following code block seems to fail.
> > ```
> > if [ ! -d "${GEOSERVER_DATA_DIR}/security" ]; then
> >   cp -r ${CATALINA_HOME}/security ${GEOSERVER_DATA_DIR}
> > fi
> > ```
> > 
> > 
> > Folder `${CATALINA_HOME}/security` does not exist. Is the correct folder `${CATALINA_HOME}/data/security`?
> > Thank you
> 
> I will fix this but it doesn’t break anything because of this https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L140

Be aware that `setup.sh `only runs during `docker build`. On the other hand, `update_password.sh` will run on `docker run` startup and, in the case of using a binded mount, folder `${GEOSERVER_DATA_DIR}` will be empty, and it will brake.

**Comment by NyakudyaA** [comment]
> > > On script` scripts/update_passwords.sh` and when mapping `${GEOSERVER_DATA_DIR}` to a volume the following code block seems to fail.
> > > ```
> > > if [ ! -d "${GEOSERVER_DATA_DIR}/security" ]; then
> > >   cp -r ${CATALINA_HOME}/security ${GEOSERVER_DATA_DIR}
> > > fi
> > > ```
> > > 
> > > 
> > > Folder `${CATALINA_HOME}/security` does not exist. Is the correct folder `${CATALINA_HOME}/data/security`?
> > > Thank you
> > 
> > 
> > I will fix this but it doesn’t break anything because of this https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L140
> 
> Be aware that `setup.sh `only runs during `docker build`. On the other hand, `update_password.sh` will run on `docker run` startup and, in the case of using a binded mount, folder `${GEOSERVER_DATA_DIR}` will be empty, and it will brake.

Noted

**Comment by NyakudyaA** [comment]
Merged develop with master.
