### ISSUE TITLE
Can't change default password with provided docker-compose stack

### ISSUE THREAD

**Issue by arkanoid87** [kartoza/docker-geoserver#151]
If I run docker compose as-is, I can login with default password provided "myawesomegeoserver", but when I try to change it via web panel I get "invalid password"

If I change GEOSERVER_ADMIN_PASSWORD environment var before running the container, I can't login nor with my provided password, nor with "myawesomegeoserver".

I'm basically stuck using "myawesomegeoserver" on vanilla image

**Comment by NyakudyaA** [comment]
I think this is because of the geoserver user. The permissions are not being applied properly when using geoserver user. I am going to revert to running it as root until I figure out the docker permissions for running as non root

**Comment by NyakudyaA** [comment]
Fixed already as image is using root
