### ISSUE TITLE
Mangled Datastor Shapefile URL - Failure To Publish Layer

### ISSUE THREAD

**Issue by joncantu** [kartoza/docker-geoserver#157]
I used to be able to simply setup a data store for a shapefile using a public facing AWS S3 URL for the Connection Parameters field and I could publish layers/services for it with no problem. That was version 2.16.0 of Geoserver (build date 18-Sep-2019).

However, on recent Geoserver deploys, the server mangles the URL and attempts to turn it into a file URL like this one for example:
file:///usr/local/tomcat/webapps/Geoserver/https:/myshapefiles.s3.amazonaws.com/testshapefile1.shp
Which, prevents successful Publishing.

Reproduction Steps
Have a public S3 repo with a shapefile in it. For example:
https://usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp

Try to use that URL for in the Connection Parameters Shapefile Location field when configuring a datastore.

Hit the Save button and then it will take you to "Layers" where you can "Publish" it.

After you hit "Publish", you get a stacktrace:

Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /var/www/geoserver/https:/usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp (No such file or directory) at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:329) at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:296) at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:105) at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:342) at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:325) at org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:413) ... 125 more

When you go back into the datastore (Edit), you will find that Geoserver mangled the original URL and turned it into a combination "file" and "http" URL, like this one:

file:///var/www/geoserver/https:/usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp

If you attempt to Save again from the Edit page, you will get an error:

"Could not find file: file:///var/www/geoserver/https:/usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp"

Of course, this is unpublishable.

This used to actually work in the kartoza/geoserver image with version 2.16.0 of Geoserver (build date 18-Sep-2019).

**Comment by NyakudyaA** [comment]
Can you give the commit references that you refer to on 18 September. I will investigate and see what is the diff. Are you sure the 2.16.0 image has recently been updated

**Comment by joncantu** [comment]
I believe this is possibly a geoserver or tomcat container configuration issue?

**Comment by NyakudyaA** [comment]
Just to be careful the community modules are highly unstable as well. But it will be nice to fix this if the error is coming from the image. What’s the commit that you think broke this

**Comment by NyakudyaA** [comment]
> I used to be able to simply setup a data store for a shapefile using a public facing AWS S3 URL for the Connection Parameters field and I could publish layers/services for it with no problem. That was version 2.16.0 of Geoserver (build date 18-Sep-2019).
> 
> However, on recent Geoserver deploys, the server mangles the URL and attempts to turn it into a file URL like this one for example:
> file:///usr/local/tomcat/webapps/Geoserver/https:/myshapefiles.s3.amazonaws.com/testshapefile1.shp
> Which, prevents successful Publishing.
> 
> Reproduction Steps
> Have a public S3 repo with a shapefile in it. For example:
> https://usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp
> 
> Try to use that URL for in the Connection Parameters Shapefile Location field when configuring a datastore.
> 
> Hit the Save button and then it will take you to "Layers" where you can "Publish" it.
> 
> After you hit "Publish", you get a stacktrace:
> 
> Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /var/www/geoserver/https:/usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp (No such file or directory) at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:329) at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:296) at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:105) at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:342) at org.geoserver.catalog.CatalogBuilder.buildFeatureType(CatalogBuilder.java:325) at org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:413) ... 125 more
> 
> When you go back into the datastore (Edit), you will find that Geoserver mangled the original URL and turned it into a combination "file" and "http" URL, like this one:
> 
> file:///var/www/geoserver/https:/usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp
> 
> If you attempt to Save again from the Edit page, you will get an error:
> 
> "Could not find file: file:///var/www/geoserver/https:/usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp"
> 
> Of course, this is unpublishable.
> 
> This used to actually work in the kartoza/geoserver image with version 2.16.0 of Geoserver (build date 18-Sep-2019).

@joncantu what region should I use to test. Can you try out the 2.17.0 image. For me to test i will need to full params you are using

**Comment by joncantu** [comment]
@NyakudyaA Can you download this shapefile directly if you click on the link?:

https://usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp

I would expect this URL to work as the Shapefile Location in Connection Parameters of Shapefile datastore.

I could not get it to work with any recent deployments of Geoserver. For example, if I were to pull the latest kartoza/geoserver docker image and run it locally.

**Comment by NyakudyaA** [comment]
> @NyakudyaA Can you download this shapefile directly if you click on the link?:
> 
> https://usgs-shapefiles.s3.amazonaws.com/5e57f958bf0a3642014f3e6c/1790-1823_BlackCone_flow.shp
> 
> I would expect this URL to work as the Shapefile Location in Connection Parameters of Shapefile datastore.
> 
> I could not get it to work with any recent deployments of Geoserver. For example, if I were to pull the latest kartoza/geoserver docker image and run it locally.

I expect the URL to have the following format
s3://landsat-pds/L8/001/002/LC80010022016230LGN00/LC80010022016230LGN00_B1.TIF?useAnon=true&awsRegion=US_WEST_2 so I need to know yor region to test it

**Comment by joncantu** [comment]
@NyakudyaA That format is only for an S3GeoTiff (Coveragestore) not a Shapefile (Datastore).  Those are two distinctly different GIS formats (raster vs vector).

**Comment by NyakudyaA** [comment]
Ping @joncantu Still an issue here or not

**Comment by joncantu** [comment]
I’m no longer at USGS. However, last I checked this was a problem with Geoserver. 
On Wednesday, August 5, 2020, 10:50 AM, mazano <notifications@github.com> wrote:




Ping @joncantu Still an issue here or not
