### ISSUE TITLE
How to add geoserver extension?

### ISSUE THREAD

**Issue by syafiqFiqq** [kartoza/docker-geoserver#16]
Im trying to add geoserver plugin which is control-flow but to no avail.

i add the control-flow jar file to the /usr/local/tomcat/webapps/geoserver/WEB-INF/lib
and the controlflow.properties file to the /opt/geoserver/data_dir

below is my dockerfile

FROM kartoza/geoserver
ADD gs-control-flow-2.9.1.jar /usr/local/tomcat/webapps/geoserver/WEB-INF/lib
ADD controlflow.properties /opt/geoserver/data_dir

however it doesnt detect it.

do you know how to implement this on docker?
Your help is much appreciated..

**Comment by timlinux** [comment]
@NyakudyaA can you take a look at this?

**Comment by gubuntu** [comment]
@syafiqFiqq you might want to try my fork at https://github.com/gubuntu/docker-geoserver. I'm trying a slightly different approach. It installs control flow fine, remember you still have to configure it after installing.

**Comment by syafiqFiqq** [comment]
@timlinux @gubuntu hi, i have managed to add the plugin after some tweak, however, can i know where to put the config for the control flow, which is the controlflow.properties?

**Comment by syafiqFiqq** [comment]
problem solved. I found that the config file should be in the root of data_dir.
Thanks all.
