### ISSUE TITLE
Support fonts with otf format

### ISSUE THREAD

**Issue by exotfboy** [kartoza/docker-geoserver#160]
Hi:

As said in the [readme](https://github.com/kartoza/docker-geoserver#installing-extra-fonts), we just need to mount the fonts to `/opt/fonts`:
> If you have downloaded extra fonts you can mount the folder to the path /opt/fonts. This will ensure that all the .ttf files are copied to the correct path during initialisation.

But how about the fonts with `.otf` format?

**Comment by NyakudyaA** [comment]
> Hi:
> 
> As said in the [readme](https://github.com/kartoza/docker-geoserver#installing-extra-fonts), we just need to mount the fonts to `/opt/fonts`:
> 
> > If you have downloaded extra fonts you can mount the folder to the path /opt/fonts. This will ensure that all the .ttf files are copied to the correct path during initialisation.
> 
> But how about the fonts with `.otf` format?

We haven't implemented this as well but you could just modify 
in setup.sh add the following
```
create_dir /usr/share/fonts/opentype
```

and also add an entry in start.sh like the below
```
if ls ${FONTS_DIR}/*.otf > /dev/null 2>&1; then \
      cp -rf ${FONTS_DIR}/*.otf /usr/share/fonts/opentype/; \
	fi;
```
You can do the PR I have no time for now
