### ISSUE TITLE
Tomcat configuration poses security risk

### ISSUE THREAD

**Issue by clncy** [kartoza/docker-geoserver#162]
Hi,

It appears that a tomcat user is being created with the password `tomcat`:
https://github.com/kartoza/docker-geoserver/blob/74c4515fb22c79379c1ecdc8b582616c7342cf2f/scripts/start.sh#L87

This user looks to be given the following roles:
https://github.com/kartoza/docker-geoserver/blob/74c4515fb22c79379c1ecdc8b582616c7342cf2f/build_data/tomcat-users.xml#L45

Anyone with access to geoserver can then access the management gui at `{server}:{port}/manager/html`, where they have the ability to (amongst other things) create and stop applications. 

I'm not particularly familiar with tomcat, so you'll have to excuse me if I'm missing something, but I think it would be best if:
- The creation of a tomcat user with these privileges is not default behaviour.
- Or, if this behaviour is unavoidable, users of this image should be given the ability to change the tomcat password, and strongly advised to do so.

Thanks.

**Comment by lucernae** [comment]
Thanks @clncy 

The tomcat password is configurable via `TOMCAT_PASSWORD` environment variable (I think).
But to be honest, I always use it by guarding the `/manager` endpoint under nginx, so the exposed service to the public (over internet) is only `/geoserver`, so I never think about this use case before. I will try it and confirm it first.

**Comment by NyakudyaA** [comment]
@clncy There is an environment variable  `TOMCAT_EXTRAS` that controls having tomcat extras, so if you have that as true then you will need to also have to specify the tomcat password. 

Maybe we need to have the `TOMCAT_EXTRAS` default to false and have the readme to be verbose

**Comment by clncy** [comment]
Thanks for the quick responses. @NyakudyaA I think that sounds like a good solution.

**Comment by lucernae** [comment]
@clncy @NyakudyaA 
Confirmed that the settings behaves as intented.

The following docker-compose recipes works:
```
version: '3'
services:
  geoserver:
    image: kartoza/geoserver
    environment:
      TOMCAT_EXTRAS: "True"
      TOMCAT_PASSWORD: mypassword
    ports:
      - "8080:8080"
```

The new tomcat password has changed.

Practically speaking, I imagine you wouldn't need tomcat manager at all since you would normally restarting the entire service via docker command. But I agree we should put that into readme.

**Comment by NyakudyaA** [comment]
> @clncy @NyakudyaA
> Confirmed that the settings behaves as intented.
> 
> The following docker-compose recipes works:
> 
> ```
> version: '3'
> services:
>   geoserver:
>     image: kartoza/geoserver
>     environment:
>       TOMCAT_EXTRAS: "True"
>       TOMCAT_PASSWORD: mypassword
>     ports:
>       - "8080:8080"
> ```
> 
> The new tomcat password has changed.
> 
> Practically speaking, I imagine you wouldn't need tomcat manager at all since you would normally restarting the entire service via docker command. But I agree we should put that into readme.

@lucernae  Maybe in environments where you want someone to manage your instance without giving them access to the server where you have deployed the docker container
