### ISSUE TITLE
Build with CORS Support not working  (following the docs)

### ISSUE THREAD

**Issue by messaoudi-mounir** [kartoza/docker-geoserver#174]
Hi, 
By default geoserver disable the cors (check WEB-INF/web.xml file).

the web.xml in usr/local/tomcat/conf/web.xml  (if it's exist, used for all deployed apps in Tomcat) is overrided by web.xml in geoserver/WEB-INF/

So, include a static web xml with CORS support web.xml, you must create the file at **resources/overlays/usr/local/tomcat/geoserver/WEB-INF/**

**Comment by NyakudyaA** [comment]
@messaoudi-mounir The image should be enabled for CORS by default. Can you test this and let me know if you experiencing problems.

**Comment by NyakudyaA** [comment]
Cors are enabled by default from line 73 in the dockerfile
