### ISSUE TITLE
Render results are messy

### ISSUE THREAD

**Issue by lwx314781** [kartoza/docker-geoserver#175]
I Released shape of point data and rendered with POI style，so  name property of result  is a messy code. 
I don't know if anyone has. Thank you very much

**Comment by NyakudyaA** [comment]
> I Released shape of point data and rendered with POI style，so name property of result is a messy code.
> I don't know if anyone has. Thank you very much

Can you please describe the problem and the steps you tried. Ideally screeenshots

**Comment by lwx314781** [comment]
step1  Download the image and launch it successfully
step2  Enter geoserver and release a Shape file using a similar POI style
step3  switch to Layer Preview tab and use openlayer preview

**Comment by NyakudyaA** [comment]
This is still not clear. Can you add more detail otherwise will close this

**Comment by lwx314781** [comment]
使用docker镜像，启动geoserver服务后，发布一个矢量数据（点矢量），记住一定使用一个可以显示NAME属性的style
然后再geoserver的预览，发现NAME属性是乱码的。（我试图改了很多编码方式，但是都无济于事）

**Comment by NyakudyaA** [comment]
Can you share your data, cannot replicate here
