### ISSUE TITLE
Can't connect to included PostGIS or any other DB

### ISSUE THREAD

**Issue by Bandit253** [kartoza/docker-geoserver#178]
Hi,
Love your work.
I ran `docker-compose up -d` and I am unable to connect to the DB from Geoserver, nor ant other .  I can from QGIS
![image](https://user-images.githubusercontent.com/9003261/90323232-ca996280-dfa1-11ea-8ec8-463ec6d63746.png)

This is also the behaviour I have with an existing PostGIS DB I have.

Any clues

**Comment by NyakudyaA** [comment]
What docker-compose did you use.

If you exec into the geoserver container are you able to ping the dB container ?

**Comment by Bandit253** [comment]
This is the one I used 'https://github.com/kartoza/docker-geoserver/blob/master/docker-compose.yml'
I did comment out the backup db- as per docs...

1.docker run --name "postgisX" -d -t kartoza/postgis:12.0
2. docker exec -it c57ee9883ac6 /bin/bash
3. ping <IP> 192.0.17.3

**Comment by Bandit253** [comment]
Sorry re-reading that maybe a little confusing
I **can** connect to the DB (and another existing one) from QGIS
NOT from the GeoServer 
One google result said the error was because Geoserver didn't have the PostGIS driver - I doubt that
Oh and the ping above was unsuccessful

**Comment by NyakudyaA** [comment]
You only need the PostgreSQL client if you need to access the database inside the geoserver container using psql. In all other situations geoserver store will connect to the database because it has the necessary libs. 

When you define a store make sure to identity the host properly. The host should be db not localhost

**Comment by Bandit253** [comment]
Yep OK, I get that but what is the 'host'? Is it the container name, it address?
Sorry I am such a noob, how do I find the host?
Thanks so much in advance for all the assistance and fabulous images.

**Comment by NyakudyaA** [comment]
![db-host](https://user-images.githubusercontent.com/2510900/90660591-6b0fb100-e246-11ea-89ec-712448be73a3.png)

**Comment by Bandit253** [comment]
Thanks again but unfortunately that does not seem to work, or I have missed the point of your red arrow :)
I have tried docker-env and docker-env/db.env and now I get a different errror
![image](https://user-images.githubusercontent.com/9003261/90730964-5d246380-e30c-11ea-969b-3aa6f5982d0e.png)
![image](https://user-images.githubusercontent.com/9003261/90731082-87762100-e30c-11ea-9369-1f5dcbf6c40e.png)

**Comment by NyakudyaA** [comment]
@Bandit253  change the host from `docker-env` to `db`

Read https://stackoverflow.com/questions/35832095/difference-between-links-and-depends-on-in-docker-compose-yml

**Comment by Bandit253** [comment]
reading that now but merely changing to 'db' resulted in 
![image](https://user-images.githubusercontent.com/9003261/90732016-cd7fb480-e30d-11ea-852c-ee55bb976331.png)

**Comment by NyakudyaA** [comment]
Inside the container, you connect to the port `5432`

**Comment by Bandit253** [comment]
mmm if that is possible, maybe It be my particular problem....
would these port configs be conflicting?
![image](https://user-images.githubusercontent.com/9003261/90733006-46334080-e30f-11ea-9feb-2f54345361dc.png)

**Comment by NyakudyaA** [comment]
Hi @Bandit253 Can you please look at our offering here https://kartoza.com/en/shop/product/support/. You could take out a small office contract and we can give you a detailed walkthrough in setting up this service and a crash course in docker

**Comment by NyakudyaA** [comment]
This is user error
