### ISSUE TITLE
Including mongodb-plugin breaks tomcat/geoserver

### ISSUE THREAD

**Issue by mitkin** [kartoza/docker-geoserver#179]
Issue tested with geoserver 2.16.2, 2.17.1 and 2.17.2.

I run docker container as per instructions, but if I include mongodb-plugin in stable_extensions list, I get 404 page served by tomcat. If I don't include mongodb-plugin geoserver instance works as expected. Including a different plugin, for example netcdf-plugin does not break anything.

Can anyone confirm the same behaviour for when mongodb plugin is loaded?

**Comment by NyakudyaA** [comment]
@mitkin please take a look at http://osgeo-org.1560.x6.nabble.com/JIRA-GEOS-9403-MongoDB-Plugin-breaks-GeoServer-Admin-UI-td5422413.html

**Comment by mitkin** [comment]
thanks. Adding app-schema-plugin didn't help though, admin ui page still returns 404. Actually when app-schema-plugin is loaded alone (no mongodb-plugin) same thing happens.

**Comment by NyakudyaA** [comment]
@mitkin can you try it using the latest image 2.17.2

**Comment by mitkin** [comment]
> @mitkin can you try it using the latest image 2.17.2

@NyakudyaA works fine! thanks!
