### ISSUE TITLE
SSL / HTTPS

### ISSUE THREAD

**Issue by rumski20** [kartoza/docker-geoserver#18]
I was able to get a container up and running no problem using the instructions you've provided. However, I ideally want Geoserver being served over HTTPS, which I have set up on the host.  
Do you have any idea how to enable this on the container? Is it a Tomcat issue?
Here's the error I receive when I try to access it over HTTPS:

`An error occurred during a connection to data.nrri.umn.edu:32770. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG`

Might be something to do with the port that's being used??
Thanks for any assistance you can provide.

**Comment by timlinux** [comment]
Hmm sorry I don't know what is causing that - maybe its better to ask first in upstream geoserver lists?

**Comment by modulitos** [comment]
@rumski20 I'm not sure if this is useful for you, but I set up an nginx server in front of Geoserver that uses LetsEncrypt to serve all of the Geoserver content of HTTPS. Here is the Docker Compose file: https://github.com/mapseed/docker-geoserver/blob/master/docker-compose.yml#L60-L75

The setup can definitely use some improvement, but it's been working well enough for me. Feel free to ping me if you want to try it out!

**Comment by rumski20** [comment]
@modulitos Thanks for the idea. I ended up solving the issue by setting my proxy base URL (which I really should have done to begin with): http://docs.geoserver.org/latest/en/user/configuration/globalsettings.html#proxy-base-url

**Comment by micahl98** [comment]
Rumski20; We are using this container for geoserver and also need to run it with SSL... can you help guide us in how you configured this? I found the proxy base URL, but am unsure what to do with it. Also we prefer using letsencrypt..... do we set this up outside the container on the host? Thanks!
