### ISSUE TITLE
Version numbering is confusing / broken?

### ISSUE THREAD

**Issue by petermant** [kartoza/docker-geoserver#180]
In build.sh, there are three variables which ought to dictate the version being built:

MAJOR=2
MINOR=17
BUGFIX=1

However, in the docker file, there is this:

ARG GS_VERSION=2.17.2
ARG WAR_URL=http://downloads.sourceforge.net/project/geoserver/GeoServer/${GS_VERSION}/geoserver-${GS_VERSION}-war.zip

So it's not clear whether the build is 2.17.1 or 2.17.2 - especially as the last commit message into master talks about bumping the geoserver version to 2.17.2, but when building with build.sh what you actually get is 2.17.1.

Would it be prudent to change the scripts so that the version overrides are clearer, e.g. so that the GS_VERSION arg is composed of (or replaced by) the major/minor/bugfix environment variables?

When I build and deploy from master, I get this in the About Geoserver page:

About GeoServer

General information about GeoServer

    Build Information
        GeoServer Version
        **2.17.1**

**Comment by NyakudyaA** [comment]
This has been fixed.
