### ISSUE TITLE
geoserver can't open

### ISSUE THREAD

**Issue by zuohuaijun** [kartoza/docker-geoserver#184]
docker run --name geoserver -v /e/DockerData/geoserver_data:/opt/geoserver/data_dir -p 8080:8080 -d kartoza/geoserver

The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**Comment by NyakudyaA** [comment]
> docker run --name geoserver -v /e/DockerData/geoserver_data:/opt/geoserver/data_dir -p 8080:8080 -d kartoza/geoserver
> 
> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Can you share your logs? Can you also try it without a volume or using docker volume

**Comment by zuohuaijun** [comment]
NOTE: Picked up JDK_JAVA_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED

[0.002s][warning][gc,ergo] -XX:NewSize and -XX:MaxNewSize override -XX:NewRatio

18-Sep-2020 10:56:15.632 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name: Apache Tomcat/9.0.20

18-Sep-2020 10:56:15.639 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built: May 3 2019 22:26:00 UTC

18-Sep-2020 10:56:15.639 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.20.0

18-Sep-2020 10:56:15.640 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name: Linux

18-Sep-2020 10:56:15.640 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version: 4.19.128-microsoft-standard

18-Sep-2020 10:56:15.640 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture: amd64

18-Sep-2020 10:56:15.640 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home: /usr/lib/jvm/java-11-openjdk-amd64

18-Sep-2020 10:56:15.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version: 11.0.3+1-Debian-1bpo91

18-Sep-2020 10:56:15.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor: Oracle Corporation

18-Sep-2020 10:56:15.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE: /usr/local/tomcat

18-Sep-2020 10:56:15.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME: /usr/local/tomcat

18-Sep-2020 10:56:15.652 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED

18-Sep-2020 10:56:15.653 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED

18-Sep-2020 10:56:15.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED

18-Sep-2020 10:56:15.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties

18-Sep-2020 10:56:15.654 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager

18-Sep-2020 10:56:15.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true

18-Sep-2020 10:56:15.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms2G

18-Sep-2020 10:56:15.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx4G

18-Sep-2020 10:56:15.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PerfDataSamplingInterval=500

18-Sep-2020 10:56:15.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.referencing.forceXY=true

18-Sep-2020 10:56:15.655 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:SoftRefLRUPolicyMSPerMB=36000

18-Sep-2020 10:56:15.656 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewRatio=2

18-Sep-2020 10:56:15.656 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC

18-Sep-2020 10:56:15.656 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxGCPauseMillis=200

18-Sep-2020 10:56:15.656 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ParallelGCThreads=20

18-Sep-2020 10:56:15.656 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ConcGCThreads=5

18-Sep-2020 10:56:15.656 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:InitiatingHeapOccupancyPercent=70

18-Sep-2020 10:56:15.656 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+CMSClassUnloadingEnabled

18-Sep-2020 10:56:15.657 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF8

18-Sep-2020 10:56:15.657 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Duser.timezone=GMT

18-Sep-2020 10:56:15.657 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.request.encoding=UTF-8

18-Sep-2020 10:56:15.657 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.response.encoding=UTF-8

18-Sep-2020 10:56:15.657 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DGEOSERVER_DATA_DIR=/opt/geoserver/data_dir

18-Sep-2020 10:56:15.657 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.shapefile.datetime=true

18-Sep-2020 10:56:15.658 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ds3.properties.location=/opt/geoserver/data_dir/s3.properties

18-Sep-2020 10:56:15.658 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer.useThreadLocal=false

18-Sep-2020 10:56:15.658 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer.pixelsize=8192

18-Sep-2020 10:56:15.658 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewSize=300m

18-Sep-2020 10:56:15.658 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlog4j.configuration=/usr/local/tomcat/log4j.properties

18-Sep-2020 10:56:15.659 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --patch-module=java.desktop=/usr/local/tomcat/marlin-0.9.4.2-Unsafe-OpenJDK9.jar

18-Sep-2020 10:56:15.659 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer=org.marlin.pisces.PiscesRenderingEngine

18-Sep-2020 10:56:15.659 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dgeoserver.xframe.shouldSetPolicy=true

18-Sep-2020 10:56:15.659 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-modules=java.se

18-Sep-2020 10:56:15.659 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED

18-Sep-2020 10:56:15.659 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED

18-Sep-2020 10:56:15.660 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.nio=ALL-UNNAMED

18-Sep-2020 10:56:15.660 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED

18-Sep-2020 10:56:15.660 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.management/sun.management=ALL-UNNAMED

18-Sep-2020 10:56:15.660 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED

18-Sep-2020 10:56:15.661 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048

18-Sep-2020 10:56:15.661 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources

18-Sep-2020 10:56:15.661 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027

18-Sep-2020 10:56:15.661 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=

18-Sep-2020 10:56:15.661 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat

18-Sep-2020 10:56:15.661 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat

18-Sep-2020 10:56:15.662 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp

18-Sep-2020 10:56:15.662 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.5.2].

18-Sep-2020 10:56:15.662 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].

18-Sep-2020 10:56:15.662 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]

18-Sep-2020 10:56:15.666 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0l 10 Sep 2019]

18-Sep-2020 10:56:15.963 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]

18-Sep-2020 10:56:15.993 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]

18-Sep-2020 10:56:15.996 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [586] milliseconds

18-Sep-2020 10:56:16.066 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]

18-Sep-2020 10:56:16.067 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.20]

18-Sep-2020 10:56:16.076 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/geoserver]

18-Sep-2020 10:56:25.221 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

log4j:WARN No appenders could be found for logger (org.geotools.util.factory).

log4j:WARN Please initialize the log4j system properly.

log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

18-Sep-2020 10:56:26.675 INFO [main] it.geosolutions.imageio.plugins.turbojpeg.TurboJpegUtilities.load TurboJPEG library loaded (turbojpeg)

18-Sep-2020 10:56:26.747 INFO [main] it.geosolutions.imageio.gdalframework.GDALUtilities.loadGDAL GDAL Native Library loaded (version: 2.1.2)

18-Sep-2020 10:56:27.445 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.

18-Sep-2020 10:56:27.447 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.

18-Sep-2020 10:56:27.451 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.

18-Sep-2020 10:56:27.451 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.

18-Sep-2020 10:56:31.957 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.

18-Sep-2020 10:56:31.958 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.

18-Sep-2020 10:56:31.959 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.

18-Sep-2020 10:56:31.959 WARNING [main] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.geotools.image.ImageWorker (file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gt-coverage-23.2.jar) to constructor com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi()

WARNING: Please consider reporting this to the maintainers of org.geotools.image.ImageWorker

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

18-Sep-2020 10:56:44.629 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/geoserver] has finished in [28,552] ms

18-Sep-2020 10:56:44.645 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]

18-Sep-2020 10:56:44.678 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]

18-Sep-2020 10:56:44.698 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [28,701] milliseconds

**Comment by zuohuaijun** [comment]
docker run --name geoserver -p 8080:8080 -d kartoza/geoserver.     it without a volume, also can't open.

**Comment by NyakudyaA** [comment]
> docker run --name geoserver -p 8080:8080 -d kartoza/geoserver. it without a volume, also can't open.

If you go to http://localhost:8080 it will show you that error message because by default tomcat web app is off, https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L44

try : docker run --name geoserver -p 8080:8080 -e TOMCAT_EXTRAS=true -d kartoza/geoserver
this will respond when you go to http://localhost:8080 and also http://localhost:8080/geoserver

**Comment by zuohuaijun** [comment]
It's ok http://localhost:8080/geoserver,but not http://localhost:8080 . Thank you.
