### ISSUE TITLE
Cannot publish coverage store and layers

### ISSUE THREAD

**Issue by mcfwesh** [kartoza/docker-geoserver#194]
I cannot seem to publish coverage stores for tiff files in Geoserver. I use the REST API to do this. The store shows up, but I cannot publish layers as it gives errors.

 I think this might be due to the user settings in the docker geoserver because this works on my local geoserver. I have not tampered with anything yet. Is there anything I can do?
<img width="1440" alt="Screenshot 2020-10-21 at 15 34 13" src="https://user-images.githubusercontent.com/53073382/96727155-0e9a5080-13b3-11eb-9fa5-357193e866ad.png">

**Comment by NyakudyaA** [comment]
@mcfwesh What geoserver version are you running ?. What command are you using to create the layer using the rest api.
What version is it working from. We are trying to migrate to a dedicated user to navigate docker security issues

**Comment by mcfwesh** [comment]
Geoserver version. 2.18.0
Command used : From Python; 
`import requests

# define your parameters
url = 'http://localhost:8600/geoserver/rest/workspaces'
headers = {'Content-Type': 'text/xml'}
auth = ('admin', 'myawesomegeoserver')
workspace = '<workspace><name>h2-atlas</name></workspace>'
datastore = """
<dataStore>
  <name>nyc</name>
  <connectionParameters>
    <host>db</host>
    <port>5432</port>
    <database>testGIS</database>
    <user>postgres</user>
    <passwd>password</passwd>
    <dbtype>postgis</dbtype>
  </connectionParameters>
</dataStore>
"""

coveragestore = """
<coverageStore>
  <name>nyc</name>
  <workspace><name>h2-atlas</name></workspace>
   <enabled>true</enabled>
  <type>GeoTIFF</type>
  <url>/Users/nate/Desktop/test/excluded-areas.tiff</url>
</coverageStore>
"""

coveragestore_layer = """
<coverage>
          <name>imageGeoTiffWGS84</name>
          <title>imageGeoTiffWGS84</title>
          <nativeCRS>GEOGCS[&quot;WGS 84&quot;,DATUM[&quot;World Geodetic System 1984&quot;,SPHEROID[&quot;WGS 84&quot;,6378137.0, 298.257223563, AUTHORITY[&quot;EPSG&quot;,&quot;7030&quot;]],AUTHORITY[&quot;EPSG&quot;,&quot;6326&quot;]],PRIMEM[&quot;Greenwich&quot;, 0.0, AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],UNIT[&quot;degree&quot;, 0.017453292519943295],AXIS[&quot;Geodetic longitude&quot;, EAST],AXIS[&quot;Geodetic latitude&quot;, NORTH],AUTHORITY[&quot;EPSG&quot;,&quot;4326&quot;]]</nativeCRS>
          <srs>EPSG:4326</srs>
          <latLonBoundingBox><minx>-179.958</minx><maxx>-105.002</maxx><miny>-65.007</miny><maxy>65.007</maxy><crs>EPSG:4326</crs></latLonBoundingBox>
          </coverage>
"""

# ws = requests.post(url, headers=headers, auth=auth, data=workspace)
ds = requests.post('http://localhost:8600/geoserver/rest/workspaces/h2-atlas/coveragestores?configure=all',
                   headers=headers, auth=auth, data=coveragestore)
requests.post('http://localhost:8600/geoserver/rest/workspaces/h2-atlas/coveragestores/nyc/coverages',
              headers=headers, auth=auth, data=coveragestore_layer)`
Do you mean the Docker version?

**Comment by mcfwesh** [comment]
Geoserver version: 2.18.0. The latest on the image
Python Code below:
```
import requests

# define your parameters
url = 'http://localhost:8600/geoserver/rest/workspaces'
headers = {'Content-Type': 'text/xml'}
auth = ('admin', 'myawesomegeoserver')
workspace = '<workspace><name>h2-atlas</name></workspace>'
datastore = """
<dataStore>
  <name>nyc</name>
  <connectionParameters>
    <host>db</host>
    <port>5432</port>
    <database>testGIS</database>
    <user>postgres</user>
    <passwd>password</passwd>
    <dbtype>postgis</dbtype>
  </connectionParameters>
</dataStore>
"""

coveragestore = """
<coverageStore>
  <name>nyc</name>
  <workspace><name>h2-atlas</name></workspace>
   <enabled>true</enabled>
  <type>GeoTIFF</type>
  <url>/Users/nate/Desktop/test/excluded-areas.tiff</url>
</coverageStore>
"""

coveragestore_layer = """
<coverage>
          <name>imageGeoTiffWGS84</name>
          <title>imageGeoTiffWGS84</title>
          <nativeCRS>GEOGCS[&quot;WGS 84&quot;,DATUM[&quot;World Geodetic System 1984&quot;,SPHEROID[&quot;WGS 84&quot;,6378137.0, 298.257223563, AUTHORITY[&quot;EPSG&quot;,&quot;7030&quot;]],AUTHORITY[&quot;EPSG&quot;,&quot;6326&quot;]],PRIMEM[&quot;Greenwich&quot;, 0.0, AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],UNIT[&quot;degree&quot;, 0.017453292519943295],AXIS[&quot;Geodetic longitude&quot;, EAST],AXIS[&quot;Geodetic latitude&quot;, NORTH],AUTHORITY[&quot;EPSG&quot;,&quot;4326&quot;]]</nativeCRS>
          <srs>EPSG:4326</srs>
          <latLonBoundingBox><minx>-179.958</minx><maxx>-105.002</maxx><miny>-65.007</miny><maxy>65.007</maxy><crs>EPSG:4326</crs></latLonBoundingBox>
          </coverage>
"""

# ws = requests.post(url, headers=headers, auth=auth, data=workspace)
ds = requests.post('http://localhost:8600/geoserver/rest/workspaces/h2-atlas/coveragestores?configure=all',
                   headers=headers, auth=auth, data=coveragestore)
requests.post('http://localhost:8600/geoserver/rest/workspaces/h2-atlas/coveragestores/nyc/coverages',
              headers=headers, auth=auth, data=coveragestore_layer)

# print((ds.text))

```
I do not get the third question

**Comment by NyakudyaA** [comment]
> Geoserver version: 2.18.0. The latest on the image
> Python Code below:
> 
> ```
> import requests
> 
> # define your parameters
> url = 'http://localhost:8600/geoserver/rest/workspaces'
> headers = {'Content-Type': 'text/xml'}
> auth = ('admin', 'myawesomegeoserver')
> workspace = '<workspace><name>h2-atlas</name></workspace>'
> datastore = """
> <dataStore>
>   <name>nyc</name>
>   <connectionParameters>
>     <host>db</host>
>     <port>5432</port>
>     <database>testGIS</database>
>     <user>postgres</user>
>     <passwd>password</passwd>
>     <dbtype>postgis</dbtype>
>   </connectionParameters>
> </dataStore>
> """
> 
> coveragestore = """
> <coverageStore>
>   <name>nyc</name>
>   <workspace><name>h2-atlas</name></workspace>
>    <enabled>true</enabled>
>   <type>GeoTIFF</type>
>   <url>/Users/nate/Desktop/test/excluded-areas.tiff</url>
> </coverageStore>
> """
> 
> coveragestore_layer = """
> <coverage>
>           <name>imageGeoTiffWGS84</name>
>           <title>imageGeoTiffWGS84</title>
>           <nativeCRS>GEOGCS[&quot;WGS 84&quot;,DATUM[&quot;World Geodetic System 1984&quot;,SPHEROID[&quot;WGS 84&quot;,6378137.0, 298.257223563, AUTHORITY[&quot;EPSG&quot;,&quot;7030&quot;]],AUTHORITY[&quot;EPSG&quot;,&quot;6326&quot;]],PRIMEM[&quot;Greenwich&quot;, 0.0, AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],UNIT[&quot;degree&quot;, 0.017453292519943295],AXIS[&quot;Geodetic longitude&quot;, EAST],AXIS[&quot;Geodetic latitude&quot;, NORTH],AUTHORITY[&quot;EPSG&quot;,&quot;4326&quot;]]</nativeCRS>
>           <srs>EPSG:4326</srs>
>           <latLonBoundingBox><minx>-179.958</minx><maxx>-105.002</maxx><miny>-65.007</miny><maxy>65.007</maxy><crs>EPSG:4326</crs></latLonBoundingBox>
>           </coverage>
> """
> 
> # ws = requests.post(url, headers=headers, auth=auth, data=workspace)
> ds = requests.post('http://localhost:8600/geoserver/rest/workspaces/h2-atlas/coveragestores?configure=all',
>                    headers=headers, auth=auth, data=coveragestore)
> requests.post('http://localhost:8600/geoserver/rest/workspaces/h2-atlas/coveragestores/nyc/coverages',
>               headers=headers, auth=auth, data=coveragestore_layer)
> 
> # print((ds.text))
> ```
> 
> I do not get the third question

You said `because this works on my local geoserver` so I was asking what version does it work against. I will give it a spin and revert

**Comment by mcfwesh** [comment]
Oh ok. It works against the exact same version. 2.18.0

**Comment by mcfwesh** [comment]
I think to upload a coverage resource and successfully publish the layers, one has to upload from the 'data_dir' of geoserver and not the local storage. This approach also worked with my local geoserver.

Now, when I build the image, the geoserver and postgis volumes are not mounted as folders on automatically. I had to use the 'docker run' command to mount them individually. 
The issue, is when I populate the `geoserver_data_dir` folder locally  with my coverage data(GeoTIFF image), it does not update in the container automatically, which means I do not see it on the  `geoserver_data_dir` interface directory when one wants to create a GeoTiff store, which in turn causes an error when using the REST API.

The question is how do I make this directory update automatically in the container with my files. If there is a better way to achieve this, please let me know. I am new to these things.

**Comment by NyakudyaA** [comment]
@mcfwesh You just need to mount your local folder into the geoserver data-dir something like 
```
docker run -d -p 8600:8080 --name geoserver -v /data/geoserver_data_dir:/opt/geoserver/data_dir kartoza/geoserver:2.18.0 
```
This way you can then just load your layers in /data/geoserver_data then it will be inside the container

**Comment by mcfwesh** [comment]
Thanks for this. I successfully loaded them
