### ISSUE TITLE
Image Pyramid Plugin

### ISSUE THREAD

**Issue by mcfwesh** [kartoza/docker-geoserver#197]
Is the Image pyramid plugin included in the stable plugins allowed? I plan on creating a  raster coverage store of pyramids. If it's not included, is there an alternative?

**Comment by NyakudyaA** [comment]
> Is the Image pyramid plugin included in the stable plugins allowed? I plan on creating a raster coverage store of pyramids. If it's not included, is there an alternative?

Have you read the README?

**Comment by mcfwesh** [comment]
So sorry. I have seen it. I was mistaken between image mosaic and image pyramid
