### ISSUE TITLE
Permissions issue in 2.18

### ISSUE THREAD

**Issue by frankhommers** [kartoza/docker-geoserver#198]
I run this:

`docker run --name geoserver1 -d --restart always -e INITIAL_MEMORY=1536M -e MAXIMUM_MEMORY=3584M -v /srv/geoserver/geoserver1:/opt/geoserver/data_dir -p 8080:8080 kartoza/geoserver:<version>`

And when I replace `<version>` with `2.17.2` it works:

```
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED,
[0.005s][warning][gc,ergo] -XX:NewSize and -XX:MaxNewSize override -XX:NewRatio,
03-Nov-2020 10:49:47.511 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.20,
03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 3 2019 22:26:00 UTC,
03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.20.0,
03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux,
03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-26-generic,
03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64,
03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64,
03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.3+1-Debian-1bpo91,
03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation,
03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat,
03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat,
03-Nov-2020 10:49:47.530 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED,
03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED,
03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED,
03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties,
03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager,
03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1536M,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx3584M,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PerfDataSamplingInterval=500,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.referencing.forceXY=true,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:SoftRefLRUPolicyMSPerMB=36000,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewRatio=2,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC,
03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxGCPauseMillis=200,
03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ParallelGCThreads=20,
03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ConcGCThreads=5,
03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:InitiatingHeapOccupancyPercent=70,
03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+CMSClassUnloadingEnabled,
03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF8,
03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Duser.timezone=GMT,
03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.request.encoding=UTF-8,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.response.encoding=UTF-8,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DGEOSERVER_DATA_DIR=/opt/geoserver/data_dir,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.shapefile.datetime=true,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ds3.properties.location=/opt/geoserver/data_dir/s3.properties,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer.useThreadLocal=false,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer.pixelsize=8192,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewSize=300m,
03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlog4j.configuration=/usr/local/tomcat/log4j.properties,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --patch-module=java.desktop=/usr/local/tomcat/marlin-0.9.4.2-Unsafe-OpenJDK9.jar,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer=org.marlin.pisces.PiscesRenderingEngine,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dgeoserver.xframe.shouldSetPolicy=true,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-modules=java.se,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.nio=ALL-UNNAMED,
03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.management/sun.management=ALL-UNNAMED,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat,
03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat,
03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp,
03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.5.2].,
03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].,
03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true],
03-Nov-2020 10:49:47.541 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0l  10 Sep 2019],
03-Nov-2020 10:49:47.841 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"],
03-Nov-2020 10:49:47.879 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"],
03-Nov-2020 10:49:47.882 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [597] milliseconds,
```

And when I replace `<version>` with `latest`  or `2.18.0` it does not work and starts looping:
```
Adding custom projection directory,
cp: cannot create directory '/opt/geoserver/data_dir/user_projections': Permission denied,
/scripts/start.sh: line 188: /opt/geoserver/data_dir/controlflow.properties: Permission denied,
cp: cannot create directory '/opt/geoserver/data_dir/security': Permission denied,
cp: cannot stat '/opt/geoserver/data_dir/security/usergroup/default/users.xml': No such file or directory,
/scripts/update_passwords.sh: line 36: /opt/geoserver/data_dir/security/usergroup/default/users.xml: No such file or directory,
cat: /opt/geoserver/data_dir/security/usergroup/default/users.xml.orig: No such file or directory,
cp: cannot stat '/opt/geoserver/data_dir/security/role/default/roles.xml': No such file or directory,
/scripts/update_passwords.sh: line 41: /opt/geoserver/data_dir/security/role/default/roles.xml: No such file or directory,
cat: /opt/geoserver/data_dir/security/role/default/roles.xml.orig: No such file or directory,
touch: cannot touch '/opt/geoserver/data_dir/.updatepassword.lock': Permission denied,
Adding custom projection directory,
cp: cannot create directory '/opt/geoserver/data_dir/user_projections': Permission denied,
/scripts/start.sh: line 188: /opt/geoserver/data_dir/controlflow.properties: Permission denied,
mv: cannot move '/tmp/tomcat/tomcat_apps/ROOT' to '/usr/local/tomcat/webapps/ROOT': Directory not empty,
mv: cannot move '/tmp/tomcat/tomcat_apps/docs' to '/usr/local/tomcat/webapps/docs': Directory not empty,
mv: cannot move '/tmp/tomcat/tomcat_apps/examples' to '/usr/local/tomcat/webapps/examples': Directory not empty,
mv: cannot move '/tmp/tomcat/tomcat_apps/host-manager' to '/usr/local/tomcat/webapps/host-manager': Directory not empty,
mv: cannot move '/tmp/tomcat/tomcat_apps/manager' to '/usr/local/tomcat/webapps/manager': Directory not empty,
cp: cannot create directory '/opt/geoserver/data_dir/security': Permission denied,
```

**Comment by NyakudyaA** [comment]
> I run this:
> 
> `docker run --name geoserver1 -d --restart always -e INITIAL_MEMORY=1536M -e MAXIMUM_MEMORY=3584M -v /srv/geoserver/geoserver1:/opt/geoserver/data_dir -p 8080:8080 kartoza/geoserver:<version>`
> 
> And when I replace `<version>` with `2.17.2` it works:
> 
> ```
> NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED,
> [0.005s][warning][gc,ergo] -XX:NewSize and -XX:MaxNewSize override -XX:NewRatio,
> 03-Nov-2020 10:49:47.511 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.20,
> 03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 3 2019 22:26:00 UTC,
> 03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.20.0,
> 03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux,
> 03-Nov-2020 10:49:47.519 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-26-generic,
> 03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64,
> 03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64,
> 03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.3+1-Debian-1bpo91,
> 03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation,
> 03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat,
> 03-Nov-2020 10:49:47.520 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat,
> 03-Nov-2020 10:49:47.530 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties,
> 03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager,
> 03-Nov-2020 10:49:47.531 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1536M,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx3584M,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PerfDataSamplingInterval=500,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.referencing.forceXY=true,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:SoftRefLRUPolicyMSPerMB=36000,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewRatio=2,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC,
> 03-Nov-2020 10:49:47.532 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxGCPauseMillis=200,
> 03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ParallelGCThreads=20,
> 03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ConcGCThreads=5,
> 03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:InitiatingHeapOccupancyPercent=70,
> 03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+CMSClassUnloadingEnabled,
> 03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF8,
> 03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Duser.timezone=GMT,
> 03-Nov-2020 10:49:47.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.request.encoding=UTF-8,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.response.encoding=UTF-8,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DGEOSERVER_DATA_DIR=/opt/geoserver/data_dir,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.shapefile.datetime=true,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ds3.properties.location=/opt/geoserver/data_dir/s3.properties,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer.useThreadLocal=false,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer.pixelsize=8192,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewSize=300m,
> 03-Nov-2020 10:49:47.534 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlog4j.configuration=/usr/local/tomcat/log4j.properties,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --patch-module=java.desktop=/usr/local/tomcat/marlin-0.9.4.2-Unsafe-OpenJDK9.jar,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer=org.marlin.pisces.PiscesRenderingEngine,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dgeoserver.xframe.shouldSetPolicy=true,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-modules=java.se,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.nio=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.535 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.management/sun.management=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat,
> 03-Nov-2020 10:49:47.536 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat,
> 03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp,
> 03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.5.2].,
> 03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].,
> 03-Nov-2020 10:49:47.537 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true],
> 03-Nov-2020 10:49:47.541 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0l  10 Sep 2019],
> 03-Nov-2020 10:49:47.841 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"],
> 03-Nov-2020 10:49:47.879 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"],
> 03-Nov-2020 10:49:47.882 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [597] milliseconds,
> ```
> 
> And when I replace `<version>` with `latest` or `2.18.0` it does not work and starts looping:
> 
> ```
> Adding custom projection directory,
> cp: cannot create directory '/opt/geoserver/data_dir/user_projections': Permission denied,
> /scripts/start.sh: line 188: /opt/geoserver/data_dir/controlflow.properties: Permission denied,
> cp: cannot create directory '/opt/geoserver/data_dir/security': Permission denied,
> cp: cannot stat '/opt/geoserver/data_dir/security/usergroup/default/users.xml': No such file or directory,
> /scripts/update_passwords.sh: line 36: /opt/geoserver/data_dir/security/usergroup/default/users.xml: No such file or directory,
> cat: /opt/geoserver/data_dir/security/usergroup/default/users.xml.orig: No such file or directory,
> cp: cannot stat '/opt/geoserver/data_dir/security/role/default/roles.xml': No such file or directory,
> /scripts/update_passwords.sh: line 41: /opt/geoserver/data_dir/security/role/default/roles.xml: No such file or directory,
> cat: /opt/geoserver/data_dir/security/role/default/roles.xml.orig: No such file or directory,
> touch: cannot touch '/opt/geoserver/data_dir/.updatepassword.lock': Permission denied,
> Adding custom projection directory,
> cp: cannot create directory '/opt/geoserver/data_dir/user_projections': Permission denied,
> /scripts/start.sh: line 188: /opt/geoserver/data_dir/controlflow.properties: Permission denied,
> mv: cannot move '/tmp/tomcat/tomcat_apps/ROOT' to '/usr/local/tomcat/webapps/ROOT': Directory not empty,
> mv: cannot move '/tmp/tomcat/tomcat_apps/docs' to '/usr/local/tomcat/webapps/docs': Directory not empty,
> mv: cannot move '/tmp/tomcat/tomcat_apps/examples' to '/usr/local/tomcat/webapps/examples': Directory not empty,
> mv: cannot move '/tmp/tomcat/tomcat_apps/host-manager' to '/usr/local/tomcat/webapps/host-manager': Directory not empty,
> mv: cannot move '/tmp/tomcat/tomcat_apps/manager' to '/usr/local/tomcat/webapps/manager': Directory not empty,
> cp: cannot create directory '/opt/geoserver/data_dir/security': Permission denied,
> ```

What are the permissions for the `/srv/geoserver/geoserver` folder. Ideally, this should not be owned by root because in 2.18.0 we are trying to migrate from using root access because of the security implications of running containers as root. Reference https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L127

**Comment by frankhommers** [comment]
The permissions on /srv/geoserver/geoserver1 are root. What should they be then?

**Comment by NyakudyaA** [comment]
> The permissions on /srv/geoserver/geoserver1 are root. What should they be then?

Just change ownership to a normal user for the whole data directory recursively. Also remember when you using an existing data directory you need https://github.com/kartoza/docker-geoserver#upgrading-image-to-use-a-specific-version
