### ISSUE TITLE
Build tests for the image  integrate with github workflows to publish images

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-geoserver#202]
# Problem

We need to have a test for this image so that when we monitor the quality of the builds and we do not have things breaking.

# Solution

The test should cover i.e 
* Different base builds
* Builds from user-specified URL
* Test CORS support
* Plugins install both the community and the stable plugins installed with env variables
* Standard plugins that are installed as part of the image i.e gdal, printing
* JMS clustering

ping @lucernae here. I am assigning this to you.

**Comment by krishnaglodha** [comment]
Is anyone working on it ? @NyakudyaA

**Comment by NyakudyaA** [comment]
No one as of now. You can take a look at it

**Comment by NyakudyaA** [comment]
Tests added and workflow also added, we need to keep updating workflows
