### ISSUE TITLE
GEOSERVER_DATA_DIR sync issue

### ISSUE THREAD

**Issue by mpschaeuble** [kartoza/docker-geoserver#203]
For development purposes, I mount a local data dir directory to the container using:
```
[...]
volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
[...]
```

Since version 2.18 I noticed that files in data_dir/gwc are not in sync anymore. I suppose the reason is the change in Dockerfile in the commit https://github.com/kartoza/docker-geoserver/commit/411816fc7d77033a0547f07f46f3adef68f4fabd
This lead to an additional mount point in the docker container that prevents proper syncing:
```
grpcfuse on /opt/geoserver/data_dir type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
/dev/vda1 on /opt/geoserver/data_dir/gwc type ext4 (rw,relatime)
```

As a workaround, I'm now using the following config: 
```
volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./geoserver_data/gwc:/opt/geoserver/data_dir_gwc
environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir_gwc
```

I could imagine that other developers have the same issue as the default location of the gwc directory is within the data_dir.

**Comment by NyakudyaA** [comment]
@mpschaeuble what if you create the geoserver data dir and the gwc before mounting them. The idea is to have files that are not being run as root so that if you need to make changes outside the container you do not have to sudo the config files.

**Comment by mpschaeuble** [comment]
@NyakudyaA I don't really get your point: The local data dir exists before starting the container.

**Comment by NyakudyaA** [comment]
Fixed in develop
