### ISSUE TITLE
INSPIRE plugin is not listed in either stable_plugins.txt or community_plugins.txt

### ISSUE THREAD

**Issue by NicolaiMogensen** [kartoza/docker-geoserver#205]
The INSPIRE plugins lives here:
https://sourceforge.net/projects/geoserver/files/GeoServer/2.18.0/extensions/geoserver-2.18.0-inspire-plugin.zip/download

But is not mentioned in the two files containing plugins. 

I would have expected to find it here: 
https://github.com/kartoza/docker-geoserver/blob/master/build_data/stable_plugins.txt

**Comment by NyakudyaA** [comment]
> The INSPIRE plugins lives here:
> https://sourceforge.net/projects/geoserver/files/GeoServer/2.18.0/extensions/geoserver-2.18.0-inspire-plugin.zip/download
> 
> But is not mentioned in the two files containing plugins.
> 
> I would have expected to find it here:
> https://github.com/kartoza/docker-geoserver/blob/master/build_data/stable_plugins.txt

There are some plugins that are automatically installed as we view them as core or very important i.e https://github.com/kartoza/docker-geoserver/blob/2.18.0/scripts/setup.sh#L58

**Comment by NicolaiMogensen** [comment]
Ah, how could I have missed that! Thank you!
