### ISSUE TITLE
missing "inspire-plugin"

### ISSUE THREAD

**Issue by stanom** [kartoza/docker-geoserver#207]
There is no inspire plug-in in a group of stable plug-ins.

**Comment by NyakudyaA** [comment]
> There is no inspire plug-in in a group of stable plug-ins.

It's installed by default https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L58

**Comment by stanom** [comment]
Thanks for prompt response.

You may just need to add information about the activated module into the section _"Activate plugins on runtime"_, on the [web docker hub page](https://hub.docker.com/r/kartoza/geoserver).

Thanks

**Comment by NyakudyaA** [comment]
> Thanks for prompt response.
> 
> You may just need to add information about the activated module into the section _"Activate plugins on runtime"_, on the [web docker hub page](https://hub.docker.com/r/kartoza/geoserver).
> 
> Thanks

You are free to add that section @stanom and I will merge it

**Comment by stanom** [comment]
Sorry, of course :-)
OK, I added into `README.md`
