### ISSUE TITLE
docker-compose file and Geoserver backup

### ISSUE THREAD

**Issue by davidedelerma** [kartoza/docker-geoserver#208]
In README regarding Geoserver config backup is written: 
```
We provide a sample docker-compose.yml file that illustrates how you can establish a GeoServer + PostGIS with nightly backups.
If you are not interested in the backups , comment out those services in the docker-compose.yml file.
```
But cannot find any mention to nigthly backups in docker-compose file

**Comment by NyakudyaA** [comment]
@davidedelerma Sorry it might have been removed. The section should now read 
```
If you need to backup your running PostgreSQL database please modify the docker-compose to add a backup section according to https://github.com/kartoza/docker-pg-backup/blob/master/docker-compose.yml#L23
```

**Comment by davidedelerma** [comment]
Is there anyway to have also the backup of the Geoserver configuration ?

**Comment by NyakudyaA** [comment]
> Is there anyway to have also the backup of the Geoserver configuration ?

Yes and no. There is a module https://docs.geoserver.org/stable/en/user/community/backuprestore/index.html that allows you to backup GeoServer once it's up and running but I think it only saves the configuration files.

For a full backup with the data, you might want to run some cron job to zip the whole geoserver data directory nightly on weekly depending on your usage

**Comment by davidedelerma** [comment]
Awesome, thank you very much for your answer
