### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by peter-antal** [kartoza/docker-geoserver#209]
I scanned the 2.18 version with AWS ECR vulnerability scan and it found 622 vulnerabilities, 3 of them critical. Most of the issues could be solved by upgrading to Debian 10. However, when I tried specifying it in the IMAGE_VERSION param, many things stopped working, even basics like `more`.

Is there a plan to fork this nice work for Debian 10+?

**Comment by NyakudyaA** [comment]
> I scanned the 2.18 version with AWS ECR vulnerability scan and it found 622 vulnerabilities, 3 of them critical. Most of the issues could be solved by upgrading to Debian 10. However, when I tried specifying it in the IMAGE_VERSION param, many things stopped working, even basics like `more`.
> 
> Is there a plan to fork this nice work for Debian 10+?

Thanks, @peter-antal I will check if this image has a build setting that is triggered if the base image changes. If not I will enable this and we can eliminate some of the security vulnerabilities.

Yes, there is a plan to upgrade to Debian 10+ but since this is pro bono work I always do this in my free time. Feel free to do a draft PR and I can give pointers on how to make the Debian 10+ work

**Comment by undefinedSolutions** [comment]
I can only confirm this. I had kartoza/geoserver:2.18.0 running on my server and was sent an abus message by my hoster.
The server was completely bare apart from the docker image. In use was a firewall, disabled root access and public key authentication.
So the image is the only attack vector.

**Comment by NyakudyaA** [comment]
@peter-antal What IMAGE_VERSION were you trying to build against. What is the latest version to test this against. I tried  using `9-jdk11-openjdk-slim` and it works

**Comment by NyakudyaA** [comment]
> I think I tried `10-jdk11-openjdk-slim-buster`.

There is something wrong with the upstream image itself. I could not even manage to get tomcat running without anything i.e 
`docker run -it -p 8080:8080 tomcat:10-jdk11-openjdk-slim-buster` and then navigating to the browser so the problem needs to be fixed upstream

**Comment by varna** [comment]
I got black listed in https://www.spamhaus.org/
I had a clean server with 3 containers: nginx, certbot and kartoza/geoserver

**Comment by NyakudyaA** [comment]
@peter-antal, @undefinedSolutions  I managed to build with the specified tomcat, can you try the 2.19.0
