### ISSUE TITLE
Which version is the latest stable 2.15.2 or 2.16.2 ?

### ISSUE THREAD

**Issue by Ledoux** [kartoza/docker-geoserver#210]
Hi, 

thanks a lot for your amazing work, there seem to have a little discordance here on the stable minor version, s it 15 or 16 ?

![Screenshot from 2021-01-26 11-33-43](https://user-images.githubusercontent.com/3239692/105834137-63f58780-5fca-11eb-92b9-d7db530e36e8.png)

tx

**Comment by NyakudyaA** [comment]
Hi @Ledoux That is just an example of how you could use it to build. We could improve the wording there to mention that if you need to build the latest version check again http://geoserver.org/download/ to see which one is the latest version

**Comment by Ledoux** [comment]
Thanks a lot, I also read too fast the README, my bad :).
