### ISSUE TITLE
How to create geospatial PDFs with GDAL from GeoServer?

### ISSUE THREAD

**Issue by opaulochaves** [kartoza/docker-geoserver#212]
With the available GDAL plugin is it possible to create a geospatial PDF? I'm trying to generate one that is going to be imported into the Avenza Maps app.

**Comment by NyakudyaA** [comment]
@opaulochaves these kind of questions are rather asked in stack exchange or the geoserver issue tracker https://gis.stackexchange.com/questions/130345/geoserver-layered-or-georeferenced-pdf
