### ISSUE TITLE
TOMCAT_EXTRAS environmen variable fails

### ISSUE THREAD

**Issue by rbrdevs** [kartoza/docker-geoserver#216]
# Problem

- Running version 2.17.2

When TOMCAT_EXTRAS environment variable is setted to "true" the script start.sh throws lines with errors. 
Some files/folders doesn't exist. 
Content of "tomcat_apps.zip" file is not as expected

```
geoserver_1  | Installing default data directory
geoserver_1  | cp: cannot stat '/usr/local/tomcat/data/*': No such file or directory
geoserver_1  | unzip:  cannot find or open tomcat_apps.zip, tomcat_apps.zip.zip or tomcat_apps.zip.ZIP.
```

**Comment by NyakudyaA** [comment]
@dbrdevsi have fixed that issue in develop. You can compare the script start.sh between the two branches to make a PR. Otherwise I will look at it over the weekend

**Comment by NyakudyaA** [comment]
> @dbrdevsi have fixed that issue in develop. You can compare the script start.sh and setup.sh between the two branches to make a PR. Otherwise I will look at it over the weekend

Do you still need this to be ported, Have you tried to run the latest 2.18.2 image which works with this change

**Comment by rbrdevs** [comment]
It would be nice this to be ported, but in fact I will try to update to 2.18.2 asap. Anyway, thanks for the good work
