### ISSUE TITLE
Geoserver behind an nginx reverse proxy

### ISSUE THREAD

**Issue by SamyOteroGlez** [kartoza/docker-geoserver#222]
Hi all,

I am facing an issue with the geoserver where I can access the majority of the links except for the ones that are generated with js.

Here is my setup:
I have the geoserver container running behind an nginx reverse proxy, with nginx I am proxying the traffic from the domain to the container (geo.example.com to 127.0.0.1:8998)
Here is the nginx configuration:
```
server {

        server_name geo.example.com;

        location / {
                proxy_pass http://127.0.0.1:8998;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_redirect off;
        }

```

Everything seems to work fine except for the links that are generated with js in geoserver, for example, adding a new store: click on stores in the sidebar, click on add new, and click on PostGIS, it will throw the following:
```
HTTP Status 400 – Bad Request
Type Status Report

Message Origin does not correspond to a request

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Apache Tomcat/9.0.7
```
and the following error in the browser terminal:
```
https://geo.example.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.store.NewDataPage?17-2.IFormSubmitListener-storeForm ---> 400
```

From geoserver documentation (https://docs.geoserver.org/latest/en/user/security/webadmin/csrf.html) I added the following to the web.xml file
```
<context-param>
  <param-name>GEOSERVER_CSRF_WHITELIST</param-name>
  <param-value>geo.example.com</param-value>
</context-param>
```
and finally, I also tried adding the following to the server.xml
```
<Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               URIEncoding="UTF-8"
               scheme="https"
               proxyName="geo.example.com"
               proxyPort="443" />
```
But nothing really changed.

Wrapping up, I am able to access, serve layers using https with the new domain thru the nginx reverse proxy, but the links that are generated with javascript with geoserver are throwing a 400 error.

Any help would be much appreciated.

Regards,
Sam

**Comment by NyakudyaA** [comment]
Hi @SamyOteroGlez what geoserver version are you running, can you try the 2.18.2 image and see if the problem occurs.

You can also directly setup the geoserver under SSL

**Comment by SamyOteroGlez** [comment]
Hi @NyakudyaA 

> Hi @SamyOteroGlez what geoserver version are you running, can you try the 2.18.2 image and see if the problem occurs.
> 
We are using Geoserver 2.16.1

> You can also directly setup the geoserver under SSL
> 
How can I do that, directly thru the geoserver UI, before the container starts? is there any example I could follow?

> Is your nginx running in docker as well
>
The nginx server is running outside docker.

Thanks

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA
> 
> > Hi @SamyOteroGlez what geoserver version are you running, can you try the 2.18.2 image and see if the problem occurs.
> 
> We are using Geoserver 2.16.1

> 
> > You can also directly setup the geoserver under SSL

https://github.com/kartoza/docker-geoserver#running-under-ssl
> 
> How can I do that, directly thru the geoserver UI, before the container starts? is there any example I could follow?
> 
> > Is your nginx running in docker as well
> 
> The nginx server is running outside docker.
> 
> Thanks

**Comment by SamyOteroGlez** [comment]
> > Hi @NyakudyaA
> > > Hi @SamyOteroGlez what geoserver version are you running, can you try the 2.18.2 image and see if the problem occurs.
> > 
> > 
> > We are using Geoserver 2.16.1
> 
> > > You can also directly setup the geoserver under SSL
> 
> https://github.com/kartoza/docker-geoserver#running-under-ssl
> 
> > How can I do that, directly thru the geoserver UI, before the container starts? is there any example I could follow?
> > > Is your nginx running in docker as well
> > 
> > 
> > The nginx server is running outside docker.
> > Thanks

Tried both options: let the container generate its own certs and importing my own certs via volume, same result.

```
HTTP Status 400 – Bad Request
Type Status Report

Message Origin does not correspond to a request

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Apache Tomcat/9.0.7
```

**Comment by NyakudyaA** [comment]
@SamyOteroGlez It looks like those changes are not in the image. I suggest two things 
* Cherry the changes from develop into 2.16.1 branch and then we create a new image
* Upgrade your cluster to use 2.18.2 - remembering to use the env `EXISTING_DATA_DIR=true` to skip the password initialization logic

**Comment by SamyOteroGlez** [comment]
> @SamyOteroGlez It looks like those changes are not in the image. I suggest two things
> 
> * Cherry the changes from develop into 2.16.1 branch and then we create a new image
> * Upgrade your cluster to use 2.18.2 - remembering to use the env `EXISTING_DATA_DIR=true` to skip the password initialization logic

I upgraded the server to 2.18.2 it worked fine using the SSL=true (I am letting the container handle the certs by its own), Then I added the following configuration on nginx:
```
server {

        server_name geo.example.com;

        location / {
                proxy_pass http://<server-ip>:8998;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_redirect off;
        }
}
```

and finally executed the letsencrypt to generate certs for the custom domain I am using, in this case: geo.example.com

Thanks for your help @NyakudyaA. I will proceed and close this issue.

Cheers,
Sam

**Comment by FedericOldani** [comment]
Hi there, just to mention I faced the very same problem but I wasn't able to solve following this thread.
The error was 400 bad request: Origin does not correspond to request
The solution in my case was to add the hostname as GEOSERVER_CSRF_WHITELIST env variable (https://docs.geoserver.org/stable/en/user/security/webadmin/csrf.html) :
`GEOSERVER_CSRF_WHITELIST=geoserver.example.com`
and now it works

**Comment by renatowow14** [comment]
> Olá, só para mencionar que enfrentei o mesmo problema, mas não consegui resolver seguindo este tópico. O erro foi 400 solicitação incorreta: a origem não corresponde à solicitação A solução no meu caso foi adicionar o nome do host como variável env GEOSERVER_CSRF_WHITELIST ( [https://docs.geoserver.org/stable/en/user/security/webadmin/csrf. html](https://docs.geoserver.org/stable/en/user/security/webadmin/csrf.html) ): `GEOSERVER_CSRF_WHITELIST=geoserver.example.com` e agora funciona

tell us in more detail how you solved it I'm with the same problem and putting this environment variable was not solved.

**Comment by erhhung** [comment]
If you're running the latest (2.20.0) version of this GeoServer container, you see in `/scripts/entrypoint.sh` that the options are set with `-DGEOSERVER_CSRF_WHITELIST=${CSRF_WHITELIST}`, so you should pass `CSRF_WHITELIST=my.domain.com` into the container instead.

**Comment by illflavored** [comment]
> 

Confirmed this solution worked for my situation. Running an nginx ingress controller in kubernetes with geoserver as a backend service in the cluster listening on port 8080. I set that environment variable in my deployment .yaml to resolve HTTP Status 400 – Bad Request errors in the web interface

**Comment by ZeroSums** [comment]
> If you're running the latest (2.20.0) version of this GeoServer container, you see in `/scripts/entrypoint.sh` that the options are set with `-DGEOSERVER_CSRF_WHITELIST=${CSRF_WHITELIST}`, so you should pass `CSRF_WHITELIST=my.domain.com` into the container instead.

This worked for me - thank you!!!!
