### ISSUE TITLE
Why republish same docker tag 2.18.2?  The new build seems broken by the way.

### ISSUE THREAD

**Issue by tlvu** [kartoza/docker-geoserver#232]
I was scratching my head as to why the exact same `docker-compose` recipe on the same version `2.18.2` do not work when deploying on a new machine.  It was working fine just a few days ago on another machine.

I was having this errors in `docker logs geoserver`:

```
26-Mar-2021 21:44:51.051 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/geoserver]
26-Mar-2021 21:45:09.982 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
26-Mar-2021 21:45:10.010 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
26-Mar-2021 21:45:10.012 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors
26-Mar-2021 21:45:10.041 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/geoserver] has finished in [18,990] ms
```

Took a lot of time before thinking about comparing the image hash between my machines.

Old machine that was working:
```
kartoza/geoserver                   2.18.2                          185e7557ded2        5 weeks ago         2.12GB
```

New machine broken:
```
kartoza/geoserver           2.18.2                          f030f6e76749        2 hours ago         2.13GB
```

So I double check on DockerHub and it also shows a freshly re-publish of `2.18.2`.

I think it's a bad practice to re-publish on a tag that is already publicly available.  If you want to re-publish again on the same version, add something to the tag to make it different, ex: `2.18.2-build2` and so on.

![Screenshot from 2021-03-26 18-04-19](https://user-images.githubusercontent.com/11966697/112697435-e3ce8f80-8e5d-11eb-815f-44176f5bb820.png)

**Comment by tlvu** [comment]
`kartoza/geoserver:2.19.0` also have the exact same error "`At least one JAR was scanned for TLDs yet contained no TLDs.`" as this re-published `2.18.2`.

**Comment by NyakudyaA** [comment]
@tlvu what do you mean the new build is broken, doesn't the geoserver startup? 
Are you failing to activate some plugins. From the log you posted it doesn't look like it's a big issue.

I have been using the 2.19.0 image for a couple of days and it has been working without any glitches.

As for the update, the reason why I updated the branch was to use a newer tomcat base image with security fixes. See the recent issues about security vulnerabilities and this was mainly causing by running older tomcat base images.

I will try to compare the startup using the old tomcat version and the newer one to see if there is something broken.

**Comment by tlvu** [comment]
> @tlvu what do you mean the new build is broken, doesn't the geoserver startup?
> Are you failing to activate some plugins. From the log you posted it doesn't look like it's a big issue.

@NyakudyaA 

Geoserver app did not start for me "`SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors`", as in my original issue description.

I also suspected the plugins so I did not activate any and same result.  So both re-published 2.18.2 and 2.19.0 have the same error for me, without plugins.

> As for the update, the reason why I updated the branch was to use a newer tomcat base image with security fixes. See the recent issues about security vulnerabilities and this was mainly causing by running older tomcat base images.

This is superb.  However you need to re-release using a different tag so people are aware of it and to ensure reproducibility of already published tag.

Imagine someone already pulled 2.18.2, they will have no idea that what they have is not good anymore and have to pull again.  Docker do not re-pull by default.

Or 2 persons having both 2.18.2, they will have no idea their version are in fact different !  This basically defeat the reproducibility of docker images.

If your existing tag keeps changing, then you have the exact same problems as the `latest` "moving" tag: https://vsupalov.com/docker-latest-tag/

I propose adding a "release" field to your docker tag, example how RPM packing does: https://www.thegeekdiary.com/understanding-rpm-versions-and-naming-schemes/ (DEB package have the very similar nomenclature also).  So your tag will be like `<geoserver_version>-<release_version>`, ex: `2.18.2-20210326` or `2.18.2-r1`.

Up to you to decide the format of your `release_version`.  The goal is to make it visible there is a new build on existing version and to ensure reproducibility of past build.

Again, thanks for keeping up with security vulnerabilities !

**Comment by tlvu** [comment]
> Geoserver app did not start for me "`SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors`", as in my original issue description.
> 
> I also suspected the plugins so I did not activate any and same result. So both re-published 2.18.2 and 2.19.0 have the same error for me, without plugins.

@NyakudyaA

I have disabled the plugins but maybe some other config that I touch broke it as well.  Will check again on my side as well.

So maybe the build is okay but it's still bad to re-release on an already publicly published tag.

**Comment by NyakudyaA** [comment]
@tlvu morning have fixed those builds. Can you confirm if all is working and close if so

**Comment by tlvu** [comment]
> @tlvu morning have fixed those builds. Can you confirm if all is working and close if so

Confirmed fixed for 2.19.0.  Will retest 2.18.2 as well.

I will close this issue and open a new issue for changing the format of the docker tag to incorporate the release version?

Curious what was the fix?  New docker base image or actual code change in this repo?

**Comment by tlvu** [comment]
New 2.18.2 working as well.

However in the logs I see
```
STABLE_EXTENSIONS is unset, so we do not install any stable extensions                                                                                
COMMUNITY_EXTENSIONS is unset, so we do not install any community extensions 
```

Is it expected now to have to also set those 2 env var, in addition to `STABLE_EXTENSIONS` and `COMMUNITY_EXTENSIONS` or there is a new mechanism to enable those extensions?

**Comment by tlvu** [comment]
> Curious what was the fix? New docker base image or actual code change in this repo?

Replying to myself:

Base image downgrade from Tomcat 10 back to original Tomcat 9.
* 2.18.0 branch change: https://github.com/kartoza/docker-geoserver/commit/d3745de1e9288bcdb0136bc3314a9e16580fe045
* 2.19.0 branch change: https://github.com/kartoza/docker-geoserver/commit/034d477e02da3df637f68ef2b824ff0c18bcf26a

Why those commits do not reference this issue that if fixes?

**Comment by tlvu** [comment]
> However in the logs I see
> 
> ```
> STABLE_EXTENSIONS is unset, so we do not install any stable extensions                                                                                
> COMMUNITY_EXTENSIONS is unset, so we do not install any community extensions 
> ```
> 
> Is it expected now to have to also set those 2 env var, in addition to `STABLE_EXTENSIONS` and `COMMUNITY_EXTENSIONS` or there is a new mechanism to enable those extensions?

Sorry, my fault, forgot to re-enable plugins.  I was disabling plugins while testing the previous build that had Tomcat 10 where geoserver did not start.

**Comment by tlvu** [comment]
> I will close this issue and open a new issue for changing the format of the docker tag to incorporate the release version?

New issue created https://github.com/kartoza/docker-geoserver/issues/233

As a work-around to ensure reproducibility on my side, I have cached your build on our DockerHub org.  See our PR https://github.com/bird-house/birdhouse-deploy/pull/136 and commit https://github.com/bird-house/birdhouse-deploy/pull/136/commits/babd648aafa3fb23b08e3de64691d040f2e99a1f
