### ISSUE TITLE
Please add configuration for InitiatingHeapOccupancyPercent

### ISSUE THREAD

**Issue by jcachat** [kartoza/docker-geoserver#244]
I have a system that was recently launched that is running the latest docker w/Geoserver 2.18.2.  I also have a couple systems that are running an older version (Geoserver 2.16.2 built a year or so ago).  All of the systems are running in Kubernetes on a dedicated host with 8GB of ram and Geoserver is configured with MAXIMUM_MEMORY of 4GB.  We have been experiencing out of memory errors on the new system after it has been running for 2-3 days while the older systems have been running fine for many months with no issues at all.

While under load, the memory usage would steadily increase and never be reclaimed - even when usage dropped at the end of the day.  Eventually, the JVM would get an OOM error which crashes the container and causes it to restart.  It is not a Kubernetes pod eviction.

The changes to the garbage collection to switch from UseParallelGC to UseG1GC seems to be the difference.  And the only way I could get things working properly was to change the setting for InitiatingHeapOccupancyPercent back to Java's default of 45%.  

I'm not very experienced with Java (so correct me if I have this wrong) but from what I have learned in the last couple days, it seems that G1GC requires multiple full GC's to actually reclaim any memory.  So I think what's happening is when it hits 70% (which is what you set it to), it marks the memory as not allocated in the JVM heap but doesn't actually free it.  So it continues to allocate more memory until it...can't...because another GC is not triggered in time due to the heap being reduced by the previous pass.

I'm sure you had a reason for changing it to 70%, but could you please add a configuration for it so we can tweak it for our environments along with the initial/max settings?

Here is a picture of the cpu & memory usage of the VM from this week.  Over the weekend, I had forced Geoserver to free memory (from the status page) so it starts out low on Mon.  The 1st big drop in memory usage (and spike in CPU) is where the container crashed and restarted.  The 2nd is where I updated it (last night) to set InitiatingHeapOccupancyPercent to 45.  You can see it has been allocating and releasing memory normally today (even while under load) where it never released any significant amount of memory prior to that change.

![image](https://user-images.githubusercontent.com/1613260/116597711-f2dcad80-a8f3-11eb-9d14-3fc71ebd75e3.png)

**Comment by NyakudyaA** [comment]
Thanks @jcachat I am not also very experienced with the java but when I configured those new settings was based on https://docs.oracle.com/cd/E40972_01/doc.70/e40973/cnf_jvmgc.htm#autoId2

https://www.oracle.com/technical-resources/articles/java/g1gc.html

However I can setup defaults which work and users can configure them as they wish. I will do a PR sometime when I am free
