### ISSUE TITLE
Expanding support of specifying passwords with _FILE?

### ISSUE THREAD

**Issue by anilnatha** [kartoza/docker-geoserver#247]
Regarding the appending of `_FILE` to certain settings to make use of docker secrets, the readme file states that:

>Currently, GEOSERVER_ADMIN_USER and GEOSERVER_ADMIN_PASSWORD are supported.

Will the other password settings in the `.env` file be able to be configured using docker secrets in the near future? I don't feel comfortable specifying these settings in `.env` since I would like to version control my `.env` file.

The passwords I'm referring to are:

- `JKS_KEY_PASSWORD`
- `JKS_STORE_PASSWORD`
- `PKCS12_PASSWORD`

**Comment by anilnatha** [comment]
To add to my original post, I noticed that in `scripts/start.sh` there is also a `TOMCAT_PASSWORD` password but I did not see that specified in the `.env` file so that would also be another one to set using docker secrets.

**Comment by NyakudyaA** [comment]
@anilnatha It should be as easy as referencing it in the `start.sh` script as done in https://github.com/kartoza/docker-geoserver/blob/master/scripts/update_passwords.sh#L21

If you really need this I suggest you make the specific modifications in a PR

**Comment by NyakudyaA** [comment]
This has been updated in the latest images. All passwords can now be passed as env variables
