### ISSUE TITLE
WMTS Multidimensional extension does not install with Geoserver 2.19

### ISSUE THREAD

**Issue by anilnatha** [kartoza/docker-geoserver#248]
Hello. First I wanted to say thank you for the excellent documentation, it's helped me learn a lot about how this docker configuration is set up and what options are available for us to configure.

Based on the list of available plugins provided by the [Community Plugins](https://github.com/kartoza/docker-geoserver/blob/master/build_data/community_plugins.txt) list, I added the following to my `.env` file and referenced it in my `docker-compose.yml`.

```
COMMUNITY_EXTENSIONS=wmts-multi-dimensional-plugin
```

Upon running `docker-compose up`, it reported that:

```shell
geoserver | Plugin URL does not exist: https://build.geoserver.org/geoserver/2.19.x/community-latest/geoserver-2.19-SNAPSHOT-wmts-multi-dimensional-plugin.zip
geoserver | Installing wmts-multi-dimensional-plugin plugin
geoserver | unzip:  cannot find or open /community_plugins/wmts-multi-dimensional-plugin.zip, /community_plugins/wmts-multi-dimensional-plugin.zip.zip or /community_plugins/wmts-multi-dimensional-plugin.zip.ZIP.
```
I did some research and it appears as though the WMTS Multi-Dimensional Plugin is no longer considered a community plugin. With 2.19, it's now listed as a [stable extension](https://docs.geoserver.org/stable/en/user/extensions/index.html) and available at these locations:

https://build.geoserver.org/geoserver/2.19.x/ext-latest/
https://liquidtelecom.dl.sourceforge.net/project/geoserver/GeoServer/2.19.0/extensions/geoserver-2.19.0-wmts-multi-dimensional-plugin.zip

I found where the extensions and plugins are being loaded in `start.sh`, but don't know what the best way would be to install item(s) that are version specific and so wanted to at least inform you of this issue.

**Comment by NyakudyaA** [comment]
@anilnatha that plugin is correctly listed as a stable_extension so you need to add the env variable for stable extension.

The logic in start.sh is quite clever enough to figure out that it you pass the correct extension name on runtime it will try to locate it from the plugins already downloaded otherwise it will download it from that url and place it in the proper place
