### ISSUE TITLE
Configuration when running behind nginx proxy?

### ISSUE THREAD

**Issue by gamesbook** [kartoza/docker-geoserver#249]
I am trying to run geoserver on a server (for example, `server.backend.co.za`) that is behind a firewall, and where a separate nginx proxy server (for example, running as `server.frontend.co.za`) handles incoming requests.

The nginx maps calls from `/prefix/geoserver` to the http://server.backend.co.za:8124/geoserver/

This works fine for the title page; however all the data links are still shown as:

http://server.backend.co.za:8124/geoserver/tiger/wms?service=WMS&version=1.1.0&request=GetMap&layers=tiger... 

I have tried adding the https proxy details in the `docker-compose.yml` file:
```
        - HTTPS_PROXY_NAME=server.frontend.co.za
        - HTTPS_PROXY_PORT=80
```
but this had no effect.

What should be changed or set in docker-compose to enable the correct server prefix for these links?

**Comment by NyakudyaA** [comment]
@gamesbook You need to set the `Proxy Base URL` in your GeoServer UI. Currently, we do not have a way to define this as an env variable

**Comment by gamesbook** [comment]
Thanks.  However, to set the `Proxy Base URL` requires one to login to GeoServer. The login process suffers from the same problem as indicated above - the URLs used by GeoServer are themselves are not correct.

**Comment by NyakudyaA** [comment]
Please share your nginx config because we are also running the same setup and it works seamlessly

**Comment by gamesbook** [comment]
If you can share the relevant parts of your config, I can try that.

**Comment by gamesbook** [comment]
Any chance to share a working setup for mapping from nginx to GeoServer?

**Comment by NyakudyaA** [comment]
Hi @gamesbook will do so, I guess I will have to add it to the repo and include it in the readme

**Comment by tlvu** [comment]
@gamesbook @NyakudyaA FYI, this is how we set the `Proxy Base URL` without logging in https://github.com/bird-house/birdhouse-deploy/blob/b60443eb6a38350cc55ad0edb9c296bc0fe7e7c1/birdhouse/config/geoserver/entrypointwrapper#L3-L14

**Comment by NyakudyaA** [comment]
Thanks @tlvu i will do a PR and add it to the image on the next iteration

**Comment by NyakudyaA** [comment]
@gamesbook Provided you running nginx in docker here is the config file

```
upstream geoserver {
    server geoserver:8080;
}


server {

    listen      80;
    # the domain name it will serve for
    server_name localhost;
    

    # max upload size, adjust to taste
    client_max_body_size 15M;

    location / {
        root /web/;
        index index.html index.htm;
       
    }
   
    
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location /geoserver {
        proxy_pass http://geoserver/geoserver;
    }
  
}
```

**Comment by NyakudyaA** [comment]
> @gamesbook @NyakudyaA FYI, this is how we set the `Proxy Base URL` without logging in https://github.com/bird-house/birdhouse-deploy/blob/b60443eb6a38350cc55ad0edb9c296bc0fe7e7c1/birdhouse/config/geoserver/entrypointwrapper#L3-L14
> 
> 
> 
> 

@tlvu i tried your logic and it didn't work. I only realized that the logic for setting this in place was already there but was for ssl based. I fixed it in the latest dev branch and should work out of the box for ssl and none ssl

**Comment by NyakudyaA** [comment]
@gamesbook can you try the latest image with the https proxy env variables. I tested it and it worked
