### ISSUE TITLE
error while building image "returned a non-zero code: 100"

### ISSUE THREAD

**Issue by abhijitgujar86** [kartoza/docker-geoserver#257]
Service 'geoserver' failed to build: The command '/bin/sh -c apt-get -y update; apt-get -y --no-install-recommends install fonts-cantarell lmodern ttf-aenigma     ttf-georgewilliams ttf-bitstream-vera ttf-sjfonts tv-fonts  libapr1-dev libssl-dev      gdal-bin libgdal-java wget zip unzip curl xsltproc certbot  cabextract gettext postgresql-client figlet toilet' returned a non-zero code: 100

**Comment by NyakudyaA** [comment]
@abhijitgujar86 what branch are you building against

**Comment by NyakudyaA** [comment]
This might have been an internet connectivity affecting this
