### ISSUE TITLE
How can I use the JNDI PostGIS datastore?

### ISSUE THREAD

**Issue by lstillwe** [kartoza/docker-geoserver#261]
As I understand it, I have to put a Resource block in Tomcat's context.xml file describing the DB connection in order to use the JNDI PostGIS datastore. How is this done with this docker image?

Thanks!

**Comment by NyakudyaA** [comment]
If you are using the latest image you should be able to use https://github.com/kartoza/docker-geoserver#mounting-configs and mount the web.xml but if you are running previous tagged version you should be able to mount the web.xml to the actual location when starting the image

**Comment by lstillwe** [comment]
Thank you. I saw that I could mount some config files, but I thought I had to put the DB details in **context.xml** (i.e. userid, password) not web.xml?

**Comment by lstillwe** [comment]
@NyakudyaA Do you recommend putting the config info for the JNDI connection in web.xml or context.xml? I tried using context.xml, and mounting that in /settings - but that did not seem to work. I am using you latest docker image. Also I saw here (https://docs.geoserver.org/master/en/user/tutorials/tomcat-jndi/tomcat-jndi.html) that I should move the postgresql-42.2.18.jar file to $CATALINA_HOME/lib. Is that correct? Thanks - Lisa

**Comment by NyakudyaA** [comment]
@lstillwe It's currently working in the develop branch, All you need to do is add the following env variables

```
POSTGRES_JNDI=TRUE
HOST=${HOST}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASS=${POSTGRES_PASS}
```
assuming those variables are defined in the .env 
You will need to build the dev branch as I haven't added it to the master branch

**Comment by lstillwe** [comment]
@NyakudyaA When do you think you will add this to Master? I would rather wait until that is available. Thanks again - Lisa

**Comment by NyakudyaA** [comment]
I will try to do it later tonight

**Comment by lstillwe** [comment]
@NyakudyaA Thank you!

**Comment by NyakudyaA** [comment]
> @NyakudyaA Thank you!

I have merged to master, you should try pulling the image
