### ISSUE TITLE
Why use insecure requests for builds?

### ISSUE THREAD

**Issue by adjenks** [kartoza/docker-geoserver#263]
Why do a lot of the URLs use `http:`  instead of `https:` and why do you use `--no-check-certificate` on wget requests?

I would prefer using TLS wherever possible instead.

**Comment by NyakudyaA** [comment]
@adjenks the main reason is that we do not want our builds to fail where url are not properly setup or have certificates that haven’t been renewed. If we can be certain that all URL we use for building or downloading have TLS we can switch to them.


What are the implications of using http in downloading binaries etc?

**Comment by adjenks** [comment]
If someone detects that you are using http in builds, they could intercept the request and provide a malicious binary to you instead.

In a similar sense, I would not run an exe file on my desktop computer that was downloaded over http from a website, since I can't guarantee that nobody performed a man-in-the-middle attack when I made the request for the file.

The purpose of TLS is not only to encrypt and hide the contents of the messages you are exchanging, but to verify the identity of the sender (and the client if client certificates are used), and verify the integrity of the message. This way you know that you received the file that you asked for from the source you intended on getting it from.

If a certificate hasn't been renewed then the build should fail. The owner of the website should be informed that they need to renew their certificate. Just because you may not access a site securely one day, does not mean that you should forgo safety in builds every day.

**Comment by NyakudyaA** [comment]
Thanks for the info @adjenks , The geoserver site where we fetch the binary and some plugins hasn’t been under ssl for a while. We could write to them to suggesting that they make it more secure but that’s up to them really. 

The second option would be to build the binary and extensions ourselves but that would considerably slow down the build considerably.

for now the best way is to use https where possible and fall back to http where it’s the only option

**Comment by adjenks** [comment]
All of the sources I've tried so far have had HTTPS available, I didn't try the community plugins yet though.

Defaulting to secure downloads would be good. Perhaps instead of falling back to HTTP all the time there should be a flag like `ALLOW_INSECURE_FALLBACK` or the opposite like `HTTPS_SOURCES_ONLY`.
I would prefer a secure default which I could choose to switch to insecure.

**Comment by NyakudyaA** [comment]
> All of the sources I've tried so far have had HTTPS available, I didn't try the community plugins yet though.
> 
> Defaulting to secure downloads would be good. Perhaps instead of falling back to HTTP all the time there should be a flag like `ALLOW_INSECURE_FALLBACK` or the opposite like `HTTPS_SOURCES_ONLY`.
> I would prefer a secure default which I could choose to switch to insecure.

How about a fail safe method  like
```
function url_checker {
URL=$1
if wget --spider https://$URL 2>/dev/null; then
 BASE_URL=https://$URL
 echo $BASE_URL
else
  BASE_URL=http://$URL
  echo $BASE_URL
fi
}
```
then we could call the request like 
```
request="wget --progress=bar:force:noscroll -c "
WAR_URL=downloads.sourceforge.net/project/geoserver/GeoServer/${GS_VERSION}/geoserver-${GS_VERSION}-war.zip
${request} $(url_checker $WAR_URL) -O ${destination}
```

This way the builds will always be sucessful

**Comment by NyakudyaA** [comment]
@adjenks  see https://github.com/kartoza/docker-geoserver/pull/264 and revert

**Comment by adjenks** [comment]
Yes I think this would be an improvement.
Though this pull request includes many other changes and this build is fairly complex, so I can't comment on the pull request itself because it touches lots of code that I'm not familiar with.

Personally I would want the function to behave like this:
```bash

#A global default that can be modified for individuals who want the build to fail when https is not available:
ONLY_HTTPS =0

function url_protocol_selector {
  URL=$1
  if [[ $(wget --spider https://$URL 2>/dev/null) ]] || [[ 1 -eq $ONLY_HTTPS ]] ; then
   BASE_URL=https://$URL
   echo $BASE_URL
  else
    BASE_URL=http://$URL
    echo $BASE_URL
  fi
}
```

**Comment by NyakudyaA** [comment]
In the current master branch, all requests are now being built with HTTPS.  If a user supplies build args that are not secure it's up to him for that. I do not think we need a flag to stop a build if it uses HTTP since the default is to build with secure URL

**Comment by adjenks** [comment]
Awesome.
