### ISSUE TITLE
Error while building image 

### ISSUE THREAD

**Issue by abhijitgujar86** [kartoza/docker-geoserver#266]
dpkg: error processing package python3-minimal (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python3.5-minimal
 python3-minimal

**Comment by NyakudyaA** [comment]
> dpkg: error processing package python3-minimal (--configure):
> dependency problems - leaving unconfigured
> Errors were encountered while processing:
> python3.5-minimal
> python3-minimal

what branch ?
