### ISSUE TITLE
Setup SSL on Tomcat/GeoServer - Keycloak

### ISSUE THREAD

**Issue by senthils25** [kartoza/docker-geoserver#267]
Hi I am new to docker. 
Sorry, This might be a very basic question
I wanted to authenticate my GeoServer using Keycloak server.
Where do I provide these details?

**Comment by NyakudyaA** [comment]
> Hi I am new to docker.
> Sorry, This might be a very basic question
> I wanted to authenticate my GeoServer using Keycloak server.
> Where do I provide these details?

https://docs.geoserver.org/master/en/user/community/keycloak/index.html
