### ISSUE TITLE
Cannot commit the docker image with changes to GeoServer

### ISSUE THREAD

**Issue by senthils25** [kartoza/docker-geoserver#268]
I created workspace, stores and layers in Geoserver running on docker.
To save these changes, I used docker commit, but when I run the saved image, I don't find the workspace and stores on new container.
How to save the changes made to GeoServer(including data directory and users) as new image?

**Comment by NyakudyaA** [comment]
@senthils25 this breaks the docker principle for images. What is wrong with the mounting the data directory.

I am sure this could because the data directory is mounted so you could try to actually copy the data directory rather than mounting it

**Comment by senthils25** [comment]
Yes I do agree. But with changes I make to geoserver data directory, I wanna create a new image with ready to use configuration

**Comment by senthils25** [comment]
But my question is why data directory is not saved during docker commit command? Usually any changes made to container are saved but not this geoserver data directory.

**Comment by NyakudyaA** [comment]
https://stackoverflow.com/questions/46349071/commit-content-of-mounted-volumes-as-well

**Comment by senthils25** [comment]
> https://stackoverflow.com/questions/46349071/commit-content-of-mounted-volumes-as-well

Thank you. will try it out. So by default the Geoserver data directory even if not specified in environment variables is considered as mounted drive?
