### ISSUE TITLE
CORS issue in GeoServer

### ISSUE THREAD

**Issue by senthils25** [kartoza/docker-geoserver#269]
Hi I am running the Geoserver docker with Data directory mounted.

I am getting CORS error when I give WFS Post request to the server. 

I enabled the CORS in Tomcat (tomcat/conf/web.xml) and also in Geoserver (tomcat/webapps/geoserver/web.xml) file.
After enabling the CORS, I get CORS error this time saying that multiple Cross-Origin values present and expecting single value.

**Comment by NyakudyaA** [comment]
@senthils25 Can you please check gisstackexchange for these kinds of issues. but just to answer you CORS can either be enabled through tomcat (https://github.com/kartoza/docker-geoserver/blob/develop/scripts/start.sh#L13) or directly in web apps folder. 
The container already enables it in tomcat

**Comment by senthils25** [comment]
@NyakudyaA  Thank you!
