### ISSUE TITLE
Geoserver Data Directory Mounting - No rights

### ISSUE THREAD

**Issue by senthils25** [kartoza/docker-geoserver#271]
Hi 

I am mounting the directory to geoserver image and passing the enivronment variable EXISTING_DATA_DIR = true and also passing GEOSERVER_DATA_DIR to the mounted volume.

Geoserver ignores this mounted data directory and when I try to bash, I get no permission error for directory inside mounted volume.

What permissions need to be set for mounted volumes and which user?

Thanks in advance

**Comment by NyakudyaA** [comment]
You need the directory to be owned by a normal user ie chown -R foo:foo /data
