### ISSUE TITLE
Unusual outgoing traffic from docker

### ISSUE THREAD

**Issue by senthils25** [kartoza/docker-geoserver#272]
Hi,

After using the geoserver docker, there is unsual huge volume of data in outgoing traffic on UDP port 80 (around 15GB/hour ).

After stopping docker the outgoing traffic is reduced drastically and its normal.

**Comment by NyakudyaA** [comment]
@senthils25 How does your setup look like ?

**Comment by senthils25** [comment]
I pulled the latest image and used the following to start the container

docker run -d -p 8080:8080 --name GEOSERVER -v /var/lib/tomcat9/webapps/geoserver/data:/tmp/geoserver_datadir -e EXISTING_DATA_DIR=true -e GEOSERVER_DATA_DIR=/tmp/geoserver_datadir kartoza/geoserver

**Comment by NyakudyaA** [comment]
I cannot replicate this @senthils25 , Is this still occurring ?

**Comment by senthils25** [comment]
@NyakudyaA  Yes, when I scanned I found some Virus in docker overlay images and that might be causing this issue?

[/var/lib/docker/overlay2/a6236e8c2ff3b5480420bfc929f0fc5e5568fc756a2c2b375561586399a3b6be/diff/tmp/Josho.x86.1: Unix.Dropper.Mirai-7135890-0 FOUND
/var/lib/docker/overlay2/a6236e8c2ff3b5480420bfc929f0fc5e5568fc756a2c2b375561586399a3b6be/diff/tmp/Josho.ppc.1: Unix.Dropper.Mirai-7135890-0 FOUND
/var/lib/docker/overlay2/a6236e8c2ff3b5480420bfc929f0fc5e5568fc756a2c2b375561586399a3b6be/diff/tmp/Josho.sh4.1: Unix.Dropper.Mirai-7135890-0 FOUND
/var/lib/docker/overlay2/a6236e8c2ff3b5480420bfc929f0fc5e5568fc756a2c2b375561586399a3b6be/diff/tmp/Josho.x86: Unix.Dropper.Mirai-7135890-0 FOUND
/var/lib/docker/overlay2/a6236e8c2ff3b5480420bfc929f0fc5e5568fc756a2c2b375561586399a3b6be/diff/tmp/Josho.sh4: Unix.Dropper.Mirai-7135890-0 FOUND
/var/lib/docker/overlay2/a6236e8c2ff3b5480420bfc929f0fc5e5568fc756a2c2b375561586399a3b6be/diff/tmp/Josho.arm6.1: Unix.Dropper.Mirai-7135890-0 FOUND](url)

**Comment by NyakudyaA** [comment]
@senthils25 maybe you could try to build the image with the latest version of tomcat. It's been a while since I tried but it will have less bugs . I will also try when I have time
