### ISSUE TITLE
Assign subdomain

### ISSUE THREAD

**Issue by MaxDragonheart** [kartoza/docker-geoserver#275]
Hi and thank you for working on this image. I'm new into the Docker world, I already have a server with GeoServer, but without Docker; this server is full now and I need to create a new instance passing to Docker.

It was very simple to create a new instance [eratosthenes.massimilianomoraca.com:8600/geoserver](http://eratosthenes.massimilianomoraca.com:8600/geoserver) (*link1*) but now I would to remove the port number and use http://eratosthenes.massimilianomoraca.com/geoserver/ (*link2*)

I've no clear how I can do this even reading the issue #249 but I need to use Nginx and Letsencrypt, so with `docker kill CONTAINER_ID` I've removed the container. After that I've modified the `.env` putting this:

```
# SSL Settings explained here https://github.com/AtomGraph/letsencrypt-tomcat
SSL=true
HTTP_PORT=8080
HTTP_PROXY_NAME=eratosthenes.massimilianomoraca.com
HTTP_PROXY_PORT=80
HTTP_REDIRECT_PORT=
HTTP_CONNECTION_TIMEOUT=20000
HTTPS_PORT=8443
HTTPS_MAX_THREADS=150
HTTPS_CLIENT_AUTH=
HTTPS_PROXY_NAME=
HTTPS_PROXY_PORT=
JKS_FILE=letsencrypt.jks
JKS_KEY_PASSWORD='geoserver'
KEY_ALIAS=letsencrypt
JKS_STORE_PASSWORD='geoserver'
P12_FILE=letsencrypt.p12
PKCS12_PASSWORD='geoserver'
LETSENCRYPT_CERT_DIR=/etc/letsencrypt
CHARACTER_ENCODING='UTF-8'
```
rebuilding the container with `docker-compose -f docker-compose-build.yml up -d --build`.
I've installed Nginx on the server(I'm using a Droplet of [DigitalOcean](https://m.do.co/c/d49c095797d9)), I've deleted the default variables and created a new conf file named `tomcat.conf`(it comes from my previous instance that has another domain's name):
```
server {
  server_name  eratosthenes.massimilianomoraca.com www.eratosthenes.massimilianomoraca.com;
  access_log /var/log/nginx/tomcat-access.log;
  error_log /var/log/nginx/tomcat-error.log;

    location / {
        proxy_pass http://127.0.0.1:8080/geoserver/;
        proxy_pass_header Set-Cookie;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /geoserver/ {
        proxy_pass http://127.0.0.1:8080/geoserver/;
        proxy_pass_header Set-Cookie;
        proxy_set_header Host $host;
         proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}
```
But I see `This site can’t be reached` when I use *link2*, *link1* working fine. So, my changes aren't usefull.

**Comment by NyakudyaA** [comment]
There are a couple of solutions here.

1- run geoserver on a default port 80 and then you will not need a port number in the url.
2- the ssl settings only affect the geoserver global settings I.e all layer urls will use that domain you have specified
3- Your nginx config have mixed declarations where you are making it available from / and then /geoserver. 
4- how is your nginx installed through docker or on host machine

**Comment by NyakudyaA** [comment]
@MaxDragonheart check https://github.com/kartoza/docker-geoserver/blob/master/README.md#reverse-proxy-using-nginx

**Comment by MaxDragonheart** [comment]
@NyakudyaA thank you, I try It after the holidays

**Comment by NyakudyaA** [comment]
@MaxDragonheart I assume this is fixed, I am closing this but feel free to reopen if it still is an issue
