### ISSUE TITLE
Environment variable GEOSERVER_ADMIN_USER_FILE not usable

### ISSUE THREAD

**Issue by julescarpentier** [kartoza/docker-geoserver#276]
When setting GEOSERVER_ADMIN_USER_FILE environment variable (in a compose file for instance) the container fails to start.

Because the GEOSERVER_ADMIN_USER is set to default `admin` in `/scripts/env-data.sh` (ln:226) prior to the check made by `file_env` in `/scripts/update_passwords.sh` (ln:32), the start script exits with error "both var GEOSERVER_ADMIN_USER and GEOSERVER_ADMIN_USER_FILE are set (but are exclusive)".

I would fix this by removing lines 225-227 in `/scripts/env-data.sh` and setting a default GEOSERVER_ADMIN_USER like a random GEOSERVER_ADMIN_PASSWORD is set in `/scripts/update_passwords.sh` if none were provided.

However I'm no expert and I couldn't find how the default password is set to `geoserver` so I'm not sure about this potential fix

**Comment by NyakudyaA** [comment]
@julescarpentier good catch,
I think there are two solutions to this

1- in env-data.sh source the functions.sh and then add all declarations that use 
file_env at the top of the file.
2- proceed by deleting the env variable from env-data.sh and add it to update_password 

I feel option 1 will be more favorable as it will allow us to add all file_env declarations at the top and this will affect a lot of variables that can be controlled by secrets 

You can give it a short but will look at it when I have free time

**Comment by julescarpentier** [comment]
@NyakudyaA you're right that affects every _FILE variable with non-empty default in env-data.sh.

The changes I made in the pull request follow option 1
