### ISSUE TITLE
permission denied_DATADIR

### ISSUE THREAD

**Issue by npltr62** [kartoza/docker-geoserver#281]
I'm running docker_geoserver (v2.19) with docker_postgis in backend.
1 : the script can't mounted data_directory  "cp: cannot create directory '/opt/geoserver/data_dir/user_projections': Permission denied". 
2 :also when i run geoserver webinterface there are data and layers whereas environnement variable SAMPLE_DATA is false.

**Comment by NyakudyaA** [comment]
> I'm running docker_geoserver (v2.19) with docker_postgis in backend.
> 1 : the script can't mounted data_directory "cp: cannot create directory '/opt/geoserver/data_dir/user_projections': Permission denied".
> 2 :also when i run geoserver webinterface there are data and layers whereas environnement variable SAMPLE_DATA is false.

What command did you use to start the container

**Comment by npltr62** [comment]
here is cmd `sudo docker run -p 8600:8080 --name geoserver --network docker_default -v /volume1/docker/geoserver:/etc/geoserver/data_dir kartoza/geoserver:2.19.0 `

**Comment by NyakudyaA** [comment]
> here is cmd `sudo docker run -p 8600:8080 --name geoserver --network docker_default -v /volume1/docker/geoserver:/etc/geoserver/data_dir kartoza/geoserver:2.19.0 `
> 
> I create the geoserver directory witch i 'm the owner. 

You are mounting the data dir into a none default location but are not specifying the Datadir env variable

**Comment by npltr62** [comment]
Do you mean something like that?
`sudo docker run -p 8600:8080 --name geoserver --network docker_default -v /volume1/docker/geoserver:/etc/geoserver/data_dir -e GEOSERVER_DATA_DIR= /volume1/docker/geoserver -e EXISTING_DATA_DIR=true kartoza/geoserver:2.19.0` 
I have the same message "Permission denied"

**Comment by lucernae** [comment]
You had to run it like this:

```
sudo docker run -p 8600:8080 --name geoserver --network docker_default -v /volume1/docker/geoserver:/etc/geoserver/data_dir -e GEOSERVER_DATA_DIR=/etc/geoserver/data_dir -e EXISTING_DATA_DIR=true kartoza/geoserver:2.19.0
```

Notice the difference in the `-e GEOSERVER_DATA_DIR=/etc/geoserver/data_dir`, it has to point out the location inside the container.

For the `-e EXISTING_DATA_DIR=true` flag, you only need to use it if the volumes already contains existing geoserver data directory (for example if you copy it from elsewhere).
