### ISSUE TITLE
Remove `VOLUME` definition in Dockerfile

### ISSUE THREAD

**Issue by Nkmol** [kartoza/docker-geoserver#282]
Since the PR of https://github.com/kartoza/docker-geoserver/pull/193/commits `VOLUME` have been defined in the Dockerfile. I would advocate removing this definition for the following reason:

Using the `VOLUME` definition, in my opinion, only makes sense when you are using Geoserver as a service through the UI. Where you want the run-time changes to be persistent using docker volumes. In cases where you would use Geoserver UI-less and want a stateless image that uses the `COPY` definition to embed the configs, it does _not_ make sense to use volumes. This last scenario would currently not work as the volumes would simply overwrite any embedded state.

I instead suggest to solely rely on the docker-compose `volume:` definitions to define persistent volumes for the docker run. This way the user of this Geoserver image can decide if they want this volume behaviour or not.

Please let me know what you think about this and if I missed something.

----

Some more discussion about this in the following issue: https://github.com/moby/moby/issues/3465

**Comment by NyakudyaA** [comment]
@lucernae What are you views here

**Comment by NyakudyaA** [comment]
@Nkmol cc @jmsierra Can either of you make a PR against develop with these changes
