### ISSUE TITLE
Manifest unknown using docker-compose-nginx.yml 

### ISSUE THREAD

**Issue by MaxDragonheart** [kartoza/docker-geoserver#286]
Returned from holidays I've found this [big gift](https://github.com/kartoza/docker-geoserver/blob/master/docker-compose-nginx.yml) for me after the opening of #275 
Unfortunately when I use `docker-compose -f docker-compose-nginx.yml up -d --build`, I see this:
```
Creating network "kartozageoserver_default" with the default driver
Creating volume "kartozageoserver_geoserver-data" with default driver
Creating volume "kartozageoserver_geo-db-data" with default driver
Pulling db (kartoza/postgis:13-3.1)...
13-3.1: Pulling from kartoza/postgis
31d64ed241e5: Pull complete
f82d9e1a849d: Pull complete
0ea3394ec364: Pull complete
a4b6ecd0ac04: Pull complete
e62a1ac46b12: Pull complete
e667bde8c3bd: Pull complete
234a2944f784: Pull complete
21f911aa52ef: Pull complete
bc6ce3e0b92b: Pull complete
0e24721e5ca0: Pull complete
64ef5322dba6: Pull complete
d04449c3c98b: Pull complete
27cc65f24c29: Pull complete
60067a4634ce: Pull complete
12f9000be962: Pull complete
8eba30636732: Pull complete
a22cbb5692fd: Pull complete
c7e4272cacbb: Pull complete
b8d38bbfb6ba: Pull complete
12e79cb34ba0: Pull complete
Digest: sha256:49a7998950b50f7a0ebf0858443c579bef80c405a761b3f6316fcfef331180ed
Status: Downloaded newer image for kartoza/postgis:13-3.1
Pulling geoserver (kartoza/geoserver:2.19.2)...
ERROR: manifest for kartoza/geoserver:2.19.2 not found: manifest unknown: manifest unknown
```
For me this was a first test and then I haven't change nothing inside `.env`.

**Comment by NyakudyaA** [comment]
> Returned from holidays I've found this [big gift](https://github.com/kartoza/docker-geoserver/blob/master/docker-compose-nginx.yml) for me after the opening of #275
> Unfortunately when I use `docker-compose -f docker-compose-nginx.yml up -d --build`, I see this:
> 
> ```
> Creating network "kartozageoserver_default" with the default driver
> Creating volume "kartozageoserver_geoserver-data" with default driver
> Creating volume "kartozageoserver_geo-db-data" with default driver
> Pulling db (kartoza/postgis:13-3.1)...
> 13-3.1: Pulling from kartoza/postgis
> 31d64ed241e5: Pull complete
> f82d9e1a849d: Pull complete
> 0ea3394ec364: Pull complete
> a4b6ecd0ac04: Pull complete
> e62a1ac46b12: Pull complete
> e667bde8c3bd: Pull complete
> 234a2944f784: Pull complete
> 21f911aa52ef: Pull complete
> bc6ce3e0b92b: Pull complete
> 0e24721e5ca0: Pull complete
> 64ef5322dba6: Pull complete
> d04449c3c98b: Pull complete
> 27cc65f24c29: Pull complete
> 60067a4634ce: Pull complete
> 12f9000be962: Pull complete
> 8eba30636732: Pull complete
> a22cbb5692fd: Pull complete
> c7e4272cacbb: Pull complete
> b8d38bbfb6ba: Pull complete
> 12e79cb34ba0: Pull complete
> Digest: sha256:49a7998950b50f7a0ebf0858443c579bef80c405a761b3f6316fcfef331180ed
> Status: Downloaded newer image for kartoza/postgis:13-3.1
> Pulling geoserver (kartoza/geoserver:2.19.2)...
> ERROR: manifest for kartoza/geoserver:2.19.2 not found: manifest unknown: manifest unknown
> ```
> 
> For me this was a first test and then I haven't change nothing inside `.env`.

I haven't pushed 2.19.2 to dockerhub yet. I will do this tonight but just change to use latest for now as it will fetch 2.19.2

**Comment by MaxDragonheart** [comment]
Same thing with version 2.19.1
```
~/docker-geoserver# nano .env
~/docker-geoserver# docker-compose -f docker-compose-nginx.yml up -d --build
Pulling geoserver (kartoza/geoserver:2.19.1)...
ERROR: manifest for kartoza/geoserver:2.19.1 not found: manifest unknown: manifest unknown

```

**Comment by MaxDragonheart** [comment]
Is it normal that [here](https://github.com/kartoza/docker-geoserver/blob/master/docker-compose-build.yml#L1) the version is `3`  and [here](https://github.com/kartoza/docker-geoserver/blob/master/docker-compose-nginx.yml#L1) is `2.1`?
I'm newbie with Docker, I don't know if this is an hint.

**Comment by MaxDragonheart** [comment]
> I haven't pushed 2.19.2 to dockerhub yet. I will do this tonight but just change to use latest for now as it will fetch 2.19.2

Sorry @NyakudyaA I was writing when you was answering to me and this page isn't updated.

**Comment by NyakudyaA** [comment]
> Is it normal that [here](https://github.com/kartoza/docker-geoserver/blob/master/docker-compose-build.yml#L1) the version is `3` and [here](https://github.com/kartoza/docker-geoserver/blob/master/docker-compose-nginx.yml#L1) is `2.1`?
> I'm newbie with Docker, I don't know if this is an hint.

It's just a difference with docker-compose https://docs.docker.com/compose/compose-file/compose-versioning/
