### ISSUE TITLE
Permission deny using community plugin on the version 2.19.2

### ISSUE THREAD

**Issue by curtis18** [kartoza/docker-geoserver#289]
The new version of image 2.19.2 happens permission deny using community plugin e.g. activeMQ-broker-plugin and jms-cluster-plugin and it is not successful to create clustering, 2.19.0 is running normal. Thank you.

**Comment by NyakudyaA** [comment]
Pull again

**Comment by PingYufeng** [comment]
> The new version of image 2.19.2 happens permission deny using community plugin e.g. activeMQ-broker-plugin and jms-cluster-plugin and it is not successful to create clustering, 2.19.0 is running normal. Thank you.

@curtis18  How you can use the  activeMQ-broker-plugin to cluster? Could you share the steps of the sulution ?
