### ISSUE TITLE
Why GWC url is not default? 

### ISSUE THREAD

**Issue by BerkayOzen** [kartoza/docker-geoserver#292]
I have a big data set. For this I have to seed the tiles but when I tried to access GeoWebCache from GWCSettingsPage, I got 404 error.

![image](https://user-images.githubusercontent.com/54314280/131592387-a7f84cb2-8575-4bc0-b1cb-ba3b37c7f3b0.png)

Luckily when I opened "localhost/geoserver" page I noticed gwc was there. But its default url must be "localhost/geoserver/gwc/home". My question is why it is not in default and how can I change to default?

**Comment by NyakudyaA** [comment]
> I have a big data set. For this I have to seed the tiles but when I tried to access GeoWebCache from GWCSettingsPage, I got 404 error.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/54314280/131592387-a7f84cb2-8575-4bc0-b1cb-ba3b37c7f3b0.png)
> 
> 
> 
> Luckily when I opened "localhost/geoserver" page I noticed gwc was there. But its default url must be "localhost/geoserver/gwc/home". My question is why it is not in default and how can I change to default?
> 
> 

What is your proxy base url. Also describe your setup so that we can be able to assist

**Comment by BerkayOzen** [comment]
> > I have a big data set. For this I have to seed the tiles but when I tried to access GeoWebCache from GWCSettingsPage, I got 404 error.
> > ![image](https://user-images.githubusercontent.com/54314280/131592387-a7f84cb2-8575-4bc0-b1cb-ba3b37c7f3b0.png)
> > Luckily when I opened "localhost/geoserver" page I noticed gwc was there. But its default url must be "localhost/geoserver/gwc/home". My question is why it is not in default and how can I change to default?
> 
> What is your proxy base url. Also describe your setup so that we can be able to assist

Actually, for now I work in locally so my base url is `http://localhost:8089/geoserver/web/`. I use your 2.19.0 image from docker hub and I run the container with this command:
```
docker run --name geoserver --restart always -v geoserver-data:/var/local/geoserver -p 0.0.0.0:8089:8080 --link postgres:db /
-e GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc /
-e DB_BACKEND=POSTGRES /
-e HOST=postgres /
-e POSTGRES_PORT=5432 /
-e POSTGRES_DB=gis_data /
-e POSTGRES_USER=postgres /
-e POSTGRES_PASS=postgres /
-e STABLE_EXTENSIONS=css-plugin,mongodb-plugin,mbstyle-plugin /
-e GEOSERVER_ADMIN_USER=admin /
-e GEOSERVER_ADMIN_PASSWORD=geoserver /
-d kartoza/geoserver:2.19.0
```

**Comment by NyakudyaA** [comment]
> I solved this by setting `-e WEB_INTERFACE=false` because apparently this env var means "disable web interface"?  It should probably be renamed to `DISABLE_WEB_INTERFACE`...

@bushong1 thanks for the suggestion. If you read the .env file all env variables are explained their usages there. And by default that env variable is set to false

**Comment by BerkayOzen** [comment]
> I solved this by setting `-e WEB_INTERFACE=false` because apparently this env var means "disable web interface"? It should probably be renamed to `DISABLE_WEB_INTERFACE`...

Thank you for the suggestion but I actually don't want to disable the web interface. On the contrary, I want to use it in its widest form. I even want to use geowebcache endpoints as mentioned here. (https://docs.geoserver.org/latest/en/user/geowebcache/using.html#geowebcache-endpoint-url) Because I want to pre-seed big data that will not change using geowebcache and I want to improve performance and loading speeds. However, in the current situation, the geowebcache endpoint and the geoserver endpoint are the same.

**Comment by vijdz** [comment]
I don't understand how to modify gwc URL : geoserver/ points to gwc home, thus geoserver/gwc/demo isn't working.
Is it the expected behaviour behind reverse proxy ? How can I fix it ?
