### ISSUE TITLE
database targeting error

### ISSUE THREAD

**Issue by guisz1** [kartoza/docker-geoserver#294]
in the new version of the container, even though I'm implementing the domain of my database, being in localhost, I end up playing to an ip that has nothing to do with mine, I believe it's some env that's blocking
![image](https://user-images.githubusercontent.com/16584514/132524047-f1f9c3ec-1623-4396-bf72-1e7859260cbf.png)

**Comment by NyakudyaA** [comment]
@guisz1 Is that version of the image self built or from kartoza dockerhub. If it comes from kartoza dockerhub then that image is only useful with spc geonode and will not work with default geoserver. Please use the standard images kartoza/geoserver:version without any geonode in the name
