### ISSUE TITLE
The file epsg.properties is deleted when the geoserver starts

### ISSUE THREAD

**Issue by Lubchinskiy-Yuri** [kartoza/docker-geoserver#296]
1. $docker pull kartoza/geoserver:2.19.2
2. $docker volume create --driver local --opt type=none --opt device=/var/lib/docker/volumes/geoserver_data/_data --opt o=bind geoserver_data
3. $docker run -d --name geoserver1 -p 8080:8080 -v geoserver_data:/opt/geoserver/data_dir:   kartoza/geoserver:2.19.2
4. Put the epsg.properties file in the user_projections directory
5. $docker stop geoserver1
6. $docker start geoserver1
Expected Result: Сustom projections registered. 
Actual result: Custom projections not registered. The file epsg.properties is deleted when the geoserver starts

**Comment by NyakudyaA** [comment]
>     1. $docker pull kartoza/geoserver:2.19.2
> 
>     2. $docker volume create --driver local --opt type=none --opt device=/var/lib/docker/volumes/geoserver_data/_data --opt o=bind geoserver_data
> 
>     3. $docker run -d --name geoserver1 -p 8080:8080 -v geoserver_data:/opt/geoserver/data_dir:   kartoza/geoserver:2.19.2
> 
>     4. Put the epsg.properties file in the user_projections directory
> 
>     5. $docker stop geoserver1
> 
>     6. $docker start geoserver1
>        Expected Result: Сustom projections registered.
>        Actual result: Custom projections not registered. The file epsg.properties is deleted when the geoserver starts

You need to mount the files according to https://github.com/kartoza/docker-geoserver#mounting-configs

i.e 
```
 docker run --name "geoserver" -e GEOSERVER_ADMIN_USER=kartoza  -v /data:/settings/ -p 8080:8080 -d -t kartoza/geoserver
 ```
Where `/data` contains the file `epsg.properties`

**Comment by Lubchinskiy-Yuri** [comment]
Thanks. it worked
