### ISSUE TITLE
Environment variables not resolved at /settings/* configs

### ISSUE THREAD

**Issue by pedroetb** [kartoza/docker-geoserver#298]
For example, this substitution https://github.com/kartoza/docker-geoserver/blob/124da11786079a8a849d431a4b99ea0ffe2cc27f/scripts/functions.sh#L101

is done only when using default build_data/* configs, but it will be useful when defining new configs at /settings/*, for all of the supported config files.

**Comment by NyakudyaA** [comment]
> For example, this substitution https://github.com/kartoza/docker-geoserver/blob/124da11786079a8a849d431a4b99ea0ffe2cc27f/scripts/functions.sh#L101
> 
> is done only when using default build_data/* configs, but it will be useful when defining new configs at /settings/*, for all of the supported config files.

@pedroetb are you trying to mount configs with env variables in `settings` folder. Mounting files is meant to override what is in the build_data

**Comment by pedroetb** [comment]
@NyakudyaA yes, I hoped I could use at /settings the same functionality as in build_data. Using variables allows you to define a single config file for multiple instances (e.g. different nodes in a cluster).
