### ISSUE TITLE
[FEATURE REQUEST] - Proxy Base Url Env Variable Support

### ISSUE THREAD

**Issue by ondrovic** [kartoza/docker-geoserver#299]
Image Version: 2.19.2

It would be great if you could set the `PROXY BASE URL`  in an env variable in the event you cannot login to the ui to set it.

**Comment by NyakudyaA** [comment]
> Image Version: 2.19.2
> 
> It would be great if you could set the `PROXY BASE URL` in an env variable in the event you cannot login to the ui to set it.

This is already possible https://github.com/kartoza/docker-geoserver#proxy-base-url

**Comment by ondrovic** [comment]
This doesn't work if you are terminating ssl at the proxy level

**Comment by NyakudyaA** [comment]
> This doesn't work if you are terminating ssl at the proxy level

I don't understand what you are trying to do. Would you provide an example?
Alternatively, you can also mount the `web.xml` to the settings folder and set your proxy base_url in the `web.xml`
https://github.com/kartoza/docker-geoserver#mounting-configs

**Comment by NyakudyaA** [comment]
Fixed  by https://github.com/kartoza/docker-geoserver/pull/303
