### ISSUE TITLE
Using Tomcat base container but running self-contained Geoserver bin?

### ISSUE THREAD

**Issue by isuftin** [kartoza/docker-geoserver#3]
I'm confused as to why you're starting with the Tomcat 8.0 base container but are opting to instead run the self-contained Geoserver binary which runs on Jetty 6.1.8.

My use case is to run this container as part of an integration test and connect the container to a database container and I'd like to use JNDI to do so, but obviously writing the JNDI connection info into /usr/local/tomcat/conf/context.xml doesn't work and downloading the postgres driver to /usr/local/tomcat/lib isn't going to work.

Why not just run the Geoserver war on the Tomcat container?

**Comment by timlinux** [comment]
I by no means profess to be an expert in GeoServer configuration. Please feel free to provide a pull request if or point me to a relevant installation guide if you have a better way to configure it. I currently don't use this for any production work so I don't do much in the way of maintenance / improvements to it.

**Comment by alexgleith** [comment]
Hi @timlinux, I think isuftin is right. This dockerfile will work, but it is using Jetty, not Tomcat, so having Tomcat on the server is redundant.

You can do what you're doing by using a basic centos or ubuntu image.

I'm hoping to set up a Dockerfile to use Tomcat and the GeoServer .war file, so I'll come back and do a pull request if I remember!

**Comment by shane-axiom** [comment]
I was just looking for how to set Tomcat memory options and ran into this. Does anyone strongly prefer either Tomcat or Jetty? I lean toward Tomcat since it's more widely used. Anyone object if I submit a PR to change this to use Tomcat and the Geoserver war?

**Comment by alexgleith** [comment]
Tomcat is much better, in my opinion. And it's required to support CORS.

**Comment by shane-axiom** [comment]
This commit fixes #3 by using the GeoServer WAR download with Tomcat instead of the self-contained Jetty version. It also adds support for building the image with GeoServer plugins and adds instructions on setting Tomcat properties such as maximum memory.
