### ISSUE TITLE
Building new docker image fails

### ISSUE THREAD

**Issue by murarustefaan** [kartoza/docker-geoserver#30]
# The problem:
Trying to build a docker image using:
`docker build --build-arg ORACLE_JDK=true -t kartoza/geoserver .`
fails.

# Reason:
In the current Dockerfile, lines 41-67 contain 3 install steps. These install steps execute a wget that saves a archive to ./resources, though the dpkg install step tries to execute it from /tmp/resources.
`
RUN if [ ! -f /tmp/resources/libjpeg-turbo-official_1.5.3_amd64.deb ]; then \
    wget https://tenet.dl.sourceforge.net/project/libjpeg-turbo/1.5.3/libjpeg-turbo-official_1.5.3_amd64.deb -P /tmp/resources;\
    fi; \
    cd /tmp/resources/ && \
    dpkg -i libjpeg-turbo-official_1.5.3_amd64.deb
`

# Computer configuration
Dell E5570
Windows 10 x64
Docker engine 18.03.0-ce (linux containers)

# Solution
I can create a PR to update if someone else can also reproduce this.

**Comment by NyakudyaA** [comment]
@mayaro  thanks for picking this up. I have also updated the Readme. We have included the script `download.sh` which you can customise or run as is to install some mandatory GeoServer extensions like gdal,vector tiles. The script also builds some community modules(extensions). The building of comunity modules takes some time and consumes resources so you can comment it out from the `download.sh` script.  Downloading scripts locally helps in speeding up the build times as the resources are available locally
