### ISSUE TITLE
Password change doesn't work

### ISSUE THREAD

**Issue by gianx89** [kartoza/docker-geoserver#300]
I'm running 2.19.2 version on Docker for Windows (Windows 10) under ubuntu and WSL2. I'm using docker compose.

In my .env file I have

GEOSERVER_ADMIN_PASSWORD=mygeoserverpassword

and in the docker compose file I have

- GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}

However, when the boot finishes, I can login only with the old password "myawesomegeoserver".

Am I doing something wrong?

**Comment by NyakudyaA** [comment]
> I'm running 2.19.2 version on Docker for Windows (Windows 10) under ubuntu and WSL2. I'm using docker compose.
> 
> In my .env file I have
> 
> GEOSERVER_ADMIN_PASSWORD=mygeoserverpassword
> 
> and in the docker compose file I have
> 
>     * GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
> 
> 
> However, when the boot finishes, I can login only with the old password "myawesomegeoserver".
> 
> Am I doing something wrong?

`myawesomegeoserver` is not the default password. If the substitution was not working it would revert to `geoserver`
but it seems like you might be using an existing geoserver data directory where the password is already changed to myawesomegeoserver from a prior initialisation.

We currently do not have a way to force a reset password multiple times, I will work on it when I have some free time but for now I suggest you change the data directory volume or path if you mounting from the host

**Comment by gianx89** [comment]
Ok thanks, I'll try to reset the data, thanks
