### ISSUE TITLE
Geoserver fails on Apple silicon

### ISSUE THREAD

**Issue by ericsvendsen** [kartoza/docker-geoserver#307]
When I clone this repository on my M1 MacBook Air and run `docker-compose up`, Geoserver fails to start:
```
SEVERE [main] org.apache.catalina.startup.ContextConfig.processServletContainerInitializers Failed to detect ServletContainerInitializers for context with name [/geoserver]
geoserver_1  | 	java.net.MalformedURLException: no !/ found in url spec:file:/usr/local/tomcat/lib/tomcat-websocket.jar!/META-INF/services/javax.servlet.ServletContainerInitializer
```
and
```
28-Sep-2021 17:36:45.712 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more components marked the context as not correctly configured
geoserver_1  | 28-Sep-2021 17:36:45.714 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors
```
However, when I clone this repository on my Intel MacBook Pro and run `docker-compose up`, everything runs without any problems.

At first I wondered if this issue was related to #301, but even after pinning `IMAGE_VERSION` to `9.0-jdk11-openjdk-slim-buster` - as described in that issue - the behavior on my M1 machine is the same.

**Comment by NyakudyaA** [comment]
> When I clone this repository on my M1 MacBook Air and run `docker-compose up`, Geoserver fails to start:
> 
> ```
> 
> SEVERE [main] org.apache.catalina.startup.ContextConfig.processServletContainerInitializers Failed to detect ServletContainerInitializers for context with name [/geoserver]
> 
> geoserver_1  | 	java.net.MalformedURLException: no !/ found in url spec:file:/usr/local/tomcat/lib/tomcat-websocket.jar!/META-INF/services/javax.servlet.ServletContainerInitializer
> 
> ```
> 
> and
> 
> ```
> 
> 28-Sep-2021 17:36:45.712 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more components marked the context as not correctly configured
> 
> geoserver_1  | 28-Sep-2021 17:36:45.714 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors
> 
> ```
> 
> However, when I clone this repository on my Intel MacBook Pro and run `docker-compose up`, everything runs without any problems.
> 
> 
> 
> At first I wondered if this issue was related to #301, but even after pinning `IMAGE_VERSION` to `9.0-jdk11-openjdk-slim-buster` - as described in that issue - the behavior on my M1 machine is the same.

Please see https://hub.docker.com/repository/docker/jeffrosen1092/postgis

Which describes the issue. You will need to build the image locally and use it. Once we have setup GitHub actions to build the image then we can fix the build architecture

**Comment by ericsvendsen** [comment]
Ah, ok. Thank you for pointing me in the right direction! My apologies for not being able to track this one down.

**Comment by NyakudyaA** [comment]
Will be handled in #324
