### ISSUE TITLE
Default password is not working

### ISSUE THREAD

**Issue by robertd** [kartoza/docker-geoserver#313]
I'm running `2.19.2` but it appears that default username & password (admin/geoserver) are not working.

![image](https://user-images.githubusercontent.com/31543/137528839-6577cd79-4a94-4e61-a402-41d88d8600da.png)

**Comment by NyakudyaA** [comment]
> I'm running `2.19.2` but it appears that default username & password (admin/geoserver) are not working.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/31543/137528839-6577cd79-4a94-4e61-a402-41d88d8600da.png)
> 
> 

That password no longer works, the container now generates a strong password if you do not pass the env variable for password. The password is visible in the logs or inside the security folder of Geoserver as a text file.

We are trying to prevent users running the image in production with default password

**Comment by robertd** [comment]
Here is where I found this on dockerhub...

![image](https://user-images.githubusercontent.com/31543/137538924-70ec4522-a9bc-43f7-b363-5b49f8bf78dd.png)

**Comment by robertd** [comment]
@NyakudyaA #314 should fix this
