### ISSUE TITLE
Geoserver base url

### ISSUE THREAD

**Issue by robertd** [kartoza/docker-geoserver#319]
Is there a way to set geoserver base url without introducing nginx reverse proxy?

I'd like to run this in ECS behind a Load Balancer and going directly to `/` (tomcat root) is not what I'm looking for. Is there a way to pass env variable that configures tomcat to go to `/geoserver` by default?

**Comment by Kumark95** [comment]
Kinda late, but for anyone interested to make Tomcat redirect from "/" to "/geoserver/web" or other endpoint I include a `index.jsp` file in the  `/webapps/ROOT` directory:

```java
<%
  final String redirectURL = "/geoserver/web/";
  response.setStatus(HttpServletResponse.SC_MOVED_PERMANENTLY);
  response.setHeader("Location", redirectURL);
%>
```

But when using the `TOMCAT_EXTRAS=false` the `start.sh` script will remove anything that is placed in the `/webapps/ROOT` directory, so in my custom Dockerfile I include:

```Dockerfile
COPY --chown=geoserveruser:geoserverusers ./configuration/geoserver/index.jsp /tmp/index.jsp

# Recreate the webapps/ROOT directory with a redirect to the web interface
RUN echo '\n \
    #################################################################### \n \
    # Modified in Dockerfile. \n \
    # Ensure a redirect from ROOT endpoint to GeoServer web interface. \n \
    # By default, with `TOMCAT_EXTRAS=false` the ROOT dir is deleted \n \
    #################################################################### \n \
    delete_folder "${CATALINA_HOME}"/webapps/ROOT \n \
    mkdir "${CATALINA_HOME}"/webapps/ROOT \n \
    mv /tmp/index.jsp "${CATALINA_HOME}"/webapps/ROOT/index.jsp \n \
    #################################################################### \n \
    ' >> /scripts/start.sh
```

**Comment by NyakudyaA** [comment]
> Kinda late, but for anyone interested to make Tomcat redirect from "/" to "/geoserver/web" or other endpoint I include a `index.jsp` file in the  `/webapps/ROOT` directory:
> 
> 
> 
> ```java
> 
> <%
> 
>   final String redirectURL = "/geoserver/web/";
> 
>   response.setStatus(HttpServletResponse.SC_MOVED_PERMANENTLY);
> 
>   response.setHeader("Location", redirectURL);
> 
> %>
> 
> ```
> 
> 
> 
> But when using the `TOMCAT_EXTRAS=false` the `start.sh` script will remove anything that is placed in the `/webapps/ROOT` directory, so in my custom Dockerfile I include:
> 
> 
> 
> ```Dockerfile
> 
> COPY --chown=geoserveruser:geoserverusers ./configuration/geoserver/index.jsp /tmp/index.jsp
> 
> 
> 
> # Recreate the webapps/ROOT directory with a redirect to the web interface
> 
> RUN echo '\n \
> 
>     #################################################################### \n \
> 
>     # Modified in Dockerfile. \n \
> 
>     # Ensure a redirect from ROOT endpoint to GeoServer web interface. \n \
> 
>     # By default, with `TOMCAT_EXTRAS=false` the ROOT dir is deleted \n \
> 
>     #################################################################### \n \
> 
>     delete_folder "${CATALINA_HOME}"/webapps/ROOT \n \
> 
>     mkdir "${CATALINA_HOME}"/webapps/ROOT \n \
> 
>     mv /tmp/index.jsp "${CATALINA_HOME}"/webapps/ROOT/index.jsp \n \
> 
>     #################################################################### \n \
> 
>     ' >> /scripts/start.sh
> 
> ```

Thanks, I suggest you add a new variable ie REDIRECT_URL=FALSE which can be used to control this and put this on top of the logic for removing tomcat application folder.

Such that the variable be mutually exclusive with the TOMCAT_EXTRAS variable. This seems like a well sought after feature.

**Comment by Kumark95** [comment]
Sure thing, I'll try to make a PR during the week
