### ISSUE TITLE
Permissions denied regarding build data directory when starting container

### ISSUE THREAD

**Issue by rumski20** [kartoza/docker-geoserver#322]
Hello,
I am unable to start this container.
Geoserver version 2.19.2
Image built from repo:
```
    build: https://github.com/kartoza/docker-geoserver.git
    image: kartoza/geoserver:${GS_VERSION_TAG}
```

`docker` user has full permissions on host.

Here is what I am seeing in the log file:
```
geoserver_1  | cp: cannot open '/build_data/web.xml' for reading: Permission denied
geoserver_1  | /scripts/functions.sh: line 199: /build_data/geowebcache-diskquota.xml: Permission denied
geoserver_1  | /scripts/functions.sh: line 212: /build_data/geowebcache-diskquota-jdbc.xml: Permission denied
geoserver_1  | STABLE_EXTENSIONS is unset, so we do not install any stable extensions
geoserver_1  | COMMUNITY_EXTENSIONS is unset, so we do not install any community extensions
geoserver_1  | /scripts/functions.sh: line 225: /build_data/controlflow.properties: Permission denied
geoserver_1  | cp: cannot open '/build_data/context.xml' for reading: Permission denied
geoserver_1  | [Entrypoint] GENERATED tomcat  PASSWORD:  o8W4IAfbnHZLYmpzax
geoserver_1  |
geoserver_1  | /scripts/functions.sh: line 79: /build_data/tomcat-users.xml: Permission denied
geoserver_1  | /scripts/functions.sh: line 238: /build_data/log4j.properties: Permission denied
```

Thank you for any help you can provide.

**Comment by NyakudyaA** [comment]
> Hello, I am unable to start this container. Geoserver version 2.19.2 Image built from repo:
> 
> ```
>     build: https://github.com/kartoza/docker-geoserver.git
>     image: kartoza/geoserver:${GS_VERSION_TAG}
> ```
> 
> `docker` user has full permissions on host.
> 
> Here is what I am seeing in the log file:
> 
> ```
> geoserver_1  | cp: cannot open '/build_data/web.xml' for reading: Permission denied
> geoserver_1  | /scripts/functions.sh: line 199: /build_data/geowebcache-diskquota.xml: Permission denied
> geoserver_1  | /scripts/functions.sh: line 212: /build_data/geowebcache-diskquota-jdbc.xml: Permission denied
> geoserver_1  | STABLE_EXTENSIONS is unset, so we do not install any stable extensions
> geoserver_1  | COMMUNITY_EXTENSIONS is unset, so we do not install any community extensions
> geoserver_1  | /scripts/functions.sh: line 225: /build_data/controlflow.properties: Permission denied
> geoserver_1  | cp: cannot open '/build_data/context.xml' for reading: Permission denied
> geoserver_1  | [Entrypoint] GENERATED tomcat  PASSWORD:  o8W4IAfbnHZLYmpzax
> geoserver_1  |
> geoserver_1  | /scripts/functions.sh: line 79: /build_data/tomcat-users.xml: Permission denied
> geoserver_1  | /scripts/functions.sh: line 238: /build_data/log4j.properties: Permission denied
> ```
> 
> Thank you for any help you can provide.

![Screenshot 2021-11-28 at 17 53 56](https://user-images.githubusercontent.com/2510900/143775583-8a917b2c-1cfe-4f36-8122-83ed36e5d0ee.png)

Can you check what version of docker-compose you are using.

**Comment by rumski20** [comment]
This was an issue with how I was specifying the `build` param in my `docker-compose` file.
