### ISSUE TITLE
Backup and upgrade the service

### ISSUE THREAD

**Issue by curtis18** [kartoza/docker-geoserver#323]
Using the 2.20.0 version, it is found that the RANDOMSTRING and INSTANCE_STRING does not work anymore, the cluster folder shows different names for clustered server name. Even I did backup the data_dir, I cannot migrate the data_dir to the 2.20.0 (without clustering) and it will show the following errors. What is the best procedure to do backup and upgrade in using this docker image? Is only data_dir directory required to be backup? Thank you.

03-Nov-2021 02:27:54.266 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th                                        readLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@75f90b39]) and a value of type [org.geotools.referencing.operation.projection.T                                        ransverseMercator.Provider] (value [PROJECTION["Transverse_Mercator"]]) but failed to remove it when the web application was stopped. Threads are going to be re                                        newed over time to try and avoid a probable memory leak.
03-Nov-2021 02:27:54.267 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th                                        readLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6a383dab]) and a value of type [org.springframework.security.core.context.Secur                                        ityContextImpl] (value [org.springframework.security.core.context.SecurityContextImpl@ffffffff: Null authentication]) but failed to remove it when the web appli                                        cation was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
03-Nov-2021 02:27:54.267 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th                                        readLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6faf102]) and a value of type [org.geotools.referencing.wkt.Formatter] (value [                                        ]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
03-Nov-2021 02:27:54.267 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th                                        readLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@211a856b]) and a value of type [org.geo                                        webcache.storage.CompositeBlobStore.StoreSuitabilityCheck] (value [EXISTING]) but failed to remove it when the web application was stopped. Threads are going to                                         be renewed over time to try and avoid a probable memory leak.
03-Nov-2021 02:27:54.274 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/g                                        eoserver] has finished in [17,413] ms
03-Nov-2021 02:27:54.274 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
03-Nov-2021 02:27:54.285 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/R                                        OOT] has finished in [11] ms
03-Nov-2021 02:27:54.289 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
03-Nov-2021 02:27:54.298 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [17980] milliseconds
03-Nov-2021 02:27:55.332 INFO [FileSystemWatcher-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web appli                                        cation instance has been stopped already. Could not load [org.geoserver.platform.resource.ResourceNotification$Kind]. The following stack trace is thrown for de                                        bugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.geoserver.platform.resource                                        .ResourceNotification$Kind]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal a                                        ccess.
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1427)
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1415)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1254)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
                at org.geoserver.platform.resource.FileSystemWatcher$Watch.pollDirectory(FileSystemWatcher.java:218)
                at org.geoserver.platform.resource.FileSystemWatcher$Watch.changed(FileSystemWatcher.java:211)
                at org.geoserver.platform.resource.FileSystemWatcher$1.run(FileSystemWatcher.java:342)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by NyakudyaA** [comment]
> Using the 2.20.0 version, it is found that the RANDOMSTRING and INSTANCE_STRING does not work anymore, the cluster folder shows different names for clustered server name. Even I did backup the data_dir, I cannot migrate the data_dir to the 2.20.0 (without clustering) and it will show the following errors. What is the best procedure to do backup and upgrade in using this docker image? Is only data_dir directory required to be backup? Thank you.
> 
> 03-Nov-2021 02:27:54.266 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th readLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@75f90b39]) and a value of type [org.geotools.referencing.operation.projection.T ransverseMercator.Provider] (value [PROJECTION["Transverse_Mercator"]]) but failed to remove it when the web application was stopped. Threads are going to be re newed over time to try and avoid a probable memory leak. 03-Nov-2021 02:27:54.267 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th readLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6a383dab]) and a value of type [org.springframework.security.core.context.Secur ityContextImpl] (value [org.springframework.security.core.context.SecurityContextImpl@ffffffff: Null authentication]) but failed to remove it when the web appli cation was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak. 03-Nov-2021 02:27:54.267 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th readLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6faf102]) and a value of type [org.geotools.referencing.wkt.Formatter] (value [ ]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak. 03-Nov-2021 02:27:54.267 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a Th readLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@211a856b]) and a value of type [org.geo webcache.storage.CompositeBlobStore.StoreSuitabilityCheck] (value [EXISTING]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak. 03-Nov-2021 02:27:54.274 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/g eoserver] has finished in [17,413] ms 03-Nov-2021 02:27:54.274 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT] 03-Nov-2021 02:27:54.285 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/R OOT] has finished in [11] ms 03-Nov-2021 02:27:54.289 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"] 03-Nov-2021 02:27:54.298 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [17980] milliseconds 03-Nov-2021 02:27:55.332 INFO [FileSystemWatcher-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web appli cation instance has been stopped already. Could not load [org.geoserver.platform.resource.ResourceNotification$Kind]. The following stack trace is thrown for de bugging purposes as well as to attempt to terminate the thread which caused the illegal access. java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.geoserver.platform.resource .ResourceNotification$Kind]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal a ccess. at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1427) at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1415) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1254) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215) at org.geoserver.platform.resource.FileSystemWatcher$Watch.pollDirectory(FileSystemWatcher.java:218) at org.geoserver.platform.resource.FileSystemWatcher$Watch.changed(FileSystemWatcher.java:211) at org.geoserver.platform.resource.FileSystemWatcher$1.run(FileSystemWatcher.java:342) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)

It looks like we might need to add a flag to skip the initialisation of the data directory if you are using an existing data directory. 
We need to adjust the following

https://github.com/kartoza/docker-geoserver/blob/master/scripts/start.sh#L159 to become something like
```
if [[ ! -f $CLUSTER_LOCKFILE ||  ! -z  "${EXISTING_DATA_DIR}" ]]; then
      create_dir ${CLUSTER_CONFIG_DIR}
      broker_xml_config
      touch ${CLUSTER_LOCKFILE}
  fi
  cluster_config
  broker_config

fi
```


 For now, what you might need to do is create a text file and mount it to the folder /scripts i.e

```
-v ./random_pass.txt:/scripts/.pass_14.txt
```
Where the contents of `random_pass.txt` correspond to the value of INSTANCE_STRING

**Comment by curtis18** [comment]
Thanks for your reply and great help. I will try it and hope that the future image can have better support on version upgrade and data migration coming from other GeoServer.

**Comment by NyakudyaA** [comment]
> Thanks for your reply and great help. I will try it and hope that the future image can have better support on version upgrade and data migration coming from other GeoServer.

@curtis18 I have a PR which I will be submitting soon. I will ping you to test this

**Comment by NyakudyaA** [comment]
@curtis18 Can you test the PR https://github.com/kartoza/docker-geoserver/pull/324 if it fixes your issue

**Comment by curtis18** [comment]
@NyakudyaA Okay, I will test and inform you if there is any issues found. Thanks for your help.
