### ISSUE TITLE
how can I Clustering using the ActiveMQ-broker?

### ISSUE THREAD

**Issue by PingYufeng** [kartoza/docker-geoserver#333]
![image](https://user-images.githubusercontent.com/37933036/141674165-9d83dd72-88a6-4c61-bb4d-2c13e9d43df9.png)

I want to  Cluster using the ActiveMQ-broker, how do I set the docker-compose.yml, THANKS!  The 'BROKER_URL=tcp://0.0.0.0:61661' in the docker-compose.yml of the kartoza/docker-geoserver cluster is activting the Embedded activemq?   

How can I define my activemq service and use it in the geoserver?

@robertd @timlinux @daf @gubuntu @seifer08ms

**Comment by NyakudyaA** [comment]
@PingYufeng You do not need to ping a lot of people to get help. This is a community project and we generally help as best as we can. If you need us to help you personally I suggest you look at https://github.com/kartoza/docker-geoserver#support

For now I think you need to pull the latest image/repo and run the clustering as it is and then add your modifications

**Comment by PingYufeng** [comment]
@NyakudyaA  Thanks, I'm sorry for my behavior. I had run it, but foud some question that I can't solve it ,so I wan to ask someone who knows the solution.

**Comment by NyakudyaA** [comment]
Clustering works out of the box using the demo docker-compose.yml
