### ISSUE TITLE
Errors in `env-data.sh` defaults?

### ISSUE THREAD

**Issue by erhhung** [kartoza/docker-geoserver#335]
1. https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L100-L102
    Why set `GEOSERVER_CSRF_DISABLED` to true by default if the user didn't set that variable?
2. https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L262-L264
    https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L270-L272
    `CSRF_WHITELIST` checking is duplicated twice.
3. https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L266-L268
    Typo: `INITIAL_HEAP_OCCUPANCY_PERCENT` instead of `INITIAL_HEAT_OCCUPANCY_PERCENT`

Lots of inconsistent variable value quoting and false/true capitalization throughout that should also be standardized...

**Comment by NyakudyaA** [comment]
> 1. https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L100-L102
> 
>     Why set `GEOSERVER_CSRF_DISABLED` to true by default if the user didn't set that variable?

Why should it be false?
> 
> 2. https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L262-L264
> 
>     https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L270-L272
> 
>     `CSRF_WHITELIST` checking is duplicated twice.

This should be removed 
> 
> 3. https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L266-L268
> 
>     Typo: `INITIAL_HEAP_OCCUPANCY_PERCENT` instead of `INITIAL_HEAT_OCCUPANCY_PERCENT`

It should be HEAP, so the entry point script should be adjusted 
> 
> 
> 
> Lots of inconsistent variable value quoting and false/true capitalization throughout that should also be standardized...

Please feel free to take the lead here. What would you prefer uppercase or lowercase?
