### ISSUE TITLE
Broken 'german Umlauts' in GUI

### ISSUE THREAD

**Issue by t-book** [kartoza/docker-geoserver#341]
Hi,

I've just started GeoServer from the main branch (tag 2.20.0) but the german umlauts display is broken. I would have guessed a wrong encoding on the startup of tomcat, but this is set to UTF-8 per default .env (`-Dfile.encoding`). What else could be the cause?

![Bildschirmfoto 2021-11-30 um 07 36 02](https://user-images.githubusercontent.com/20478652/143998178-d3c77065-0ce6-40d6-8626-ed8d248a4040.png)

**Comment by phtlay** [comment]
Hi, this is actually a bug within GeoServer 2.20.0 itself: https://osgeo-org.atlassian.net/browse/GEOS-10282. It has already been fixed in version 2.20.1, so the easiest solution would be to update the GS_VERSION in the .env file.

**Comment by NyakudyaA** [comment]
> Hi, this is actually a bug within GeoServer 2.20.0 itself: https://osgeo-org.atlassian.net/browse/GEOS-10282. It has already been fixed in version 2.20.1, so the easiest solution would be to update the GS_VERSION in the .env file.

There should already be a version 2.20.1 and latest corresponding to the latest version. Please check if it is fixed

**Comment by t-book** [comment]
Thanks!
