### ISSUE TITLE
when I pass geoserver+minio with gwc-s3-plugin, but after I restart geoserver, it reports exception

### ISSUE THREAD

**Issue by PingYufeng** [kartoza/docker-geoserver#347]
**I pass geoserver+minio to set s3 blobstore with gwc-s3-plugin, but when I restart geoserver, it reports the thread[org.geowebcache.storage.CompositeBlobStore.StoreSuitabilityCheck] could not be killed.**

org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a ThreadLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@670ae7df]) and a value of type [org.geowebcache.storage.CompositeBlobStore.StoreSuitabilityCheck] (value [EXISTING]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Exception detail：**
`geoserver-master      | 04-Dec-2021 14:50:09.289 INFO [main] org.geoserver.GeoserverInitStartupListener.contextDestroyed Cleaned up javabean caches
geoserver-master      | 04-Dec-2021 14:50:09.504 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [geoserver] appears to have started a thread named [FileSystemWatcher-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
geoserver-master      |  java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
geoserver-master      |  java.base@11.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
geoserver-master      |  java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
geoserver-master      |  java.base@11.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
geoserver-master      |  java.base@11.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
geoserver-master      |  java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
geoserver-master      |  java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
geoserver-master      |  java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
geoserver-master      |  java.base@11.0.10/java.lang.Thread.run(Thread.java:834)
geoserver-master      | 04-Dec-2021 14:50:09.506 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a ThreadLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@670ae7df]) and a value of type [org.geowebcache.storage.CompositeBlobStore.StoreSuitabilityCheck] (value [EXISTING]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
geoserver-master      | 04-Dec-2021 14:50:09.513 INFO [main] java.util.prefs.FileSystemPreferences$1.run Created user preferences directory.
geoserver-master      | 04-Dec-2021 14:50:09.524 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [geoserver] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@3c5fb2fa]) and a value of type [org.geotools.referencing.operation.projection.TransverseMercator.Provider] (value [PROJECTION["Transverse_Mercator"]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
geoserver-master      | 04-Dec-2021 14:50:09.533 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/geoserver] has finished in [12,633] ms
geoserver-master      | 04-Dec-2021 14:50:09.533 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
geoserver-master      | 04-Dec-2021 14:50:09.587 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
geoserver-master      | 04-Dec-2021 14:50:09.604 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [71] ms
geoserver-master      | 04-Dec-2021 14:50:09.604 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
geoserver-master      | 04-Dec-2021 14:50:09.710 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
geoserver-master      | 04-Dec-2021 14:50:09.735 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [131] ms
geoserver-master      | 04-Dec-2021 14:50:09.735 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
geoserver-master      | 04-Dec-2021 14:50:09.772 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
geoserver-master      | 04-Dec-2021 14:50:09.774 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [39] ms
geoserver-master      | 04-Dec-2021 14:50:09.774 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
geoserver-master      | 04-Dec-2021 14:50:09.814 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
geoserver-master      | 04-Dec-2021 14:50:09.815 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [41] ms
geoserver-master      | 04-Dec-2021 14:50:09.815 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
geoserver-master      | 04-Dec-2021 14:50:09.851 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
geoserver-master      | 04-Dec-2021 14:50:09.853 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [38] ms
geoserver-master      | 04-Dec-2021 14:50:09.857 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
geoserver-master      | 04-Dec-2021 14:50:09.866 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [13008] milliseconds
geoserver-master      | 04-Dec-2021 14:50:12.911 INFO [FileSystemWatcher-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.geoserver.platform.resource.ResourceNotification$Kind]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
geoserver-master      | 	java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.geoserver.platform.resource.ResourceNotification$Kind]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
geoserver-master      | 		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
geoserver-master      | 		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
geoserver-master      | 		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1226)
geoserver-master      | 		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
geoserver-master      | 		at org.geoserver.platform.resource.FileSystemWatcher$Watch.pollDirectory(FileSystemWatcher.java:217)
geoserver-master      | 		at org.geoserver.platform.resource.FileSystemWatcher$Watch.changed(FileSystemWatcher.java:210)
geoserver-master      | 		at org.geoserver.platform.resource.FileSystemWatcher$1.run(FileSystemWatcher.java:341)
geoserver-master      | 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
geoserver-master      | 		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
geoserver-master      | 		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
geoserver-master      | 		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
geoserver-master      | 		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
geoserver-master      | 		at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by PingYufeng** [comment]
root@my# ps -eLf | grep checkThreadLocalMapForLeaks 
root     74989 52149 74989  0    1 23:22 pts/3    00:00:00 grep --color=auto checkThreadLocalMapForLeaks

It could not be killed,and the checkThreadLocalMapForLeaks always be created when I kill the current PID.

**Comment by NyakudyaA** [comment]
Refer to https://github.com/kartoza/docker-geoserver/issues/423
