### ISSUE TITLE
Plugins in setup.sh not installed 

### ISSUE THREAD

**Issue by vwmaus** [kartoza/docker-geoserver#35]
I noticed that the image does not include the plugins which should be installed by `setup.sh`. I solved the issue by creating the plugins tmp folder with this
```
if [ ! -d ${work_dir}/plugins ];
 then
     echo "Creating tmp plugins directory"
     mkdir -p ${work_dir}/plugins
 else
     echo "tmp plugins directory already exist"
 fi
```
before this https://github.com/kartoza/docker-geoserver/blob/efa129d19cbae4fa051ab768ae237b0d6fa3ad50/setup.sh#L39

**Comment by NyakudyaA** [comment]
@vwmaus  thanks for pointing this out. The line https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L45 adds the resources folder. It should have the plugins folder within that. I will update the repo and add the folder and also add your steps in it. 

If there are any other plugins you intend to install you can just download them into the resources/plugins folder

**Comment by vwmaus** [comment]
Cool, many thanks @NyakudyaA

**Comment by NyakudyaA** [comment]
Done @vwmaus
