### ISSUE TITLE
Update to 2.20.2 to incorporate Geoserver Log4JS resolution

### ISSUE THREAD

**Issue by clough360** [kartoza/docker-geoserver#353]
The Log4JS issue appears to have been resolved in GeoServer in versions 2.19.4 and 2.20.2
See https://osgeo-org.atlassian.net/browse/GEOS-10335

Re-publish docker-geoserver with this version of GeoServer
Many thanks.
Si

**Comment by ropable** [comment]
Ref PR #354

**Comment by Nkmol** [comment]
Now that we have 2.20.2 migrated and I believe this ticket is done, right? Can we make sure to release a "2.20.2" image of this?

**Comment by NyakudyaA** [comment]
we have published the image on docker hub
