### ISSUE TITLE
Invalid credentials after adding layers

### ISSUE THREAD

**Issue by rumski20** [kartoza/docker-geoserver#356]
I'm experiencing an odd issue that may be related to Geoserver rather than how it's built here with Docker.

I can build and startup the container and log in to the web interface just fine using the credentials (`GEOSERVER_ADMIN_USER` and `GEOSERVER_ADMIN_PASSWORD`) I have specified in my `.env` file.

I then run a script that imports a number of data sets that were mounted in a volume on the container into Geoserver. That runs fine as well. 

However, when I try to log in again after the script has completed, I get the usual error message: "Invalid username/password combination". This renders the container useless to me.

Any idea what is happening here?
Thank you.

**Comment by NyakudyaA** [comment]
Can you please send a snippet of the script so that we can try to replicate

**Comment by rumski20** [comment]
I think this issue can be closed. I still experience this behavior on occasion, but I can't pin down exactly why (containers stopping/starting, Geoserver bug, etc).
