### ISSUE TITLE
About setting GeoServer language

### ISSUE THREAD

**Issue by curtis18** [kartoza/docker-geoserver#361]
Is it possible to add language, region, country options in GEOSERVER_OPTS or JAVA_OPTS for changing the GeoServer interface language?
-Duser.language=en -Duser.region=US -Duser.country=US

Thank you.

**Comment by NyakudyaA** [comment]
Can you do a PR, we can accept this and you can also include the text editor preferably vi or nano

**Comment by curtis18** [comment]
OK. I will send you a PR later. Thanks a lot.

**Comment by curtis18** [comment]
Just send you a PR on develop branch. Thank you.

**Comment by NyakudyaA** [comment]
Fixed by https://github.com/kartoza/docker-geoserver/pull/362
