### ISSUE TITLE
geoserver 连接 postgis报错

### ISSUE THREAD

**Issue by wxmicker** [kartoza/docker-geoserver#363]
使用docker compose -d 运行了项目 docker已经拉取成功了三个服务,但是使用geoserver配置postgis报错
![image](https://user-images.githubusercontent.com/95065021/148883773-6f13c456-af8c-496d-9290-66a54041670a.png)

**Comment by NyakudyaA** [comment]
Please check if you have enabled SSL encryption. Share your docker-compose
