### ISSUE TITLE
Geoserver docker default username password on linux host

### ISSUE THREAD

**Issue by t-hey** [kartoza/docker-geoserver#366]
I am using  kartoza/geoserver:2.19.2 docker container on KUbuntu host.
I use the following docker run command to create the container.
`sudo docker run -d -p 8600:8080 --name geoserver -v /opt/geoserver/data_dir:/opt/geoserver/data_dir -e COMMUNITY_EXTENSIONS=mbtiles-store-plugin kartoza/geoserver:2.19.2`

I have also run the following command to set rights on the `/opt/geoserver` directory on the host.
`sudo chmod -R o+rwx /opt/geoserver/`

The Geoserver then run and I can access the start page with the following URL `http://<ip>:8600/geoserver/`, I then supply the default user **admin** and password **geoserver**, but I get an error message "Invalid username/password combination".

I suspect a rights issue on the host machine, but can't figure it out. 
Can someone please point me in the right direction to fix this, please?

Regards

**Comment by NyakudyaA** [comment]
> /opt/geoserver/data_dir

This folder needs to be owned by the current user i.e `sudo chown -R ${user}:${user } /opt/geoserver/data_dir`
Alternatively try to run it using docker volumes and see if it works

**Comment by t-hey** [comment]
HI NyakudyaA, thank you for the reply. I changed the ownership of the `/opt/geoserver/data_dir` like you suggested. But ibut I get the same result "Invalid username/password combination"". I did get GeoServer in a docker container running on a Ubuntu before, that worked. I decided to use the same version as before. With the following recipe.

```
sudo mkdir -p /opt/geoserver/data_dir
sudo chown -R $USER:$USER /opt/geoserver/data_dir
sudo docker run -d -p 8600:8080 --name geoserver -v /opt/geoserver/data_dir:/opt/geoserver/data_dir -e COMMUNITY_EXTENSIONS=mbtiles-store-plugin kartoza/geoserver:2.19.0
```
And it worked.
I have repeated the recipe above with kartoza/geoserver:2.19.2, but I get the same result "Invalid username/password combination".
Looks like the problem is with kartoza/geoserver:2.19.2
I am happy to test any suggestions you have to resolve this. 
At the moment the `/opt/geoserver/data_dir/`ownership looks like this:
```
dev@dev-VirtualBox:/home$ ll /opt/geoserver
total 12
drwxr-xr-x  3 root root 4096 Jan 22 16:03 ./
drwxr-xr-x  6 root root 4096 Jan 22 16:03 ../
drwxr-xr-x 11 dev  dev  4096 Jan 22 16:04 data_dir/
```
And the `/opt/geoserver/data_dir/` looks like this 
```
dev@dev-VirtualBox:/home$ ll /opt/geoserver/data_dir/
total 64
drwxr-xr-x 9 dev  dev    4096 Jan 22 16:04 ./
drwxr-xr-x 3 root root   4096 Jan 22 16:03 ../
-rw-r--r-- 1 dev  10001   134 Jan 22 16:04 controlflow.properties
-rw-r--r-- 1 dev  10001 13158 Jan 22 16:04 epsg.properties
drwxr-x--- 3 dev  10001  4096 Jan 22 16:04 gwc/
-rw-r----- 1 dev  10001  1597 Jan 22 16:04 gwc-gs.xml
-rw-r----- 1 dev  10001     0 Jan 22 16:04 logging.xml
drwxr-xr-x 3 dev  10001  4096 Jan 22 16:04 monitoring/
drwxr-xr-x 8 dev  10001  4096 Jan 22 16:04 security/
drwxr-x--- 2 dev  10001  4096 Jan 22 16:04 styles/
drwxr-x--- 3 dev  10001  4096 Jan 22 16:04 temp/
drwxr-x--- 2 dev  10001  4096 Jan 22 16:04 tmp/
-rw-r--r-- 1 dev  10001     0 Jan 22 16:04 .updatepassword.lock
drwxr-xr-x 2 dev  10001  4096 Jan 22 16:04 user_projections/
-rw-r----- 1 dev  10001  1744 Jan 22 16:04 wps.xml
```

**Comment by NyakudyaA** [comment]
> I am using  kartoza/geoserver:2.19.2 docker container on KUbuntu host.
> I use the following docker run command to create the container.
> `sudo docker run -d -p 8600:8080 --name geoserver -v /opt/geoserver/data_dir:/opt/geoserver/data_dir -e COMMUNITY_EXTENSIONS=mbtiles-store-plugin kartoza/geoserver:2.19.2`
> 
> I have also run the following command to set rights on the `/opt/geoserver` directory on the host.
> `sudo chmod -R o+rwx /opt/geoserver/`
> 
> The Geoserver then run and I can access the start page with the following URL `http://<ip>:8600/geoserver/`, I then supply the default user **admin** and password **geoserver**, but I get an error message "Invalid username/password combination".
> 
> I suspect a rights issue on the host machine, but can't figure it out. 
> Can someone please point me in the right direction to fix this, please?
> 
> Regards
> 
> 
> 

Ooh I hadn't really looked at your issues in detail. If you do not pass any environment variables we generate an random strong password as s specified in https://github.com/kartoza/docker-geoserver/blob/master/scripts/update_passwords.sh#L75

This was meant to prevent people from running the image in production with the default passwords. 

Please check the password in security folder of geoserver data directory. Alternatively just pass the env variable for the password as an env variable during runtime

**Comment by t-hey** [comment]
HI NyakudyaA, again thank you for the reply.
This time it worked. Thanks for the help.
