### ISSUE TITLE
Image kartoza/geogig:1.2.0 does not exist

### ISSUE THREAD

**Issue by urzds** [kartoza/docker-geoserver#38]
According to https://hub.docker.com/r/kartoza/geogig/tags/ the only tag of kartoza/geogig is `1.0b1`. The tag `1.2.0` that is referenced in docker-compose.yml does not exist.

**Comment by NyakudyaA** [comment]
@urzds You can use the latest version in the docker hub. I will create the 1.2.0 image

**Comment by urzds** [comment]
Thanks. We prefer using tagged versions.

**Comment by urzds** [comment]
`docker-compose.yml` in this repository still refers to a non-existing `image: kartoza/geogig:1.2.0`.

**Comment by urzds** [comment]
https://hub.docker.com/r/kartoza/geogig/tags/ still shows no sign of a `1.2.0` tag. Are you still working on this, @NyakudyaA ?

**Comment by NyakudyaA** [comment]
@urzds I will deploy before the end of the week

**Comment by NyakudyaA** [comment]
Available
