### ISSUE TITLE
Unable to add PostGIS as a Data Source from GeoServer web interface

### ISSUE THREAD

**Issue by franchyze923** [kartoza/docker-geoserver#382]
I'm trying to add the PostGIS database as a Data Source via the GeoServer web interface. 

I keep getting the following error - 

`Error creating data store, check the parameters. Error message: Unable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: no pg_hba.conf entry for host "172.23.0.3", user "docker", database "gis", no encryption)`

<img width="1271" alt="Screen Shot 2022-03-12 at 3 21 21 PM" src="https://user-images.githubusercontent.com/9319623/158038414-6dc3a81b-e1e8-4392-a60e-ee91c5b9d15d.png">

I'm able to connect to this PostGIS database using PGAdmin, from my desktop with the same user/pass I'm providing to GeoServer. Only difference is on my desktop I'm using the IP address where I have the containers running and I'm also using the 32767 port instead of 5432. 

I believe the 172.23.0.3 is the IP address of the GeoServer container. It would seem that the PostGIS container is not allowing the connection from the GeoServer container? Do I need to go into the running PostGIS container and edit the pg_hba.conf file and allow the GeoServer container to be able to connect? Is there a config I can provide in the .env or .yaml that would do this for me?

Thanks

**Comment by NyakudyaA** [comment]
Can you check the ssl settings. You will need to adjust it to

**Comment by franchyze923** [comment]
Which SSL settings are you referring to? The .env file I'm using specifies SSL=false. I'm accessing the GeoServer web interface over HTTP.

**Comment by NyakudyaA** [comment]
> Which SSL settings are you referring to? The .env file I'm using specifies SSL=false. I'm accessing the GeoServer web interface over HTTP.
Please check the following 
https://gis.stackexchange.com/questions/423872/geoserver-ssl-certificate

**Comment by NyakudyaA** [comment]
![Peek 2022-03-30 16-11](https://user-images.githubusercontent.com/2510900/160855376-280b84b6-ccde-4e27-9461-3c9d7e0d53ad.gif)

**Comment by intersides** [comment]
That's worked for me ! surprised that the hostname is db as the service name in the docker-compose file.
