### ISSUE TITLE
Add native JAI and ImageIO support

### ISSUE THREAD

**Issue by lufishggg** [kartoza/docker-geoserver#383]
Maybe can add native JAI and ImageIO support, which can see that at https://geoserver.geo-solutions.it/multidim/install_run/jai_io_install.html? Use an environment variable to control.

**Comment by NyakudyaA** [comment]
Isn't this already part of the image ?

**Comment by lufishggg** [comment]
> Isn't this already part of the image ?

But when I run the image, and then check the server status of the geoserver at web UI, I see that native jai and native jai imageio is false?

![image](https://user-images.githubusercontent.com/31639618/158051456-5cfde162-212c-4a26-8e56-df654ef9f2c3.png)

**Comment by NyakudyaA** [comment]
> > Isn't this already part of the image ?
> 
> But when I run the image, and then check the server status of the geoserver at web UI, I see that native jai and native jai imageio is false?
> 
> ![image](https://user-images.githubusercontent.com/31639618/158051456-5cfde162-212c-4a26-8e56-df654ef9f2c3.png)

maybe you can do a PR with the suggested changes

**Comment by NyakudyaA** [comment]
@lufishggg  This will not be implemented because the Geoserver team doesn't recommend it. See https://stackoverflow.com/questions/71437752/how-can-i-install-native-jai-on-geoserver-2-20-x-geoserver-2-19-x
