### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by JD99** [kartoza/docker-geoserver#388]
Creating /opt/geoserver/data_dir/user_projections directory
mkdir: cannot create directory ‘/opt/geoserver/data_dir/user_projections’: Permission denied 

`
      volumes:
        - /home/maps/geoserver/data_dir:/opt/geoserver/data_dir     
`

**Comment by NyakudyaA** [comment]
> Creating /opt/geoserver/data_dir/user_projections directory mkdir: cannot create directory ‘/opt/geoserver/data_dir/user_projections’: Permission denied
> 
> `volumes: - /home/maps/geoserver/data_dir:/opt/geoserver/data_dir `

make sure the volume is owned by you. run
```
mkdir -p /home/maps/geoserver/data_dir
sudo chown whoami:whoami /home/maps/geoserver/data_dir
```

**Comment by JD99** [comment]
did not help ..
/home/maps/geoserver/data_dir
mounted folder, maybe this is the case

**Comment by NyakudyaA** [comment]
> did not help .. /home/maps/geoserver/data_dir mounted folder, maybe this is the case

Did you let geoserver create the folder before you started or not. I suggest you create a new folder with RW access and owned by you and test again otherwise you might need to recursively make this owned by you and also change the permissions to RW
