### ISSUE TITLE
Cannot connect to local machine postgis database

### ISSUE THREAD

**Issue by learningnoobi** [kartoza/docker-geoserver#397]
I am using image provided in docker hub . Everything works fine . But when I am creating store to connect my local database . I cannot create it . It show following error

`Error creating data store, check the parameters. Error message: Unable to obtain connection: Cannot create PoolableConnectionFactory (Connection to 127.0.0.1:631 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)`

**Comment by NyakudyaA** [comment]
Please check https://gis.stackexchange.com/questions/423872/geoserver-ssl-certificate
