### ISSUE TITLE
Building via master:docker-compose-build.yml results in 404 on /geoserver

### ISSUE THREAD

**Issue by PhilippBuehlerOkeanos** [kartoza/docker-geoserver#403]
OS: Ubuntu 21.10 (GNU/Linux 5.13.0-40-generic x86_64)

Pulling the master branch and deploying the containers via docker-compose-build.yml yields in a 404 on server:8600/geoserver!

The Apache client runs fine but going to /geoserver/web results in 

> the requested resource [/geoserver] is not available

The logs show no error but:

> org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors

**Comment by NyakudyaA** [comment]
Can you please share the logs? And did you build the containers locally?

**Comment by PhilippBuehlerOkeanos** [comment]
I think its resulting from files being cached and not being rebuild. Even after deleting all kartoza/geoserver related containers, volumes, images and networks, it didnt work!
Sadly docker-compose up doesn't allow to use the --no-cache flag so I had to rebuild using `docker-compose -f docker-compose-build.yml build --no-cache` which in the end worked out.
