### ISSUE TITLE
Duplicated CSRF_WHITELIST check in env.data.sh

### ISSUE THREAD

**Issue by zachsa** [kartoza/docker-geoserver#415]
Hi,

Thank you for such a comprehensive Docker image! I'm super new to GeoServer, and so far especially appreciate being able to configure the username/password at container run time.

Going through the process of using this Docker image I noticed a repeated line of code:

```sh
if [ -z "${CSRF_WHITELIST}" ]; then
    CSRF_WHITELIST=
fi
```

https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L277-L279
https://github.com/kartoza/docker-geoserver/blob/master/scripts/env-data.sh#L289-L291

Doesn't look intentional, so I thought it worth flagging in case it is not!

Zach

**Comment by NyakudyaA** [comment]
Thanks, will fix in an upcoming PR

**Comment by NyakudyaA** [comment]
fixed in develop and master
