### ISSUE TITLE
Is it possible to specify a non-standard PostgreSQL port for the JNDI PostgreSQL connector?

### ISSUE THREAD

**Issue by zachsa** [kartoza/docker-geoserver#416]
Looking at the README.md: https://github.com/kartoza/docker-geoserver#activating-jndi-postgresql-connector, I see the following postgres connection settings

```
HOST=${POSTGRES_HOSTNAME}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASS=${POSTGRES_PASS}
```

Is there a way to specify a non-standard Postgres port?

**Comment by NyakudyaA** [comment]
You should be able to also specify the port according to https://github.com/kartoza/docker-geoserver/blob/master/build_data/context.xml#L23 . It's just not documented there

**Comment by zachsa** [comment]
Thank you
