### ISSUE TITLE
About libjpeg-turbo-plugin

### ISSUE THREAD

**Issue by curtis18** [kartoza/docker-geoserver#432]
While libjpeg-turbo-plugin is shipped, it seems the libjpeg-turbo library hasn't installed. Would you please help about it?

https://sourceforge.net/projects/libjpeg-turbo/files/2.1.3/

**Comment by NyakudyaA** [comment]
What version are you running.

**Comment by curtis18** [comment]
Thanks for your reply. I find the libjpeg-turbo finally at /opt/libjpeg-turbo finally.
