### ISSUE TITLE
GEOSERVER_ADMIN_USER has no effect

### ISSUE THREAD

**Issue by poperne** [kartoza/docker-geoserver#434]
Hello, 

Trying to change the admin username via environment variable has no effect, log in works only in case, when value GEOSERVER_ADMIN_USER is passed to the username field. 
users.xml in running container contains :
<img width="554" alt="image" src="https://user-images.githubusercontent.com/91725293/180439594-d85eb237-3de4-4071-85bc-aef5c5dfd9df.png">

Docker image version : kartoza/geoserver:2.21.0

UPDATE
The issue happens when the container is running with user geoserver, id 1000. When container is running under the root user, works as expected

**Comment by NyakudyaA** [comment]
does this happen only when you start the container or when updating the credentials?
