### ISSUE TITLE
datastore failes to load

### ISSUE THREAD

**Issue by npltr62** [kartoza/docker-geoserver#438]
`CONFIG` [org.geoserver] - Loaded style 'litho'
WARN   [org.geoserver] - Failed to load data store 'data_int'`
 I run this command `docker run -d -p 8600:8080 --name geoserverb --network net -e DB_BACKEND=POSTGRES -e HOST=db -e POSTGRES_PORT=5432 -e POSTGRES_DB=fdp49 -e POSTGRES_USER=postgres -e POSTGRES_PASS=postgres -e GEOSERVER_DATA_DIR=/opt/geoserver/data_dir -e EXISTING_DATA_DIR=false kartoza/geoserver:2.21.0`
the workspace and styles are loaded well, why datastores/layers didn't?

**Comment by NyakudyaA** [comment]
Where is the style `litho` coming from if you are using an empty data directory?

**Comment by npltr62** [comment]
It's just a question of permission of data_dir directory ...
thank's
