### ISSUE TITLE
geoserver, postgis connection error

### ISSUE THREAD

**Issue by swchoi1997** [kartoza/docker-geoserver#439]
#docker-compose version
version: "3"

volumes:
  db-backups:
  geoserver_data:
  geodb-data:
  pgadmin:
 
services:
  db: # service name
    image: kartoza/postgis:latest # 서비스 컨테이너 생성할 때 쓰일 이미지 이름(이름 포멧은 docker run과 같음)
    networks:
      - test_network
    volumes:
      - geodb-data:/var/lib/postgresql
    ports: # 서비스 컨테이너를 개방할 포트를 설정한다.
      - "25434:5432"
    environment: # docker run 의 --env, -e 옵션과 동일함, 서비스 컨테이너 네부에서 사용할 황경 변수를 지정하며 딕셔너리나 배열 형태
      - POSTGRES_DB=gis,gwc
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: always

  geoserver:
    image: kartoza/geoserver:2.19.0
    networks:
      - test_network
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    ports:
      - "8888:8080"
    restart: always
    environment:
      - POSTGRES_DB=gis,gwc
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  dbbackups:
    image: kartoza/pg-backup:latest
    networks:
      - test_network
    volumes:
      - db-backups:/backups
    environment:
      - DUMPPREFIX=PG_db
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=gis
    
    restart: always
    depends_on:
      - db
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - test_network
    restart: always
    depends_on:
      - db

networks:
  test_network:
    driver: bridge

my docker-compose.yml
----------------------------------------------------------------------------------------
when i make storage, error occupied

error message :
Error creating data store, check the parameters. Error message: Unable to obtain connection: Cannot create PoolableConnectionFactory (Connection to localhost:25434 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)

i don't know how to solve that :(

**Comment by NyakudyaA** [comment]
You should be using the following parameters
host=db
port=5432

Because you are connecting internally

**Comment by swchoi1997** [comment]
oh... thank you.. 
i must need more study for docker
