### ISSUE TITLE
Geoserver version 2.20.5 missing

### ISSUE THREAD

**Issue by osso-rkuper** [kartoza/docker-geoserver#440]
On Dockerhub the following images are available:
* 2.21.0
* 2.20.4
* 2.20.3
* 2.20.2

However Geoserver with the tag 2.20.5 seems to be missing.
Could this be added?

**Comment by osso-rkuper** [comment]
Additionaly I tried building the 2.20.5 locally from a clean git, but it complains about not being able to install the dependencies of libgdal26:

> The following packages have unmet dependencies:
 libgdal26 : Depends: libarmadillo9 (>= 1:9.200.7+dfsg) but it is not installable
             Depends: libcfitsio7 (>= 3.450~) but it is not installable
             Depends: libdap25 but it is not installable
             Depends: libjson-c3 (>= 0.11) but it is not installable
             Depends: libnetcdf13 (>= 1:4.0.0) but it is not installable
             Depends: libpoppler82 (>= 0.71.0) but it is not installable
             Depends: libqhull7 but it is not installable
E: Unable to correct problems, you have held broken packages.

The package depends on other packages that are not available in bullseye. On Buster it builds fine.
The not installable packages are caused by them being a newer version in Bullseye (example: libarmadillo9 is the newer version libarmadillo10 in Bullseye)

**Comment by NyakudyaA** [comment]
Will build and tag the image

**Comment by arvkonstantin** [comment]
> Additionaly I tried building the 2.20.5 locally from a clean git, but it complains about not being able to install the dependencies of libgdal26:
> 
> > The following packages have unmet dependencies:
> > libgdal26 : Depends: libarmadillo9 (>= 1:9.200.7+dfsg) but it is not installable
> > Depends: libcfitsio7 (>= 3.450~) but it is not installable
> > Depends: libdap25 but it is not installable
> > Depends: libjson-c3 (>= 0.11) but it is not installable
> > Depends: libnetcdf13 (>= 1:4.0.0) but it is not installable
> > Depends: libpoppler82 (>= 0.71.0) but it is not installable
> > Depends: libqhull7 but it is not installable
> > E: Unable to correct problems, you have held broken packages.
> 
> The package depends on other packages that are not available in bullseye. On Buster it builds fine. The not installable packages are caused by them being a newer version in Bullseye (example: libarmadillo9 is the newer version libarmadillo10 in Bullseye)

Hello, I have the same problem

**Comment by osso-rkuper** [comment]
> > Additionaly I tried building the 2.20.5 locally from a clean git, but it complains about not being able to install the dependencies of libgdal26:
> > > The following packages have unmet dependencies:
> > > libgdal26 : Depends: libarmadillo9 (>= 1:9.200.7+dfsg) but it is not installable
> > > Depends: libcfitsio7 (>= 3.450~) but it is not installable
> > > Depends: libdap25 but it is not installable
> > > Depends: libjson-c3 (>= 0.11) but it is not installable
> > > Depends: libnetcdf13 (>= 1:4.0.0) but it is not installable
> > > Depends: libpoppler82 (>= 0.71.0) but it is not installable
> > > Depends: libqhull7 but it is not installable
> > > E: Unable to correct problems, you have held broken packages.
> > 
> > 
> > The package depends on other packages that are not available in bullseye. On Buster it builds fine. The not installable packages are caused by them being a newer version in Bullseye (example: libarmadillo9 is the newer version libarmadillo10 in Bullseye)
> 
> Hello, I have the same problem

I did some further digging, the libgdal-java package in the PPA the Dockerfile uses depends on libgdal26, see: https://deb.meteo.guru/debian/dists/buster/main/binary-amd64/Packages
Bullseye doesn't have the libgdal26, it has the newer libgdal28 (https://packages.debian.org/bullseye/libgdal28) 
The old package depends on older libraries, which are also not available on Bullseye. 
The best fix for this would be to have a Bullseye build for libgdal-java with updated dependencies.

**Comment by NyakudyaA** [comment]
Unfortunately, Bullseye doesn't ship `libgdal-java` anymore, check https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947960 for reference. You might need to build with an older version or use the login in the develop to build with a new version of gdal >3 which has been supported but not officially before 2.21.0
