### ISSUE TITLE
How to track changes after 2.19.0, there are no branches or tags available

### ISSUE THREAD

**Issue by tlvu** [kartoza/docker-geoserver#441]
I would like to diff the exact code change between the releases and without any branches or tags, it is impossible to perform the diff. Ideally this should be tags and not branches because branches can change with time.

No branches after `2.19.0`:

![Screenshot 2022-08-11 at 19-28-10 Branches · kartoza_docker-geoserver](https://user-images.githubusercontent.com/11966697/184259062-509b8313-96b6-453b-9638-a53c36bb506d.png)

No tags for all releases:

![Screenshot 2022-08-11 at 19-28-44 Releases · kartoza_docker-geoserver](https://user-images.githubusercontent.com/11966697/184259144-f7b72034-63e2-47ea-b337-3483637d23dd.png)

**Comment by NyakudyaA** [comment]
Branches can become cumbersome to maintain as a release cycle can have more than 4 version I.e 2.21.0 to 2.21.5

I had stopped tagging them for this reason but going forward I will tag the release and when the PR for actions is merged it will build against master for a new release

**Comment by tlvu** [comment]
Thanks for tagging going forward for each release on DockerHub (example 2.21.0, 2.21.1, ...).  Will help a lot for "traceable release" and "reproducible science".  The tag has to be on the exact commit used to perform the release build on DockerHub.

If possible, could you also retrospectively tag the exact commit used to build the following existing releases on DockerHub: 2.19.0, 2.19.2, 2.20.0, 2.20.1, 2.20.2, 2.20.3, 2.20.4, 2.21.0, 2.21.1?

FYI, DockerHub can be setup to automatically trigger a build when it sees a new tag being pushed to Github so no manual build is required after you push a new tag.  This will ensure you never forget to tag since the tag is needed to trigger the release build on DockerHub.
