### ISSUE TITLE
Base Image update

### ISSUE THREAD

**Issue by Rainfords** [kartoza/docker-geoserver#444]
Hello,
What are the plans in updating the base image used in this project? `9.0-jdk11-openjdk-slim-bullseye` is over a year old now and has critical and high vulnerabilities  raise against it.

Base Image                                 Vulnerabilities  Severity
tomcat:9.0.65-jdk11-openjdk-slim-bullseye  46               1 critical, 2 high, 0 medium, 43 low

✗ High severity vulnerability found in libtirpc/libtirpc-common
  Description: Allocation of Resources Without Limits or Throttling
  Info: https://snyk.io/vuln/SNYK-DEBIAN11-LIBTIRPC-2959390
  Introduced through: libtirpc/libtirpc-common@1.3.1-1, adduser@3.118, libtirpc/libtirpc3@1.3.1-1
  From: libtirpc/libtirpc-common@1.3.1-1
  From: adduser@3.118 > shadow/passwd@1:4.8.1-1 > pam/libpam-modules@1.4.0-9+deb11u1 > libnsl/libnsl2@1.3.0-2 > libtirpc/libtirpc3@1.3.1-1 > libtirpc/libtirpc-common@1.3.1-1
  From: libtirpc/libtirpc3@1.3.1-1
  and 2 more...
  Image layer: Introduced by your base image (tomcat:9.0.65-jdk11-openjdk-slim-bullseye)
  Fixed in: 1.3.1-1+deb11u1

✗ High severity vulnerability found in gnutls28/libgnutls30
  Description: Double Free
  Info: https://snyk.io/vuln/SNYK-DEBIAN11-GNUTLS28-2964220
  Introduced through: gnutls28/libgnutls30@3.7.1-5+deb11u1, apt@2.2.4
  From: gnutls28/libgnutls30@3.7.1-5+deb11u1
  From: apt@2.2.4 > gnutls28/libgnutls30@3.7.1-5+deb11u1
  Image layer: Introduced by your base image (tomcat:9.0.65-jdk11-openjdk-slim-bullseye)
  Fixed in: 3.7.1-5+deb11u2

✗ Critical severity vulnerability found in zlib/zlib1g
  Description: Out-of-bounds Write
  Info: https://snyk.io/vuln/SNYK-DEBIAN11-ZLIB-2976151
  Introduced through: meta-common-packages@meta
  From: meta-common-packages@meta > zlib/zlib1g@1:1.2.11.dfsg-2+deb11u1
  Image layer: Introduced by your base image (tomcat:9.0.65-jdk11-openjdk-slim-bullseye)

**Comment by NyakudyaA** [comment]
You are welcome to do a PR with an upgrade base image. Please check the supported tomcat version https://docs.geoserver.org/master/en/user/installation/war.html#installation-war
and also consider the issue of libgdal-java which is no longer being built but is required for geoserver gdal plugins 

Also check https://github.com/kartoza/docker-geoserver/issues/301
