### ISSUE TITLE
build.sh break the Dockerfile

### ISSUE THREAD

**Issue by vipcxj** [kartoza/docker-geoserver#46]
[This line](https://github.com/kartoza/docker-geoserver/blob/master/build.sh#L11) break the Dockerfile. Because `${OLD_MAJOR}`, `${OLD_MINOR}` and `${OLD_BUGFIX}` are all empty, this command become `sed -i "s/../13.2.0/g" Dockerfile`.

**Comment by NyakudyaA** [comment]
closed via https://github.com/kartoza/docker-geoserver/commit/ca26741f4985b78fe1a9d27654f121a90878f77e
