### ISSUE TITLE
jdbc-image-mosaic-plugin for GeoServer 2.21 or 2.20

### ISSUE THREAD

**Issue by diegom22** [kartoza/docker-geoserver#461]
Looking for the jdb-image-mosaic-plugin for Geoserver 2.21 or 2.20

**Comment by NyakudyaA** [comment]
If you do not find the plugin you should be able to activate it using the env variable
```
STABLE_EXTENSIONS=name-of-plugin
```
provided the plugin is available from https://sourceforge.net/projects/geoserver/files/GeoServer/2.21.2/extensions/ 
or the 
```
COMMUNITY_EXTENSIONS=name-of-plugin
```
https://build.geoserver.org/geoserver/2.21.x/community-latest/

**Comment by diegom22** [comment]
The plugin jdbc-image-mosaic-plugin does not exist in the extensions folders provided. Has it been upgraded or grouped into another plugin? if so what is the name of the new plugin?

**Comment by NyakudyaA** [comment]
It looks like that plugin might have been dropped since it was a community-maintained plugin. Please check the changelog for 2.21.x series or better ask in the geoserver issue tracker
