### ISSUE TITLE
CORS error on browser but not on postman

### ISSUE THREAD

**Issue by abbasogaji** [kartoza/docker-geoserver#464]
When running the docker container on M1 mac, Im unable make API requests from my browser, while this is possible on postman, i even tried running the geoserver behind a reverse proxy with all the required CORS headers, it still doesnt work, i know this enabled by default but even did a double check to make sure the CORS filters are present in the web.xml file within the docker container, see screenshot below:

Device info:

Apple M1 pro,
16GB
OS: ventura 13.0.1

Browser info: Chromonium (Electron App)

<img width="1330" alt="Screenshot 2022-12-12 at 3 37 11 PM" src="https://user-images.githubusercontent.com/34817010/207072749-41407f68-8db3-4a46-94dc-bf9b4cca814a.png">

**Comment by NyakudyaA** [comment]
Please be descriptive of the problem. In cases like this, you will not get any assistance at all. This is a community service and any well described problem will attract answers very quickly and also other users can learn from it

**Comment by abbasogaji** [comment]
@NyakudyaA my bad, i have updated the description now

**Comment by NyakudyaA** [comment]
Have you tried to set `CSRF_WHITELIST`

https://docs.geoserver.org/stable/en/user/security/webadmin/csrf.html

**Comment by krishnaglodha** [comment]
Can you please share the Docker-compose file snapshot ?

**Comment by NyakudyaA** [comment]
Lack of feedback
