### ISSUE TITLE
Invalid username/password combination

### ISSUE THREAD

**Issue by AnythingLinux** [kartoza/docker-geoserver#472]
Hello I have update .env file geoserver user and password but when i try to login it says Invalid username/password combination

![Screenshot from 2023-01-19 05-08-22](https://user-images.githubusercontent.com/1058663/213324267-a4a1daf0-335f-4995-9f67-db2148ea721c.png)

**Comment by VP2405** [comment]
Same problem here. We tried to set GEOSERVER_ADMIN_PASSWORD and GEOSERVER_ADMIN_USER env variables, in /settings we see that the files .default_admin_pass.txt and .default_admin_user.txt contain the right values we set, but when doing the authentication, it does not succeed.
We're using the 2.22.0 version.

**Comment by colkassad** [comment]
I'm having the same issue.

**Comment by NyakudyaA** [comment]
Are you using docker volume or host mounted data directory.

**Comment by AnythingLinux** [comment]
> host mounted data directory.

host mounted data directory

**Comment by NyakudyaA** [comment]
What are the permissions on your data directory?.
You need to make sure that the local volume is owned by you.   Alternatively, you can rest it to the default ones(admin/geoserver) by running the following command

```
docker exec container-name cp /usr/local/tomcat/security/usergroup/default/users.xml /opt/geoserver/data_dir/security/usergroup/default/
```
assuming the data dir path is `/opt/geoserver/data_dir`
