### ISSUE TITLE
DiskQuota Postgres connection configuration through rest API

### ISSUE THREAD

**Issue by Martenz** [kartoza/docker-geoserver#475]
From main readme I see it is possible to Enable disk quota storage in PostgreSQL backend, but is it possible also to configure the connection to the db though rest API or env variables? Or we should configure it through GUI ?

thanks

**Comment by NyakudyaA** [comment]
You can define the connection through env variables. If you also want to do it through the REST API and ignore the env variables you will need to check what the Reast documentation says.

I have always thought we could add an entrypoint script like what the PostgreSQL container does. Maybe in future iterations this will be coming

**Comment by Martenz** [comment]
Using the Rest Api it seems possible only to configure H2 parameters, if I set to JDBC there is no way to set also the Postgres connection. 
From the Geoserver-data-dir I see, when configuring the JDBC connection for db disk quota setup, that geoserver creates a geowebcache-diskquota-jdbc.xml with the connection parameters.

Do you mean that through env variables is possible to set this connection and have JDBC disk quota store set ?

And not related to this topic.. it would be nice to have also the "Enable direct integration with GeoServer WMS" option through env variables to enable it automatically. Maybe I will open an other issue for this, is it fine?

thanks a lot for your time.

**Comment by NyakudyaA** [comment]
```
docker run -d -p 8600:8080 --name geoserver --link db:db -e DB_BACKEND=POSTGRES -e HOST=db -e POSTGRES_PORT=5432 -e POSTGRES_DB=gis -e POSTGRES_USER=docker -e POSTGRES_PASS=docker kartoza/geoserver:2.18.0
```
Will create that file geowebcache-diskquota-jdbc.xml that will be read on startup configuring diskquota. Login is available from https://github.com/kartoza/docker-geoserver/blob/develop/scripts/start.sh#L42

**Comment by NyakudyaA** [comment]
> Using the Rest Api it seems possible only to configure H2 parameters, if I set to JDBC there is no way to set also the Postgres connection. From the Geoserver-data-dir I see, when configuring the JDBC connection for db disk quota setup, that geoserver creates a geowebcache-diskquota-jdbc.xml with the connection parameters.
> 
> Do you mean that through env variables is possible to set this connection and have JDBC disk quota store set ?
> 
> And not related to this topic.. it would be nice to have also the "Enable direct integration with GeoServer WMS" option through env variables to enable it automatically. Maybe I will open an other issue for this, is it fine?

Yes you can open an issue request. Isn't that info written in `global.xml`, Don't we have logic to pass a custom `global.xml`
> 
> thanks a lot for your time.

**Comment by Martenz** [comment]
> ```
> docker run -d -p 8600:8080 --name geoserver --link db:db -e DB_BACKEND=POSTGRES -e HOST=db -e POSTGRES_PORT=5432 -e POSTGRES_DB=gis -e POSTGRES_USER=docker -e POSTGRES_PASS=docker kartoza/geoserver:2.18.0
> ```
> 
> 
>     
>  
>   
> 
> Will create that file geowebcache-diskquota-jdbc.xml that will be read on startup configuring diskquota. Login is available from https://github.com/kartoza/docker-geoserver/blob/develop/scripts/start.sh#L42

Great! will test this in local with docker-compose adding those env variables as far containers are already linked.

I will open the other ticket, it seems it is not in global.xml but in gwc-gs.xml the true/false for the WMS integration.

thanks again very helpful
