### ISSUE TITLE
Disk Quota Postgres backend specify schema

### ISSUE THREAD

**Issue by Martenz** [kartoza/docker-geoserver#480]
### Feature description

Add **currentSchema=myschema** parameter to jdbc connection to use specific schema on Postgres db to store disk quota tiles metadata.

**Comment by NyakudyaA** [comment]
@Martenz I suggest you take a stab at this, Basically, you need to adjust  https://github.com/kartoza/docker-geoserver/blob/develop/build_data/geowebcache-diskquota-jdbc.xml#L5
and add a default env variable to specify a schema in `env-data.sh`. The default should be `public`

**Comment by Martenz** [comment]
I build a new image with the new env data. 
The configuration is correctly saved to geowebcache-diskquota-jdbc.xml but not applied.

anyhow if I try to connect directly from GUI I get this error:

Failure occurred while saving the JDBC configurationPreparedStatementCallback; bad SQL grammar [SELECT DISTINCT(LAYER_NAME) FROM TILESET WHERE KEY <> '___GLOBAL_QUOTA___']; nested exception is org.postgresql.util.PSQLException: ERROR: relation "tileset" does not exist Position: 34 (see the logs for a full stack trace)

any hint?

thanks

**Comment by Martenz** [comment]
it seems related to missing tables, so it seems that if I just add only the env variable and the default value the start scripts create only the connection but does not initialize the schema creating the two needed tables.

I tried creating manually the two tables in the schema and with a docker-compose up down and up now it works.

Any idea where I can check when and how to create the two tables for the store e of tile caches?

thanks again for your time

**Comment by NyakudyaA** [comment]
Looks like the Jdbc might be defaulting to the public schema(creation table), if this is so then this is an upstream problem that will need to be reported in GeoServer.

**Comment by Martenz** [comment]
Thanks will report, if fixed will push the new env variable replacement.

**Comment by NyakudyaA** [comment]
Does it work if you specify the schema as public with the new environment variable. If so then maybe you can do the pull request so long with a default schema being public
