### ISSUE TITLE
Consider splitting README into multiple docs

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-geoserver#483]
### Feature description

The readme has become quite long and will continue to grow, let's consider splitting it and keep the main features here and flesh out most of the login using GitHub wiki pages.

I think advanced features and best practices may be moved to wiki pages or basically have the following

* README.md
* docs/guide.md (Basics & Advanced Features)
* docs/best-practices.md
etc

**Comment by krishnaglodha** [comment]
Hi @NyakudyaA , I would be happy to take this issue. I'm proposing creating a doc website  such as https://dive.pygeoapi.io/ , which can have sections of each use case, and it can be kept open end so we can also add more settings and use cases in future.

**Comment by NyakudyaA** [comment]
@krishnaglodha Thanks a lot, you can go ahead

**Comment by krishnaglodha** [comment]
I'll create basic structure, and add here

**Comment by krishnaglodha** [comment]
Hi @NyakudyaA  please check https://github.com/kartoza/docker-geoserver/pull/485
