### ISSUE TITLE
New built images do not start: java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO

### ISSUE THREAD

**Issue by mumeraltaf** [kartoza/docker-geoserver#486]
### What is the bug or the crash?

Hello,

I have been trying to figure this one out since couple of days, new builds on existing released tags (i.e. 2.21.2, 2.21.1 etc) are not starting up correctly any more.

- Builds done couple of months ago using same tags work OK, i see that most recent update of kartoza images on dockerhub was also couple of months ago
- Kartoza images from DockerHub work ok too
- But any new builds done now result in an image that produces following exception at container start:

> 04 Feb 06:09:27 WARN   [support.XmlWebApplicationContext] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geoServer' defined in URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-main-2.21.2.jar!/applicationContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.config.impl.GeoServerImpl]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO

04 Feb 06:09:27 WARN   [support.DisposableBeanAdapter] - Invocation of destroy method failed on bean with name 'geoServerLoader': java.lang.NullPointerException

04 Feb 06:09:27 ERROR  [context.ContextLoader] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geoServer' defined in URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-main-2.21.2.jar!/applicationContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.geoserver.config.impl.GeoServerImpl]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO

### Steps to reproduce the issue

`git clone https://github.com/kartoza/docker-geoserver.git`
`cd docker-geoserver`
`git checkout v2.21.1`
`docker build -t geo/geoserver:1 .`

now use any docker-compose to start with postgis running along.

The logs show the exception above and GeoServer Fails to start.

Tried on x86 public cloud (AMD EPYC 7702 64-Core Processor), on both docker and containerd (rke2).
Ubuntu 22.04 LTS (Jammy) amd64

Can someone else please verify that new builds work for them and its not me doing something incorrect.

### Versions

2.22.0, 2.21.2, 2.21.1 

### Additional context

Here is simple GitHub action to build image:
[Build action 2.21.1](https://github.com/mumeraltaf/geoserver-build/blob/main/.github/workflows/build-geoserver.yaml)

The resulting image is here on DockerHub:
umeraltaf/geoserver:2.21.1-37c550e

**Comment by NyakudyaA** [comment]
Can you try to build using 
```
docker compose -f docker-compose-build.yml up -d --build
```

**Comment by mumeraltaf** [comment]
Unfortunately, same result if built through docker-compose-build too.

**Comment by mumeraltaf** [comment]
On a little further experimentation this issue is similar to #436 and removing `gdal` plugin install from `setup.sh` lets the GeoServer to start correctly. So I think the `gdal` issue is not only constrained to `arm64` but extends to `amd64` too.

Whats a bit puzzling is that for older tags (2.21.*) that used to build and run fine now the plugin does not start.

**Comment by NyakudyaA** [comment]
I think the issue could be because of `https://deb.meteo.guru/velivole-keyring.asc` where we try to install gdal3 inside the container. Can you try the normal gdal install.

https://github.com/mmomtchev/debbuild-gdal

**Comment by mumeraltaf** [comment]
@NyakudyaA Yes you are right, GDAL3 is not being installed anymore. Here are versions of gdal reported by images:

`gdalinfo --version`
2.22.0 - Current develop, with repo from `https://deb.meteo.guru/velivole-keyring.asc`
GDAL 2.4.0, released 2018/12/14

Current Develop - Buster sources without setting the custom repo for `https://deb.meteo.guru/velivole-keyring.asc` :
GDAL 2.4.0, released 2018/12/14

2.22.0 Published Image on DockerHub:
GDAL 3.2.2, released 2021/03/05


Let me see if I can find a way to get GDAL3 installed, seems like we would have to build it.

**Comment by mumeraltaf** [comment]
I found no straight forward way to install gdal v3 that is both consistent with debian and ubuntu base images.
Even when installing gda3l from ubuntu specific [ubuntugis-unstable](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable), it results in following mismatched versions:
`libgdal-java`: 3.0.4+dfsg-1
`gdal-bin`: 3.4.3+dfsg-1
This setup also does not start GeoServer (with gdal plugin)


Building gdal from source is a chore in itself, (takes >30mins) so I am not sure if this falls under scope of this project.

For our own use we do not use GDAL plugin in geoserver so we will remove it from our internal builds. But I will be happy to help in this repo if needed.

**Comment by isuftin** [comment]
Looks like https://deb.meteo.guru/ is completely emptied out, only the directory structure is left.

@mumeraltaf  do you have a snippet for how you're building the correct version of gdal from source?

**Comment by NyakudyaA** [comment]
I have opened an issue https://github.com/mmomtchev/debbuild-gdal/issues/1, easier for him to fix it than building gdal. It's a pain to clone and build especially now with libgdal-java being removed completely in higher versions
