### ISSUE TITLE
Unable to build the docker container

### ISSUE THREAD

**Issue by om-henners** [kartoza/docker-geoserver#487]
### What is the bug or the crash?

Currently trying to modify the container by running an apt update and install fails, likely due to https://github.com/mmomtchev/debbuild-gdal/issues/1

### Steps to reproduce the issue

Create a Dockerfile containing:

```
FROM kartoza/geoserver:latest AS sshd

USER root

RUN apt-get update \
    && apt-get -y install rsync \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

and run. This fails at the `apt-get update` step with 

```
#0 3.985 E: The repository 'https://deb.meteo.guru/debian buster Release' does not have a Release file.
```

### Versions

All versions

**Comment by isuftin** [comment]
Looks like a duplicate of https://github.com/kartoza/docker-geoserver/issues/486

**Comment by om-henners** [comment]
Yeah, definitely a duplicate of https://github.com/kartoza/docker-geoserver/issues/486

That said, for anyone building from an existing image from dockerhub, the solution is to remove the offending apt repo before applying apt uptdate:

```
RUN rm /etc/apt/sources.list.d/meteo.guru.list \
    && apt-get update \
    && apt-get -y install \
    ...
```
