### ISSUE TITLE
Generate 2.21.3 docker image

### ISSUE THREAD

**Issue by SylvainVISSIERE-GUERINET** [kartoza/docker-geoserver#489]
### Feature description

Hi,

i'm using your docker image to set up a geoserver and i would like to know if you have planned to release a 2.21.3 tag.

Release note: https://geoserver.org/announcements/2022/12/28/geoserver-2-21-3-released.html

Thanks.

**Comment by NyakudyaA** [comment]
I will attend to this and push it

**Comment by krishnaglodha** [comment]
Should I work on it?

**Comment by SylvainVISSIERE-GUERINET** [comment]
thanks

**Comment by krishnaglodha** [comment]
hi @NyakudyaA , can you please recommend good starting point for me to work on this?

**Comment by NyakudyaA** [comment]
@krishnaglodha You will need to do the following
* Change the version in .env to reference the version you want
* Remove `gdal-bin` from line https://github.com/kartoza/docker-geoserver/blob/develop/Dockerfile#L21
* Adjust line https://github.com/kartoza/docker-geoserver/blob/develop/Dockerfile#L23 to add the following logic
```
if [ `wget -S --spider https://deb.meteo.guru/velivole-keyring.asc  2>&1 | grep 'HTTP/1.1 200 OK'` ]; then
	curl https://deb.meteo.guru/velivole-keyring.asc |  apt-key add - \
    && echo "deb https://deb.meteo.guru/debian buster main" > /etc/apt/sources.list.d/meteo.guru.list \
    && apt-get update \
    && apt-get -y --no-install-recommends install gdal-bin libgdal-java
else
   apt-get -y --no-install-recommends install gdal-bin libgdal-java
 fi
```
* Check if the build environment works, then do a PR with these changes

**Comment by NyakudyaA** [comment]
@krishnaglodha I merged https://github.com/kartoza/docker-geoserver/pull/493 and pushed a new image. @SylvainVISSIERE-GUERINET Please checkout in dockerhub. The image is based on the latest PR

**Comment by SylvainVISSIERE-GUERINET** [comment]
just saw it on docker hub thanks :)
