### ISSUE TITLE
Docker Hub Images tag release

### ISSUE THREAD

**Issue by Martenz** [kartoza/docker-geoserver#490]
### Feature description

How often images are build and pushed to the docker hub? 
I'm using latest 2.22.0 with latest development from a local build form the develop branch.
I checked on the docker hub and I see the last image pushed is 3 months old.

Thanks,

Martino

**Comment by NyakudyaA** [comment]
@Martenz Unfortunately we haven't incorporated workflows to build the images. If you would like to give this a go you are welcome so that we can automate the build process.  We currently have https://github.com/kartoza/docker-geoserver/pull/349 which we haven't tested vigorously

**Comment by NyakudyaA** [comment]
Published new images
