### ISSUE TITLE
Tag specifically focusing on `arch` architecture 

### ISSUE THREAD

**Issue by krishnaglodha** [kartoza/docker-geoserver#492]
### Feature description

It is difficult for new user to setup docker-geoserver for arch architecture. Should we have tag for it specifically for this use case ?

**Comment by krishnaglodha** [comment]
I can work on it if needed

**Comment by NyakudyaA** [comment]
Yes, you can, Won't a GitHub workflow cater for this if setup to run properly like  https://github.com/kartoza/docker-postgis/blob/develop/.github/workflows/deploy-image.yaml#L67

**Comment by krishnaglodha** [comment]
@NyakudyaA  Unfortunately not, because arch image also needs other fixes https://github.com/kartoza/docker-geoserver#additional-notes-for-macos-m1-chip

**Comment by NyakudyaA** [comment]
If anyone has an arch / arm environment I can test this

**Comment by krishnaglodha** [comment]
Hi, I'll try in my M1 and keep you posted

**Comment by NyakudyaA** [comment]
@krishnaglodha I see they are base images tagged as m1 in the tomcat container registry. Please try those ones first i.e https://hub.docker.com/_/tomcat/tags?page=1&name=M1-jdk11

**Comment by NyakudyaA** [comment]
@krishnaglodha Is this still an issue ?

**Comment by NyakudyaA** [comment]
Open if still needed
