### ISSUE TITLE
New versions needed for GeoServer OGC Filter Injection Patch

### ISSUE THREAD

**Issue by sharon-tickell** [kartoza/docker-geoserver#496]
### Feature description

Earlier this week, the GeoServer maintainers announced that a vulnerability has been found in recent versions of GeoServer that allows SQL Injection via OGC Filter and Function expressions.   See: https://geoserver.org/vulnerability/2023/02/20/ogc-filter-injection.html

They have patched the vulnerability in several newly-released GeoServer versions:

- [x]  [GeoServer 2.22.2](https://geoserver.org/announcements/2023/02/20/geoserver-2-22-2-released.html) stable release
- [x]  [GeoServer 2.21.4](https://geoserver.org/announcements/2023/02/20/geoserver-2-21-4-released.html) maintenance
- [x]  [GeoServer 2.20.7](https://geoserver.org/announcements/2023/02/20/geoserver-2-20-7-released.html)
- [x]  [GeoServer 2.19.7](https://geoserver.org/announcements/2023/02/20/geoserver-2-19-7-released.html)
- [x]  [GeoServer 2.18.7](https://geoserver.org/announcements/2023/02/20/geoserver-2-18-7-released.html)

But there are no tags for any of these versions yet available from https://hub.docker.com/r/kartoza/geoserver

Some new builds to make these patched GeoServer releases availale would be very welcome

**Comment by NyakudyaA** [comment]
@sharon-tickell Will attend to it over the weekend and update the versions

**Comment by NyakudyaA** [comment]
All images are published now

**Comment by sharon-tickell** [comment]
Excellent - thanks heaps!   Both the published image and your speedy response are much appreciated
