### ISSUE TITLE
Not able to login after starting geoserver with minimal commands

### ISSUE THREAD

**Issue by krishnaglodha** [kartoza/docker-geoserver#502]
### What is the bug or the crash?

I'm trying to run `docker run  -p 8080:8080 kartoza/geoserver` using which I'm able to run geoserver but not sure what should I use as default username password.

So far I have tried 

username - admin, kartoza
password - geoserver, myawesomegeoserver 

combinations of these usernames and passwords. 

We need to also mention in documentation regarding the same 

### Steps to reproduce the issue

1.  Run `docker run  -p 8080:8080 kartoza/geoserver` 
2. Go to http://localhost:8080/geoserver/we
3. Enter login and password

### Versions

Geoserver 2.22.2

**Comment by NyakudyaA** [comment]
It's always advisable to pass a password variable the docs mention the following 
```

The username and password are reinitialized each time the container starts. If you do not pass the env variables GEOSERVER_ADMIN_PASSWORD the container will generate a new password which is visible in the startup logs.
```

**Comment by krishnaglodha** [comment]
Hi @NyakudyaA where can I get the startup logs?

**Comment by NyakudyaA** [comment]
`docker logs -f name_of_container`

**Comment by krishnaglodha** [comment]
Hi @NyakudyaA , I checked logs, but where do I see password? and username 
I only see password for tomcat
<img width="564" alt="Screenshot 2023-03-04 at 9 31 00 PM" src="https://user-images.githubusercontent.com/47075664/222916166-d77f7fed-e301-4d78-b2a9-5b88af1c9820.png">

**Comment by NyakudyaA** [comment]
Can you check inside the container `cat /settings/.default_admin_pass.txt`

**Comment by krishnaglodha** [comment]
No luck 
<img width="1167" alt="Screenshot 2023-03-09 at 11 39 44 AM" src="https://user-images.githubusercontent.com/47075664/223935449-cf5a1899-d62c-425d-8095-cb8072a1651e.png">

**Comment by NyakudyaA** [comment]
@krishnaglodha I have merged a PR that solves this, try building and test

**Comment by krishnaglodha** [comment]
DO you think we should keep default `admin` and `geoserver` as credentials ?

**Comment by NyakudyaA** [comment]
`admin` is fine but `geoserver` is never passed/used. If you do not pass any env, a default random password is generated

**Comment by quizz0n** [comment]
Confirm this issue even when passing the env variable `GEOSERVER_ADMIN_PASSWORD`.
The issue occurs on pretty much all versions above 2.19.2.
The command that I've been testing with is:
`docker run --name geoserver -e PKCS12_PASSWORD=geoserver -e JKS_KEY_PASSWORD=geoserver -e JKS_STORE_PASSWORD=geoserver -e SSL=true -e GEOSERVER_ADMIN_PASSWORD=password -p 443:8443 -d kartoza/geoserver:2.22.2`
```
cat /settings/.default_admin_pass.txt
password
```

**Comment by NyakudyaA** [comment]
Can you please build locally and confirm if it works, I will push new updates if you confirm. I fixed this issue. Can you please add a volume to the request and it should work
```
docker volume create geoserver
docker run --name geoserver -e PKCS12_PASSWORD=geoserver -e JKS_KEY_PASSWORD=geoserver -e JKS_STORE_PASSWORD=geoserver -e SSL=true -e GEOSERVER_ADMIN_PASSWORD=password -p 443:8443 -d -v geoserver:/opt/geoserver/data_dir kartoza/geoserver:2.22.2
```

**Comment by quizz0n** [comment]
Yes, building it works. Thanks!
