### ISSUE TITLE
Unable to download missing stable plugins in 2.22.2

### ISSUE THREAD

**Issue by tlvu** [kartoza/docker-geoserver#508]
### What is the bug or the crash?

csw-iso and metadata plugins moved from community to stable but is not yet in `stable_plugins.txt`.

So they should be downloaded on the fly when Geoserver starts, but have this error instead:
```
Plugin URL does not exist::  /2.22.2/extensions/geoserver-2.22.2-csw-iso-plugin.zip                                                                                                     
 csw-iso-plugin extension will not be installed because it is not available                                                                                           
Plugin URL does not exist::  /2.22.2/extensions/geoserver-2.22.2-metadata-plugin.zip                                                                                         
 metadata-plugin extension will not be installed because it is not available  
```

### Steps to reproduce the issue

Starts the docker image with those plugins enabled in `GEOSERVER_STABLE_EXTENSIONS` as in https://github.com/bird-house/birdhouse-deploy-ouranos/blob/a6886186fad8d8428160a31abd3e86248de83cb4/ouranos-config/docker-compose-extra.yml#L38

### Versions

2.22.2

### Additional context

Found in https://github.com/bird-house/birdhouse-deploy-ouranos/pull/20

**Comment by tlvu** [comment]
I think it's because `STABLE_PLUGIN_BASE_URL` in `start.sh` is not defined, see https://github.com/kartoza/docker-geoserver/blob/3e149e7f0c9947d3bdfaad2063f8190d383ff70b/scripts/start.sh#L85

**Comment by NyakudyaA** [comment]
It is defined as an arg in https://github.com/kartoza/docker-geoserver/blob/develop/Dockerfile#L13, maybe the issue is that `ARG` are not available in the context on entry point. If so we need to either export the arg like in https://github.com/kartoza/docker-geoserver/blob/develop/Dockerfile#L56 and then use it like in https://github.com/kartoza/docker-geoserver/blob/develop/scripts/setup.sh#L8

**Comment by tlvu** [comment]
Thanks for the fix.  Could the 2 missing plugins be added to `stable_plugins.txt` and removed from `community_plugins.txt`.

They are in "stable" now:
https://docs.geoserver.org/stable/en/user/extensions/csw-iso/index.html
https://docs.geoserver.org/stable/en/user/extensions/metadata/index.html

**Comment by NyakudyaA** [comment]
Yes, you can PR that. Ideally in future it would be nice to parse the html page to get the list of plugins so that we can always get the latest
