### ISSUE TITLE
Geoserver startup is significantly slower due to chown of GEOSERVER_DATA_DIR and GEOWEBCACHE_CACHE_DIR

### ISSUE THREAD

**Issue by tlvu** [kartoza/docker-geoserver#515]
### What is the bug or the crash?

This line https://github.com/kartoza/docker-geoserver/blob/b8d43882c674c3c1a9569d483f00e546e2895654/scripts/entrypoint.sh#L84-L88 makes Geoserver startup significantly slower for us because our `GEOSERVER_DATA_DIR` is 229 GB and `GEOWEBCACHE_CACHE_DIR` is under `GEOSERVER_DATA_DIR` which basically make it `chown` twice !

Found when upgrading from 2.19.0 to 2.22.2.  That new `chown` was introduced somewhere in 2.21.x I believe.

Please make it optional to `chown` `GEOSERVER_DATA_DIR` and `GEOWEBCACHE_CACHE_DIR`.  

Allow toggle env var like `CHOWN_DATA_DIR=false` and `CHOWN_CACHE_DIR=false`, like `EXISTING_DATA_DIR=false` would be great.

### Steps to reproduce the issue

Have a gigantic `GEOSERVER_DATA_DIR`, see all Geoserver configs in our PR https://github.com/bird-house/birdhouse-deploy/pull/307.

### Versions

2.22.2

**Comment by NyakudyaA** [comment]
I think we need a way to test if GWC is inside the data directory like 
```
case "${GEOWEBCACHE_CACHE_DIR}" in
        ${GEOSERVER_DATA_DIR}/*)
```
then chown once.

As for the flag, how would it still ensure that the correct folder permissions are preserved ?. Remember you are now able to pass your uid to preserve local folder permissions inside the data directory

**Comment by tlvu** [comment]
> Remember you are now able to pass your uid to preserve local folder permissions inside the data directory

I would assume this would cause problem on the first run only.  As long as the uid do not change after the first run, we do not need to always `chown` every time we start Geoserver.

We have been using your Geoserver image since 2.9.3, thanks for the great image by the way.  We have never encounter ownership issues, except at the big upgrade from 2.9.3 to 2.19.0.  We had to do this `chown` once and then that's it.  New files created by Geoserser should already have the proper ownership so no need to `chown` again.

So it's not about `chown` twice or once, it's about not `chown` at all.  So by default, we can continue to `chown` at each startup but please allow a toogle to opt-out.  Of course users who opt-out is responsible to deal with ownership permissions themselves.

**Comment by NyakudyaA** [comment]
I have got a much more elegant solution that I am going to implement

1. There will be folders that are shown once i.e CATALINA_HOME
2. Chown will still happen for the GeoServer data dir and GWC but as a once-off and on a successive restart this will check if chown has already run and skip the chown unless the ownership of the fils has changed

I will investigate this togle behaviour

**Comment by NyakudyaA** [comment]
@tlvu Can you test the PR and see if it resolves the issue for you
