### ISSUE TITLE
s3.properties default file is not copied into the build output

### ISSUE THREAD

**Issue by Kilowhisky** [kartoza/docker-geoserver#519]
### What is the bug or the crash?

```
10 Apr 22:53:19 WARN   [gce.imagepyramid] - it.geosolutions.imageioimpl.plugins.cog.CogSourceSPIProvider@3e5df13b
--
10-Apr-2023 22:53:19.092 SEVERE [http-nio-8080-exec-8] org.geotools.s3.geotiff.S3GeoTiffFormat.<init> Properties are missing! The system property 's3.properties.location' should be set and contain the path to the s3.properties file.
```

### Steps to reproduce the issue

1. Install the following community extensions `s3-geotiff-plugin` , `cog-plugin`
2. Follow this tutorial: https://docs.geoserver.org/latest/en/user/community/cog/mosaic.html

### Versions

2.22.2

### Additional context

Looks like s3 properties needs to be setup from the get go. 
See this answer as to where the s3 properties file needs to be referenced. 

https://gis.stackexchange.com/questions/310436/geoserver-s3-geotiff-module-with-custom-s3-provider-fails

**Comment by NyakudyaA** [comment]
This was deliberately removed because the s3 extension is no longer being maintained https://gis.stackexchange.com/questions/442695/s3-support-for-geotiff-vs-cog-cloud-optimized-geotiff-support-geoserver-co

However I see no reason no to add the logic back again as long as the responsibility of use lies with the end user

https://github.com/kartoza/docker-geoserver/blob/2.18.0/scripts/functions.sh#L87

**Comment by Kilowhisky** [comment]
AFIK the tutorial linked utilized the COG plugin. I just notated the other one as that’s also currently installed. I’ll try removing the community one.

**Comment by Kilowhisky** [comment]
I dumped the `s3-geotiff-plugin` and was still able to reproduce the issue.

**Comment by NyakudyaA** [comment]
Link for the tutorial?

**Comment by NyakudyaA** [comment]
@Kilowhisky You might need to add https://github.com/kartoza/docker-geoserver/blob/2.19.0/scripts/functions.sh#LL86C1-L94C2
https://github.com/kartoza/docker-geoserver/blob/2.19.0/scripts/start.sh#L71 and https://github.com/kartoza/docker-geoserver/blob/2.19.0/scripts/entrypoint.sh#L24. if I have time I will test this and add to the image

**Comment by NyakudyaA** [comment]
This is fixed
