### ISSUE TITLE
the GWC configuration seems to be out of synch

### ISSUE THREAD

**Issue by dgtery** [kartoza/docker-geoserver#520]
### What is the bug or the crash?

400: Could not locate a layer or layer group with id LayerInfoImpl--67903876:18769c833b8:-4ec8 within GeoServer configuration, the GWC configuration seems to be out of synch

### Steps to reproduce the issue

1. Publish PBF format services, which can be accessed normally；
2. Close the geoserver admin website；
3. After 30 minutes，visit page xxx/geoserver/gwc/service/tms/1.0.0， Obtaining this error message；
4. At this time, the service in the application cannot load normally, and the HTTP request is the same error message；
5. Log in to the geoserver admin website，visit page “xxx/geoserver/web/wicket/bookmarkable/org.geoserver.gwc.web.layer.CachedLayersPage?8&filter=false” again；
6. the service in the application can load normally

### Versions

GeoServer Version
2.23.0
Git 版本
afef4aab83639a1af6dd79b122c7e70277d9f8b0
构建日期
04-Apr-2023 06:16
GeoTools 版本
29.0 (rev 76b6ac20cb7579da3a4c3f88b574e29aa1db80c2)
GeoWebCache 版本
1.23.0 (rev 1.23.x/437ba9ba8468c6431945e3e988a330eb35012bee)

**Comment by NyakudyaA** [comment]
What disk quota caching are you using, h2 or PostgreSQL. 
How is your data dir setup

**Comment by dgtery** [comment]
![image](https://user-images.githubusercontent.com/10336363/232402816-0b61b75b-648e-462a-9c55-bae170ceff00.png)
![image](https://user-images.githubusercontent.com/10336363/232402879-eb0d20d5-5c18-41ea-8423-84f75c4f7d8f.png)

**Comment by NyakudyaA** [comment]
In production env gwc store should use a DB, https://docs.geoserver.geo-solutions.it/edu/en/caching_data/diskquotas.html

**Comment by NyakudyaA** [comment]
Please open if issue persists
