### ISSUE TITLE
GEOSERVER_DATA_DIR ignored

### ISSUE THREAD

**Issue by ghost** [kartoza/docker-geoserver#524]
### What is the bug or the crash?

Hello,

it looks like the content of the env variable GEOSERVER_DATA_DIR is not recognized anymore.

After updating my geoserver from 2.12.1 to 2.19.0 the data dir on the server status page has still the value '/usr/local/tomcat/webapps/geoserver/data', despite the env variable on the system is set to '/data'.

![grafik](https://user-images.githubusercontent.com/131688374/234036998-8159141d-0636-45e5-9c05-19a4634d89a6.png)

![grafik](https://user-images.githubusercontent.com/131688374/234037191-a04b2118-dbf0-4db9-92cb-f33ff39499d6.png)

### Steps to reproduce the issue

set env variable  GEOSERVER_DATA_DIR to another value

### Versions

2.19.0

**Comment by NyakudyaA** [comment]
Hi, any specific reason you didn't upgrade to the latest stable? What commands did you use to start

**Comment by ghost** [comment]
this was the highest version I've found on dockerhub: https://hub.docker.com/r/kartoza/geoserver

but now it works with the last stable version!
