### ISSUE TITLE
Losing all stores, layers, layergroup when restart geoserver docker.

### ISSUE THREAD

**Issue by nhaidang2808** [kartoza/docker-geoserver#529]
### What is the bug or the crash?

Losing stores, layers, layergroup when restart geoserver docker.

### Steps to reproduce the issue

I build geoserver with docker compose on a cloud server, when I need to upgrade server capacity, it causes server to be restarted and geoserver too, which causes geoserver to lose stores and all previously added layers keeping only workspaces. 

### Versions

2.23

**Comment by NyakudyaA** [comment]
Can you share the logs, there is nothing in the code that does rm. Are you using local volumes or docker volumes etc

**Comment by nhaidang2808** [comment]
> Can you share the logs, there is nothing in the code that does rm. Are you using local volumes or docker volumes etc

<img width="1214" alt="Screen Shot 2023-05-18 at 14 56 03" src="https://github.com/kartoza/docker-geoserver/assets/89778153/3825b866-4e86-4c7d-9515-cc21f9f6f1b0">
Here the logs, and I use my local volumes

**Comment by NyakudyaA** [comment]
It looks like your workspaces are not being loaded. Can you try setting the env value EXiSTING_DATA_DIR=TRUE

**Comment by nhaidang2808** [comment]
> It looks like your workspaces are not being loaded. Can you try setting the env value EXiSTING_DATA_DIR=TRUE

Ok, let's me try it. It seems that the error comes from naming the store with /, example: binhduong/thudaumot, it causes the server not to read the store path causing the error

**Comment by NyakudyaA** [comment]
You should read about rules for workspaces and namespace in GeoServer
