### ISSUE TITLE
Can't login - users.xml contains: name="GEOSERVER_ADMIN_USER" (literally)

### ISSUE THREAD

**Issue by samodadela** [kartoza/docker-geoserver#532]
### What is the bug or the crash?

We recently upgraded our GS from 2.19.x to 2.22.2. 

The first time the new images boots up - it's not possible to login to the system.

Checking `security/usergroup/default/users.xml`, shows the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<userRegistry version="1.0" xmlns="http://www.geoserver.org/security/users">
    <users>
        <user enabled="true" name="GEOSERVER_ADMIN_USER" password="digest1:zzzzzz"/>
    </users>
    <groups/>
</userRegistry>
``` 

So the reason we can't log-in is that user is set to GEOSERVER_ADMIN_USER. So instead of the value of the environment variable, it contains the name of the environment variable itself.

If I ssh to the pod, GEOSERVER_ADMIN_USER is set to "admin".

### Steps to reproduce the issue

Migrate from an old geoserver image 2.19.x (don't know if that is important, though) to 2.22.2.

### Versions

kartoza/geoserver 2.22.2

### Additional context

What's weird is that the next day, the password was suddenly changed to 'admin' ;) 

Checking the code in update_passwords.sh: the sed expression expects to find the previous username as the value in the `name` tag - is this robust? Why not simply overwrite it with whatever is contained in GEOSERVER_ADMIN_USER.

**Comment by samodadela** [comment]
Note that this happened twice on different clusters.

**Comment by samodadela** [comment]
A possible workaround... trying to debug the issue, I ran:
```
bash -x /scripts/update_passwords.sh
```

And suddenly, users.xml contains the correct value:
```
<?xml version="1.0" encoding="UTF-8"?>
<userRegistry version="1.0" xmlns="http://www.geoserver.org/security/users">
    <users>
        <user enabled="true" name="admin" password="digest1:zzzzzz"/>
    </user
    <groups/>
</userRegistry>
```

Note: before that I run `/scirpts/update_passwords.sh` and it did not print anything.

**Comment by NyakudyaA** [comment]
@samodadela This has been resolved in the latest version and other versions. You can do a PR adding that version in https://github.com/kartoza/docker-geoserver/blob/develop/.github/workflows/build-latest.yaml#L100 and https://github.com/kartoza/docker-geoserver/blob/develop/.github/workflows/deploy-image.yaml#L36

**Comment by NyakudyaA** [comment]
This should be fixed now, merged a PR that publishes new images
