### ISSUE TITLE
2.23.1 is not available on dockerhub

### ISSUE THREAD

**Issue by jl-unitedlocating** [kartoza/docker-geoserver#536]
### What is the bug or the crash?

`Error response from daemon: manifest for kartoza/geoserver:2.23.1 not found: manifest unknown: manifest unknown`

### Steps to reproduce the issue

```
VERSION=2.23.1
docker pull kartoza/geoserver:$VERSION
```

or 

```
git clone https://github.com/kartoza/docker-geoserver
cd docker-geoserver
docker-compose up -d
```

### Versions

2.23.1

### Additional context

It appears that version 2.23.1 is not available on docker hub:

https://hub.docker.com/r/kartoza/geoserver/tags?page=1

**Comment by NyakudyaA** [comment]
Fixed
