### ISSUE TITLE
Main page complains that the master password has not been set when it is

### ISSUE THREAD

**Issue by iboates** [kartoza/docker-geoserver#537]
### What is the bug or the crash?

I don't know if this is a problem with this image or with Geoserver, or maybe I am just doing something wrong, but I have certainly set the `GEOSERVER_ADMIN_USER` and `GEOSERVER_ADMIN_PASSWORD` env vars (confirmed by logging in with them), but when I log in, I see this:

![image](https://github.com/kartoza/docker-geoserver/assets/13814358/83184ca0-d2f0-4e0f-b83a-fb4145628c6e)

Is this normal?

I also keep getting complaints in the log about brute force protection due to a failed login from my own IP, even though I never try to log in with the user "admin" (because I have configured a different admin account). I will make this a separate issue because maybe they are unrelated.

Any ideas on why this is happening? Did I do something wrong and the server is indeed insecure?

### Steps to reproduce the issue

1. Spin up a container with an .env file with custom `GEOSERVER_ADMIN_USER` and `GEOSERVER_ADMIN_PASSWORD` env vars
2. Go to the UI

### Versions

kartoza/geoserver:2.22.0

**Comment by NyakudyaA** [comment]
That is not a bug, the master password is meant for use as a recovery mechanism to access geoserver, Currently there is no way to set that upfront when starting the container. https://docs.geoserver.geo-solutions.it/edu/en/security/security_overview.html#the-master-password
