### ISSUE TITLE
Logs indicate constant brute force attack prevention for user "admin" from my own IP, even though I have specified a custom user

### ISSUE THREAD

**Issue by iboates** [kartoza/docker-geoserver#538]
### What is the bug or the crash?

Possibly related to https://github.com/kartoza/docker-geoserver/issues/537

I have an instance running with custom `GEOSERVER_ADMIN_USER` and `GEOSERVER_ADMIN_PASSWORD` env vars (confirmed by logging in with them), but any time I go to the main page,  I get a brute force prevention in the logs:

```
...
lc2-geoserver-dev  | 22 Jun 09:03:36 WARN   [geoserver.security] - Failed login, user admin from <MY_IP>
lc2-geoserver-dev  | 22 Jun 09:03:36 INFO   [geoserver.security] - Brute force attack prevention, delaying login for 3650ms
lc2-geoserver-dev  | 22 Jun 09:03:39 INFO   [geoserver.security] - Strong cryptography is available
lc2-geoserver-dev  | 22 Jun 09:03:40 WARN   [geoserver.security] - Failed login, user admin from <MY_IP>
lc2-geoserver-dev  | 22 Jun 09:03:40 INFO   [geoserver.security] - Brute force attack prevention, delaying login for 4285ms
lc2-geoserver-dev  | 22 Jun 09:06:05 WARN   [geoserver.security] - Failed login, user admin from <MY_IP>
lc2-geoserver-dev  | 22 Jun 09:06:05 INFO   [geoserver.security] - Brute force attack prevention, delaying login for 1846ms
lc2-geoserver-dev  | 22 Jun 09:09:55 WARN   [geoserver.security] - Failed login, user admin from <MY_IP>
lc2-geoserver-dev  | 22 Jun 09:09:55 INFO   [geoserver.security] - Brute force attack prevention, delaying login for 2159ms
lc2-geoserver-dev  | 22 Jun 09:14:13 WARN   [geoserver.security] - Failed login, user admin from <MY_IP>
lc2-geoserver-dev  | 22 Jun 09:14:13 INFO   [geoserver.security] - Brute force attack prevention, delaying login for 4188ms
```

Maybe this is just a bug with geoserver itself?

### Steps to reproduce the issue

1. Spin up a container with custom `GEOSERVER_ADMIN_USER` and `GEOSERVER_ADMIN_PASSWORD` env vars 
2. Log in and click around, go back to the main page and watch the logs

### Versions

kartoza/geoserver:2.22.0

**Comment by NyakudyaA** [comment]
@iboates did you change your master password. It is recommended that you change it because even though you have a custom username and password, this is crucial. You can get the current master password by running
```
curl -v -u ${GEOSERVER_ADMIN_USER}:${GEOSERVER_ADMIN_PASSWORD} -XGET   http://localhost:8080/geoserver/rest/security/masterpw.xml
```
After changing the password I do not see the brute force issues
