### ISSUE TITLE
Geoserver error "exec format error" when deployed on Openshift 

### ISSUE THREAD

**Issue by rkhandha** [kartoza/docker-geoserver#546]
### What is the bug or the crash?

Below works fine 
VERSION=2.23.1
 docker run -it --name geoservertomcat  -e TOMCAT_EXTRAS=true -p 8600:8080 docker.io/kartoza/geos
erver:${VERSION}

When I deploy it opeshift with below command Pod crashes with error below 
kubectl run geoserver --image=<privaterepository>/cloudnativegis/kartoza/geoserver:2.23.1  --env="TOMCAT_EXTRAS=true" --port=8600

$ oc logs geoserver
exec /bin/bash: exec format error

### Steps to reproduce the issue

kubectl run geoserver --image=<privaterepository>/cloudnativegis/kartoza/geoserver:2.23.1  --env="TOMCAT_EXTRAS=true" --port=8600

### Versions

Geoserver version 2.23.1

**Comment by NyakudyaA** [comment]
What architecture is open shift. We either need to cater for that in the GitHub workflows or you can build the image locally on the open shift https://stackoverflow.com/questions/73285601/docker-exec-usr-bin-sh-exec-format-error

**Comment by NyakudyaA** [comment]
Can you try the images like kartoza/geoserver:pr-550-2.23.1
