### ISSUE TITLE
Failed to install plugins

### ISSUE THREAD

**Issue by Apo-** [kartoza/docker-geoserver#56]
It seems like some of the plugins fail to install after running 
```bash
git clone https://github.com/kartoza/docker-geoserver.git
cd docker-geoserver
docker build -t <tag> .
```

The issue seems to be that `wget` (inside scripts/setup.sh) fails on some of them with `Issued certificate has expired.` so adding the `--no-check-certificate` flag solves the problem for us.

**Comment by NyakudyaA** [comment]
@Apo- thanks for this. Can you build using the develop branch?  It has everything working
I will merge develop into master when I get a chance

**Comment by Apo-** [comment]
Wasn't expecting such a quick response. `develop` branch seems to be doing the trick. You are a golden shining god.
