### ISSUE TITLE
Cluster geoserver logs folder

### ISSUE THREAD

**Issue by ze-ahmed** [kartoza/docker-geoserver#563]
### What is the bug or the crash?

Hello,

When using geoserver in clustered environnement with a shared data dir, the logs of each instance are written in log4j.appender.logfile.File = ${GEOSERVER_DATA_DIR}/geoserver.log as mentionned in build_data/log4j.properties
I think that each instance should use it's file for logs and we should use log4j.appender.logfile.File = ${CLUSTER_CONFIG_DIR}/geoserver.log

Regards,
Ahmed

### Steps to reproduce the issue

Create a clustered environement of geoserver and start at least 2 instances

### Versions

2.23.1

**Comment by NyakudyaA** [comment]
@ze-ahmed we welcome a pull request from you to fix the issue
