### ISSUE TITLE
Remove the unnecessary directories under webapps

### ISSUE THREAD

**Issue by gofunn** [kartoza/docker-geoserver#579]
### Feature description

It is recommended to delete unnecessary directories under webapps to avoid some unexpected vulnerabilities.
If possible, older versions of the image are also should be updated.
```
ls /usr/local/tomcat/webapps/
docs  examples   host-manager  manager  ROOT
```

**Comment by NyakudyaA** [comment]
Those folders are available ${TOMCAT_EXTRAS} is set to true. We are building images using actions and older images are not updated unless there are bug fixes/security updates from upstream. If you want to use the logic in develop to build older images which handles deleting those files etc you are welcome to do a PR

**Comment by gofunn** [comment]
I'm sorry I didn't read the document carefully. This container is working great.

> Those folders are available ${TOMCAT_EXTRAS} is set to true. We are building images using actions and older images are not updated unless there are bug fixes/security updates from upstream. If you want to use the logic in develop to build older images which handles deleting those files etc you are welcome to do a PR这些文件夹可用${TOMCAT_EXTRAS}设置为true。我们正在使用操作构建映像，除非上游有错误修复/安全更新，否则不会更新旧映像。如果你想使用开发中的逻辑来构建旧的图像，处理删除这些文件等，欢迎你做公关
