### ISSUE TITLE
Adding ActiveMQ in the cluster docker file

### ISSUE THREAD

**Issue by krishnaglodha** [kartoza/docker-geoserver#583]
### Feature description

Should we add setup of ActiveMQ in `docker-compose` file in clustering ? 
It might help users to copy the setup directly and spin up clustered Geoserver instead of figuring out about how to add ActiveMQ

**Comment by krishnaglodha** [comment]
PS: I can work on it if that is fine

**Comment by NyakudyaA** [comment]
@krishnaglodha I do not understand what you mean, but you are free to make contributions if you feel it will make the project better

**Comment by krishnaglodha** [comment]
In the current docker-compose file in cluster, we are assuming ActiveMQ is running already. I'm suggesting instead of this, let's also include ActiveMQ docker container to compose file

**Comment by NyakudyaA** [comment]
I think it's currently running the embedded ActiveMQ which is setup by the JMS plugin but you can add another `docker-compose-external.yml` which uses the external ActiveMQ. Is this the correct interpretation?

**Comment by NyakudyaA** [comment]
This is added and working
