### ISSUE TITLE
jdom2 jar download link is not working

### ISSUE THREAD

**Issue by krishnaglodha** [kartoza/docker-geoserver#591]
### What is the bug or the crash?

to fix issue #514 there was a update made in code https://github.com/kartoza/docker-geoserver/blob/develop/scripts/start.sh#L227-L230 

but the URL seems to be broken
<img width="873" alt="Screenshot 2023-11-09 at 8 50 22 AM" src="https://github.com/kartoza/docker-geoserver/assets/47075664/7457727d-ca8a-42fe-b3ba-28375c2eef33">

### Steps to reproduce the issue

start the docker image 2.23.2 with cluster settings

### Versions

2.23.2

**Comment by NyakudyaA** [comment]
@krishnaglodha something strange is happening with that URL. If you navigate to https://jar-download.com/artifacts/org.jdom/jdom2/2.0.6.1/source-code and click on the download. The URL that is generated is identical after manually downloading is
https://download.jar-download.com/cache_jars/org.jdom/jdom2/2.0.6.1/jar_files.zip
Maybe we just need to add the jar to `build_data` and copy it in the build

**Comment by krishnaglodha** [comment]
> @krishnaglodha something strange is happening with that URL. If you navigate to https://jar-download.com/artifacts/org.jdom/jdom2/2.0.6.1/source-code and click on the download. The URL that is generated is identical after manually downloading is https://download.jar-download.com/cache_jars/org.jdom/jdom2/2.0.6.1/jar_files.zip Maybe we just need to add the jar to `build_data` and copy it in the build

I agree, it will be easy to put jar file in folder it self

**Comment by krishnaglodha** [comment]
Hi @NyakudyaA , by simply using 2.23.2 I'll be able to pull these changes right? I mean by simply using `kartoza/geoserver.2.23.2` as image name ?

**Comment by NyakudyaA** [comment]
You won't find this fix in the older images. The action only builds the latest images unless it's a bug fix which we can patch up the version number in the action

**Comment by NyakudyaA** [comment]
Also still need to fix the broken action
https://github.com/kartoza/docker-geoserver/actions/runs/6820633333
