### ISSUE TITLE
support for 2.24.1

### ISSUE THREAD

**Issue by krishnaglodha** [kartoza/docker-geoserver#599]
### Feature description

Can we create support for 2.24.1 . I'll be available for contribution if needed, please send me guide link on how to get started with it

**Comment by NyakudyaA** [comment]
@krishnaglodha You need to run https://github.com/kartoza/docker-geoserver#upgrading-geoserver-versions and also modify the https://github.com/kartoza/docker-geoserver/tree/develop/.github/workflows

**Comment by krishnaglodha** [comment]
Hi, I checked it but I'm lil bit confused about how to use it. Sorry if it's a basic question. Is there any brief doc about how to execute this ? 

Also If I'm not wrong, this will create latest image on my local , correct >

**Comment by krishnaglodha** [comment]
Hi @NyakudyaA I just checked the workflow for deploy and looks like it's been running for roughly 2 hours, and still `in progress`

**Comment by NyakudyaA** [comment]
Done, had to restart it again
