### ISSUE TITLE
roles.xml & roles.xml.orig down to 0 bytes

### ISSUE THREAD

**Issue by r4mst3r** [kartoza/docker-geoserver#608]
### What is the bug or the crash?

Hi,

I was shutting down geoserver 2.22.0 and restarting with 2.22.5 when startup failed, finally realized roles.xml and roles.xml.orig were down to 0 bytes.

No idea how that could happen but realized update_password performs a sed operation on the orig file and immediately replaces roles.xml file.

Any clue how or why roles.xml files went down to 0 bytes and how to prevent it from happening?

Happened once to far, cant reproduce.

Thanks

### Steps to reproduce the issue

Shut down geoserver 2.22.0
Startup geoserver 2.22.5 on same data_dir
-only happened once: startup failure, roles.xml is 0 bytes

### Versions

2.22.0/2.22.5

**Comment by NyakudyaA** [comment]
The script `update_password.sh` creates a lockfile that will prevent reinitialisation of the passwords, by default this is stored in `/settings` if you need to persist this please also mount a volume i.e `-v pass_settings:/settings` and on restart the password updating will not happen
