### ISSUE TITLE
GEOSERVER_ADMIN_PASSWORD has no effect

### ISSUE THREAD

**Issue by genebobmiller** [kartoza/docker-geoserver#61]
The following command results in a geoserver instance that still has the default admin password.
 
```
docker run --name "geoserver"  -e GEOSERVER_ADMIN_PASSWORD='myawesomegeoserver' -p 8080:8080 -d -t kartoza/geoserver
```

**Comment by NyakudyaA** [comment]
@genebobmiller I think the changes haven't been built into the image yet. Can you try to build the image yourself either using the master or develop branch? 

I will look at why auto builds are not building

**Comment by genebobmiller** [comment]
Thanks NyakudyaA, I can confirm this feature is working fine in a fresh build from the master branch.

It is not working on the 2.13.0 and 'latest' tags from dockerhub

**Comment by NyakudyaA** [comment]
Closing this as well because this has been tested with various versions of geoserver from 2.13 till 2.15

**Comment by genebobmiller** [comment]
Just confirming that this is not working on 2.13 which is the latest release pushed to dockerhub, it would be great to have a tag with this feature working pushed to dockerhub if possible.

**Comment by matthesrieke** [comment]
are there any news on this? I am still observing this in the `2.15.0` and `latest` (from May 6, 2019) tag.

**Comment by NyakudyaA** [comment]
@matthesrieke this is working in the 2.15.0 branch. Please use the docker-compose in the repo and the env variables. You will get the desired effect

**Comment by FedericOldani** [comment]
Hi, I still have the mentioned problem. the 
- GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
has no effect and the password remains the default one. 
It tried the tags 2.19.0 and 2.20.2. Does anyone have a hint?

**Comment by NyakudyaA** [comment]
> Hi, I still have the mentioned problem. the
> 
>     * GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
> 
> 
> has no effect and the password remains the default one. It tried the tags 2.19.0 and 2.20.2. Does anyone have a hint?

@FedericOldani Can you try to build the image yourself from the master branch. I refactored the way passwords are handled in https://github.com/kartoza/docker-geoserver/commit/e231ec7f7d159f8985dcbed3f7a7a24ffa08fe8c and added the ability to mount the passwords and roles as config files in https://github.com/kartoza/docker-geoserver/commit/6e4cc6f756ba376bb71affb6223beab65f1a3774

**Comment by jpgnz** [comment]
I don't have the same issue with kartoza/geoserver:2.21.0 in that, setting these variables like so (in docker-compose.yml):

```
      environment:
        - GEOSERVER_ADMIN_USER=admintest
        - GEOSERVER_ADMIN_PASSWORD=geoservertest
```

Allowed me to login with those credentials.
