### ISSUE TITLE
Can' t login into geoserver

### ISSUE THREAD

**Issue by jorgejesus** [kartoza/docker-geoserver#62]
Steps to replicate:

> git clone https://github.com/kartoza/docker-geoserver
> cd docker-geoserver
> git show
> commit 868d89aa97e8c1defc74e5197e1525577e41dbe4 (HEAD -> master, origin/master, origin/HEAD)
> docker build --build-arg INITIAL_MEMORY=750M  --build-arg MAXIMUM_MEMORY=1G -t kartoza/geoserver .
> docker run --name "geoserver"  -e GEOSERVER_ADMIN_PASSWORD='myawesomegeoserver' -p 8080:8080 -d -t kartoza/geoserver

The login with any password give the following error (see below). Seems there is some problems with the password creation maybe how is it done on script `scripts/update_password.sh`

``
org.jasypt.exceptions.EncryptionOperationNotPossibleException
	org.jasypt.digest.StandardByteDigester.matches(StandardByteDigester.java:1107)
	org.jasypt.digest.StandardStringDigester.matches(StandardStringDigester.java:1052)
	org.jasypt.util.password.StrongPasswordEncryptor.checkPassword(StrongPasswordEncryptor.java:99)
	org.jasypt.spring.security3.PasswordEncoder.isPasswordValid(PasswordEncoder.java:204)
	org.geoserver.security.password.AbstractGeoserverPasswordEncoder.isPasswordValid(AbstractGeoserverPasswordEncoder.java:142)
	org.geoserver.security.password.GeoServerMultiplexingPasswordEncoder.isPasswordValid(GeoServerMultiplexingPasswordEncoder.java:91)
	org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:94)
	org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:165)
	org.geoserver.security.auth.UsernamePasswordAuthenticationProvider.authenticate(UsernamePasswordAuthenticationProvider.java:82)
	org.geoserver.security.GeoServerAuthenticationProvider.authenticate(GeoServerAuthenticationProvider.java:58)
	org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:167)
	org.geoserver.security.GeoServerSecurityManager$1.authenticate(GeoServerSecurityManager.java:323)
	org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:93)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	org.geoserver.security.filter.GeoServerUserNamePasswordAuthenticationFilter.doFilter(GeoServerUserNamePasswordAuthenticationFilter.java:116)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
	org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:152)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:88)
	org.geoserver.filters.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:89)
	org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
	org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
	org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
``

**Comment by NyakudyaA** [comment]
@jorgejesus Is this not related to #61

**Comment by israelshp** [comment]
@NyakudyaA I experience the same issue even when building the image by myself from the master branch.

**Comment by jorgejesus** [comment]
@NyakudyaA @israelshp  even without setting the password I am getting the same error

**Comment by jorgejesus** [comment]
The issue was caused by a volume that was used between different GS versions and it caused the problem 
@NyakudyaA could you check that there is no volume content contamination on your side, I will then close the issue. Thank you all for the support

**Comment by NyakudyaA** [comment]
@jorgejesus cc @israelshp I will close this. I have tested this and it works on my side. I always use docker-compose to spin up my images and I use volumes. Perhaps you should try using the docker-compose file that comes in with the repository

**Comment by israelshp** [comment]
@NyakudyaA In my case, the problem was that the `update_passwords.sh` script failed to find the right path to the jasypt jar file. 
This regex `".*jasypt-[0-9]\.[0-9]\.[0-9].*jar"` [here](https://github.com/kartoza/docker-geoserver/blob/master/scripts/update_passwords.sh#L17) doesn't work for jasypt-1.8.jar, which is the version shipped with GeoServer 2.13. 
Changing it to `".*jasypt-[0-9]\.[0-9]\.[0-9]?.*jar"` solved the problem for me.

**Comment by NyakudyaA** [comment]
> @NyakudyaA In my case, the problem was that the `update_passwords.sh` script failed to find the right path to the jasypt jar file.
> This regex `".*jasypt-[0-9]\.[0-9]\.[0-9].*jar"` [here](https://github.com/kartoza/docker-geoserver/blob/master/scripts/update_passwords.sh#L17) doesn't work for jasypt-1.8.jar, which is the version shipped with GeoServer 2.13.
> Changing it to `".*jasypt-[0-9]\.[0-9]\.[0-9]?.*jar"` solved the problem for me.

@israelshp have you tested this with the other versions like 2.14 and see if your regex will apply. I did test with 2.15.0 which I aim to make a new release today and it worked. So I can add that change in the 13 branch

**Comment by israelshp** [comment]
Yes, tested with 2.13 and 2.14

**Comment by NyakudyaA** [comment]
@israelshp can you please test the develop branch

**Comment by NyakudyaA** [comment]
@jorgejesus @israelshp I have pushed a new image 2.15.0 to docker hub.
I did test it locally after pulling

![pull](https://user-images.githubusercontent.com/2510900/54837139-55ebc700-4cce-11e9-8aba-5eae1a5a1194.png)

Password specified in env
![compose](https://user-images.githubusercontent.com/2510900/54837172-68660080-4cce-11e9-8827-d0f91ab62627.png)

Docker-compose using 2.15.0
![compose-file](https://user-images.githubusercontent.com/2510900/54837195-774cb300-4cce-11e9-97a6-7cb2d69e0fc3.png)

Logged in with the new admin password
![logged-in](https://user-images.githubusercontent.com/2510900/54837230-8895bf80-4cce-11e9-83d9-64151c63b2ab.png)

Thanks for testing and your contributions

**Comment by NyakudyaA** [comment]
Thanks for testing
