### ISSUE TITLE
Clearing users.xml while creating user 

### ISSUE THREAD

**Issue by deenu2** [kartoza/docker-geoserver#664]
### What is the bug or the crash?

I have deployed the geoserver in Kubernetes and whenever I create a user it clear the users.xml file as it will be empty and geoserver will start crashing due to that. I have configured EFS volume for persistent storage.

### Steps to reproduce the issue

deployed the geoserver in EKS cluster with EFS storage for persistence storage, created a user and if the geoserver pod restart it will clear the users.xml file.

### Versions

2.25.0

### Additional context

I have faced the same issue in 2.22.1 version as well

**Comment by NyakudyaA** [comment]
What do you mean when you say create a user, through the UI or on startup with env variables?

**Comment by deenu2** [comment]
once geoserver is up and running I logged in and created a new user using the UI and after that if I restart the pod facing the issue
![image](https://github.com/kartoza/docker-geoserver/assets/87584466/f2257c43-daff-418b-89a6-11054f9f854e)

**Comment by NyakudyaA** [comment]
You need to add a persistent mount like
```
-v settings:/settings
```

Because in Kubernetes, restarting a pod, recreates a new container with new params whilst in docker-compose a restart is different as it just restarts the running instance

**Comment by deenu2** [comment]
Thank you for the solution it worked
