### ISSUE TITLE
cp: cannot stat issue

### ISSUE THREAD

**Issue by serbasii** [kartoza/docker-geoserver#68]
when i exec the command like this;

`docker run -it --name "geoserver" -v "D:/docker/data/geoserver_data:/opt/geoserver/data_dir" -e GEOSERVER_ADMIN_PASSWORD='myawesomegeoserver' -p 8080:8080  kartoza/geoserver`

_cp: cannot stat '/opt/geoserver/data_dir/security/usergroup/default/users.xml': No such file or directory
/scripts/update_passwords.sh: line 25: /opt/geoserver/data_dir/security/usergroup/default/users.xml: No such file or directory
cat: /opt/geoserver/data_dir/security/usergroup/default/users.xml.orig: No such file or directory_

**Comment by patleb** [comment]
Same here

**Comment by serbasii** [comment]
you mean that container storage?

**Comment by NyakudyaA** [comment]
> you mean that container storage?

@serbasii 
I mean storage volumes as specified here https://github.com/kartoza/docker-geoserver/blob/master/docker-compose.yml

**Comment by patleb** [comment]
It doesn't seem to be a storage volume problem: it works for GeoServer 2.13.0, but not for 2.15.0.

**Comment by NyakudyaA** [comment]
@patleb I am quite certain that it relates to using a mounted volume. In 2.13.0 there was no variable to add a password on startup so that was added from 2.15.0 upwards .

If I run the following 
`docker run -it --name "geoserver"  -e GEOSERVER_ADMIN_PASSWORD='myawesomegeoserver'  kartoza/geoserver:2.15.0` I do not get any error because the data directory is correct.

![data-dir](https://user-images.githubusercontent.com/2510900/57100090-5ab88780-6d1e-11e9-853e-c6cb7130a73b.png)

If I use storage volumes there is no problem at all.
![save(1)](https://user-images.githubusercontent.com/2510900/57100193-96535180-6d1e-11e9-852a-436a5cb7db24.gif)

**Comment by patleb** [comment]
I suspect that you already had some data in `geoserver-data` outside your container.

The error reported is a path problem. With 2.13.0, the volume is correctly shared, with 2.15.0, it's not.

**Comment by serbasii** [comment]
i'm running windows docker engine as linux container; 

As creating a _volume_ explicitly `docker volume create` works but _binding mounts_ not.  is it due to permission issue?

**Comment by NyakudyaA** [comment]
@patleb cc @serbasii According to the official docker documentation https://docs.docker.com/v17.09/engine/admin/volumes/bind-mounts/

![mount](https://user-images.githubusercontent.com/2510900/57134943-0ce86180-6da8-11e9-9d89-39968633944f.png)

So, in a nutshell, I encourage you to use docker volumes because within the image we keep the security folder https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L169 so that we can be able to change the password on runtime.

**Comment by patleb** [comment]
@NyakudyaA, I think there is a bit of misunderstanding here. I was saying that the error message shows that the path doesn't exist. So, if the error doesn't appear in the example you showed us, then the path does exist in your setup. Which implies that  there is only one explanation: considering the paths are the same for 2.13.0 and 2.15.0, me and @serbasii have an empty shared volume when we bring up the container. Also, if you execute the same commands as us, but don't experience the bug, then you either have an indeed functioning environment (which I would like to know how it differs from us) or you previously had your shared volume filled before bringing up the container (which might happen if you didn't cleared it up before changing the image version).

**Comment by HueyNemud** [comment]
I have experienced the same situation today.
Currently we can't persist data_dir as a bind-mount as the configuration files created by setup.sh are obscured when the container starts. 

@NyakudyaA Would it be possible to delegate the initialization of data_dir to entrypoint.sh? This what the official postgreSQL image does, see https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh

**Comment by NyakudyaA** [comment]
@patleb We seem to be on a different footing. So let me explain to you what is happening

* When we create the image we unzip geoserver.war which also contains geoserver data directory.
* Inside the geoserver data directory we copy the folder `security` and put it in `/opt/geoserver_data`.
* Once the image is built the contents of `/opt/geoserver_data` look like the image below
![security](https://user-images.githubusercontent.com/2510900/57139183-d5cc7d00-6db4-11e9-837b-7eaf38a11528.png)

* So when a user tries to spin up a container using the bound mount volume it then masks all the files specified in `/opt/geoserver_data/data_dir/security` and hence the script will not run. 
But if you use a docker-volume you basically can get your container running.

* I will change the configuration to allow bound-volume to be used 

In the meantime you could use the following https://stackoverflow.com/questions/47519309/mount-an-empty-folder-in-host-to-a-non-empty-folder-in-docker

**Comment by patleb** [comment]
@NyakudyaA, I don't think that you understand what I'm saying. Quick question, have you been able to reproduce the bug in this issue?

> So when a user tries to spin up a container using the bound mount volume it then masks all the files specified in /opt/geoserver_data/data_dir/security and hence the script will not run.

No, unless there is no `/usergroup/default/users.xml`, then it will run [here](https://github.com/kartoza/docker-geoserver/blob/master/scripts/update_passwords.sh#L12).

**Comment by NyakudyaA** [comment]
@patleb just hang in there I am making a PR shortly with the fix. I have already fixed it on my local machine

![fixes](https://user-images.githubusercontent.com/2510900/57146274-395ea680-6dc5-11e9-8b45-a2041387891b.png)

**Comment by patleb** [comment]
But, yes, I agree that if you manually bind the volume, then it will work.

**Comment by NyakudyaA** [comment]
@patleb @HueyNemud @serbasii I have fixed this. Can you build using the develop branch and revert to me so that I can push the changes to the 2.15.0 image

**Comment by HueyNemud** [comment]
@NyakudyaA  Tried on the development branch with : `docker run -ti -e GEOSERVER_DATA_DIR='/data_dir' -p 8080:8080 -v "/tmp/geoserver_data_dir:/data_dir" kartoza/geoserver:2.15.0`
Works like a charm, thank you!

**Comment by patleb** [comment]
@NyakudyaA tried also:

```yaml
version: "3"
services:
  geoserver:
    build: https://github.com/kartoza/docker-geoserver.git#develop
    # build: ./geoserver
```

There is still something preventing docker to share the volume. If I find why, I'll report back here. I've add a similar problem for the Postgres container used with an Odoo container and it was working only if I went down one path segment: `/var/lib/postgresql` --> `/var/lib/postgresql/data`. I didn't dig more and just let it go, but what is going on here seems very similar.

**Comment by patleb** [comment]
FYI, with named volumes, it works, but for volumes with defined by path, it doesn't. So, basically, I had:

```yaml
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
```

and from now on:

```yaml
volumes:
  geoserver_data:
...
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
```

is working as expected. So, the problem might be on docker side, but not this repo.

**Comment by NyakudyaA** [comment]
> FYI, with named volumes, it works, but for volumes with defined by path, it doesn't. So, basically, I had:
> 
> ```yaml
>     volumes:
>       - ./geoserver_data:/opt/geoserver/data_dir
> ```

Can you try to `"./geoserver_data:/opt/geoserver/data_dir"`
> 
> and from now on:
> 
> ```yaml
> volumes:
>   geoserver_data:
> ...
>     volumes:
>       - geoserver_data:/opt/geoserver/data_dir
> ```
> 
> is working as expected. So, the problem might be on docker side, but not this repo.

@patleb I have the following setup on my side and it's working seamlessly.
![Screenshot 2019-05-03 at 23 52 41](https://user-images.githubusercontent.com/2510900/57167644-c540f480-6dfe-11e9-9589-9e0875ed0ee4.png)

**Comment by serbasii** [comment]
@NyakudyaA it worked as development branch. May be push the changes to currnent version.

**Comment by NyakudyaA** [comment]
> @NyakudyaA it worked as development branch. May be push the changes to the current version.

@serbasii pushed to the latest tag and 2.15.0 tag

**Comment by patleb** [comment]
@NyakudyaA
> Can you try to "./geoserver_data:/opt/geoserver/data_dir"

Same behavior. It might be related to the usage a more recent docker-compose (I'm using the latest).

**Comment by NyakudyaA** [comment]
> @NyakudyaA
> 
> > Can you try to "./geoserver_data:/opt/geoserver/data_dir"
> 
> Same behavior. It might be related to the usage a more recent docker-compose (I'm using the latest).

@patleb I am not sure what is happening on your machine. I can't replicate this using a more recent version of compose.

![Screenshot 2019-05-06 at 17 10 33](https://user-images.githubusercontent.com/2510900/57234859-e6355f80-7021-11e9-8ea4-c473f2c25495.png)

![Screenshot 2019-05-06 at 17 05 11](https://user-images.githubusercontent.com/2510900/57234941-14b33a80-7022-11e9-9bef-f97c6ca23a80.png)

**Comment by patleb** [comment]
Not sure either what's happening. I'll stick to named volumes. Thanks anyway, I really appreciate your help.

**Comment by rmmariano** [comment]
I was having this same problem and I've noticed that the host folder was being created by Docker, which caused the problem.
To fix it, I had to manually create the folder in the host (e.g. `D:/docker/data/geoserver_data`).
