### ISSUE TITLE
Hosting docs to URL

### ISSUE THREAD

**Issue by krishnaglodha** [kartoza/docker-geoserver#680]
### Feature description

Hi, I worked on this https://github.com/kartoza/docker-geoserver/tree/develop/docs sometime back, are we planning to make it live so I'll update it to match with latest changes ?

**Comment by NyakudyaA** [comment]
@krishnaglodha This is already available on https://kartoza.github.io/docker-geoserver/

**Comment by NyakudyaA** [comment]
@krishnaglodha i know this is a long shot but do you have the source mkdocs yaml so that we can update and server them
