### ISSUE TITLE
Add support for geoserver v2.23.6

### ISSUE THREAD

**Issue by andrewmolyuk** [kartoza/docker-geoserver#681]
### Feature description

Can we get a docker image with patched geoserver v2.23.6?

**Comment by NyakudyaA** [comment]
Please do a PR if you have a chance, it's just changing github action values there

**Comment by andrewmolyuk** [comment]
Sorry for newbie question, but where I can find the image with geoserver v2.23.6 inside?

**Comment by NyakudyaA** [comment]
It seems there was an error in the build, will republish again sometime later today

**Comment by NyakudyaA** [comment]
Done

**Comment by andrewmolyuk** [comment]
Thank you!
