### ISSUE TITLE
Added Geonode?

### ISSUE THREAD

**Issue by SigTill** [kartoza/docker-geoserver#689]
### What is the bug or the crash?

Latest release: [2.24.4-geo-v2024.08.15](https://hub.docker.com/layers/kartoza/geoserver/2.24.4-geo-v2024.08.15/images/sha256-254f440b4a7a956d944f44e0b42dcdccf83dfca235109e684c852662c9c7eaab?context=explore)

Last pushed 21 days ago by [meomancer](https://hub.docker.com/u/meomancer)

Also seems to contain GEONODE - is that intentional?

### Steps to reproduce the issue

Go to https://hub.docker.com/r/kartoza/geoserver/tags - look for [2.24.4-geo-v2024.08.15](https://hub.docker.com/layers/kartoza/geoserver/2.24.4-geo-v2024.08.15/images/sha256-254f440b4a7a956d944f44e0b42dcdccf83dfca235109e684c852662c9c7eaab?context=explore)

### Versions

2.24.4

**Comment by NyakudyaA** [comment]
@SigTill Please only use the images with the tags formats
```
VERSION=2.23.6
DATE=2024.07.26
kartoza/geoserver:${VERSION}--v${DATE}
```
or

```
VERSION=2.23.6
kartoza/geoserver:${VERSION}
```
Please refer to https://github.com/kartoza/docker-geoserver?tab=readme-ov-file#pulling-from-dockerhub, all other variants are for internal use and yes it contains GeoServer for GeoNode and you can use it if you have a GeoNode deployment but you will need to know what version of GeoNode that is running against

**Comment by SigTill** [comment]
Thank you for the quick reply, was worried that something was "off" - thats why I reported it. Case can be "closed"
