### ISSUE TITLE
Need old master password in order to change to a new one 

### ISSUE THREAD

**Issue by ellvtr** [kartoza/docker-geoserver#69]
I'm using your geoserver docker image and I can't figure out what the master password is. It appears to be encrypted in file `opt/geoserver/data_dir/security/masterpw/default/passwd`. 

In order to change the master password on my installation I need the old one.

Can you help me out?

**Comment by NyakudyaA** [comment]
@ellvtr have you tried running 
`curl -v -u admin:geoserver -XGET   http://localhost:8080/geoserver/rest/security/masterpw.xml`

**Comment by ellvtr** [comment]
Thanks, I was trying to change it through the UI rather than through the REST API. Either way, I believe the old pw is needed. I assume it is `geoserver` then.

**Comment by NyakudyaA** [comment]
@ellvtr The snipped above is an example and it will let you know what the password is.
For example
![example](https://user-images.githubusercontent.com/2510900/57132132-e1ad4480-6d9e-11e9-9f20-8b742d840bac.png)

**Comment by ellvtr** [comment]
Thanks, I managed to change the master pw through the UI yet still can't login using `root:NewMasterPw`. Strange.

Thanks for your help anyway. I guess I could've guessed that it was `geoserver` by default. Didn't occur to me. Sorry for bothering you.

**Comment by NyakudyaA** [comment]
The master password is used to recover geoserver. Thanks I could help

**Comment by ellvtr** [comment]
Hi again, can you help me with the default pw for Tomcat manager and how to change that?
See screenshot.

![image](https://user-images.githubusercontent.com/12038749/57214322-f0d40280-6fe9-11e9-865b-f5c9c3055faa.png)

**Comment by ellvtr** [comment]
Hi again, can you help me with the default pw for the tomcat manager and how to change it?

![image](https://user-images.githubusercontent.com/12038749/57214415-3690cb00-6fea-11e9-814c-7cbff68aced8.png)

**Comment by NyakudyaA** [comment]
> Hi again, can you help me with the default pw for the tomcat manager and how to change it?
> 
> ![image](https://user-images.githubusercontent.com/12038749/57214415-3690cb00-6fea-11e9-814c-7cbff68aced8.png)

@ellvtr Can you take a look at the following https://www.mkyong.com/tomcat/tomcat-default-administrator-password/

**Comment by ellvtr** [comment]
Thanks @NyakudyaA , I managed to set a user and password for tomcat :)
