### ISSUE TITLE
Unexpected environment variable mapping

### ISSUE THREAD

**Issue by mpschaeuble** [kartoza/docker-geoserver#698]
### What is the bug or the crash?

In the entrypoint.sh script, the environment variable PROXY_BASE_URL_PARAMETRIZATION (which is set to false by default in env-data.sh) is mapped to the geoserver variable ALLOW_ENV_PARAMETRIZATION. This leads to the fact, that setting the environment variable ALLOW_ENV_PARAMETRIZATION in a docker environment, the variable value is not considered by geoserver. I couldn't find any information about this topic in the documentation, but the mapping looks wrong to me.

### Steps to reproduce the issue

see https://github.com/kartoza/docker-geoserver/blob/develop/scripts/entrypoint.sh

### Versions

v2.23.0

**Comment by NyakudyaA** [comment]
https://docs.geoserver.org/main/en/user/datadirectory/configtemplate.html

**Comment by mpschaeuble** [comment]
@NyakudyaA Has this been fixed? I couldn't find any related code changes.

**Comment by NyakudyaA** [comment]
@mpschaeuble I am not sure what changes are needed here, https://github.com/kartoza/docker-geoserver/blob/develop/scripts/entrypoint.sh#L75 is properly defined, The only possible change I see here is to rename the environment to something like
`ALLOW_ENV_PARAMETRIZATION`, if you have any other suggestions please feel free to say so
