### ISSUE TITLE
configuring ssl with letsencrypt

### ISSUE THREAD

**Issue by micahl98** [kartoza/docker-geoserver#75]
Need some guidance on how to setup SSL with this container; I'm familiar with configuring SSL, but not as it relates to Docker. Thanks!

**Comment by NyakudyaA** [comment]
@micahl98 Do you use rancher in deployments. If so you can take a look at https://github.com/janeczku/rancher-letsencrypt or https://www.digitalocean.com/community/tutorials/how-to-secure-your-rancher-web-app-with-let-s-encrypt-on-ubuntu-16-04

**Comment by NyakudyaA** [comment]
@micahl98 can you try to build geoserver using this image https://github.com/AtomGraph/letsencrypt-tomcat ie
docker build --build-arg IMAGE_VERSION=8-jre8 --build-arg GS_VERSION=2.13.0 -t kartoza/geoserver:2.13.0 .
