### ISSUE TITLE
Oracle JDK changed it's licence

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-geoserver#77]
# Problem

Oracle changed it's licence a couple of months back and ever since our builds are partially working because of this restrictions. The setup scripts download a bunch of these.

![Screenshot 2019-07-10 at 17 52 39](https://user-images.githubusercontent.com/2510900/60984178-8b7af580-a33b-11e9-9095-3540854b8e17.png)

# Solution

* Please investigate a feasible solution.
* We could fetch them from other third-party repos.
* Update the licence terms to reflect the new Oracle changes

cc @gubuntu @timlinux

**Comment by gubuntu** [comment]
what are the GeoServer / GeoSolutions people doing about it?

what do we need to do to comply without having to pay anything? Try to implement that...

If all else fails, switch to OpenJDK.

**Comment by NyakudyaA** [comment]
The only thing that needs to be downloaded from Oracle Java is `jdk-8u201-linux-x64.tar.gz` or the latest version for people who need to build with oracle java. I have added this in the Readme
