### ISSUE TITLE
Change default password in changelog

### ISSUE THREAD

**Issue by 1Jesper1** [kartoza/docker-geoserver#78]
Default password is "myawesomegeoserver" and not "geoserver"? https://github.com/kartoza/docker-geoserver#changing-geoserver-password-on-runtime

**Comment by NyakudyaA** [comment]
Hi @1Jesper1 the default password is `geoserver` not `myawesomegeoserver`. Read carefully the statement 
```
The default geoserver user is 'admin' and the password is 'geoserver'. You can pass the environment variable GEOSERVER_ADMIN_PASSWORD to change it on runtime
```
This basically means if you do not use the env variable `GEOSERVER_ADMIN_PASSWORD` you will log in to geoserver using `admin:geoserver`

**Comment by 1Jesper1** [comment]
Ah I understand @NyakudyaA I used `docker-compose`, docker-compose uses https://github.com/kartoza/docker-geoserver/blob/aebe1652d7728a0394667f6fa3307cd4e36eb251/docker-compose.yml https://github.com/kartoza/docker-geoserver/blob/aebe1652d7728a0394667f6fa3307cd4e36eb251/docker-env/geoserver.env which sets the password to `myawesomegeoserver`

**Comment by NyakudyaA** [comment]
In that case yes the default password would be `myawesomegeoserver`. I will look at it at reword the README
