### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by icemagno** [kartoza/docker-geoserver#86]
How can I set the Tomcat / Java proxy?

**Comment by NyakudyaA** [comment]
Hi @icemagno What do you need to achieve ?.
Have you looked at https://docs.geoserver.org/stable/en/user/security/tutorials/httpheaderproxy/index.html or https://docs.geoserver.org/latest/en/user/production/misc.html#proxy-your-server .
Alternatively have a quick look at stack exchange

**Comment by icemagno** [comment]
I need to create a WMS store from another geoserver outside my corporation. My proxy have user/password authentication to go outside.

Already tried all possible `http_proxy` configurations in ENV (building phase) or `-e JAVA_OPTS` and `-e GEOSERVER_OPTS` (runing phase).

**Comment by icemagno** [comment]
I always receive a 407 error.

**Comment by EHJ-52n** [comment]
@icemagno Isn't it a general geoserver question?

**Comment by icemagno** [comment]
Yeah.  Already open a ticket there. Thanks.

**Comment by NyakudyaA** [comment]
@icemagno thanks for this. I will close this since it's not docker specific

**Comment by EHJ-52n** [comment]
@icemagno Could you please add a link to your issue, please.

**Comment by icemagno** [comment]
Go to Geoserver JIRA and search for GEOS-9313 ( Configuration of Proxy via GUI )

**Comment by icemagno** [comment]
This can help you too to understand the problem: https://gis.stackexchange.com/questions/191959/how-to-configure-geoserver-to-use-a-proxy-when-accessing-external-services

**Comment by EHJ-52n** [comment]
https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-9313
