### ISSUE TITLE
How to build with CORS support?

### ISSUE THREAD

**Issue by j08lue** [kartoza/docker-geoserver#87]
@NyakudyaA in #24 and #60, you mentioned that your 2.15.2 image includes CORS support. But how is that image built (in case I wanted to build a slightly modified version)? Surely not just plain with `build.sh`? Do you just need to include the `web.xml` in the `resources/overlays` folder when building?

**Comment by NyakudyaA** [comment]
@j08lue you just need to add web.xml into the resources folder as specified below
![61949797-45b16480-afac-11e9-8751-aefb6b2d68f4](https://user-images.githubusercontent.com/2510900/63926992-1f6c6200-ca4d-11e9-87c3-724bd150e44d.png)

**Comment by j08lue** [comment]
That simple, thanks. Maybe you could include these instructions in your README? Just a suggestion...

**Comment by NyakudyaA** [comment]
> That simple, thanks. Maybe you could include these instructions in your README? Just a suggestion...

I will when I get a chance

**Comment by NyakudyaA** [comment]
Fixed in develop, will be porting to master

**Comment by lukaszswitaj** [comment]
There is no example in any of the branches, master nor develop.

**Comment by NyakudyaA** [comment]
> There is no example in any of the branches, master nor develop.

Please read carefully on the readme
![Screenshot 2019-09-14 at 21 59 13](https://user-images.githubusercontent.com/2510900/64913150-0fd26600-d73b-11e9-9e39-ccd1ccd2fc1c.png)
