### ISSUE TITLE
Missing PostGIS store?

### ISSUE THREAD

**Issue by fegyi001** [kartoza/docker-geoserver#88]
I installed the kartoza/geoserver:2.15.2 version, and really like how many vector and raster data sources are available out of the box when I try to create a new Store. 

One extremely important seems to be missing though: PostGIS. This should be included in any GeoServer by default, how can it be, that I cannot see it, and therefore cannot add a PostGIS Store to my GeoServer?

Or did I do something wrong? My Dockerfile consists of nothing else than simply:
"FROM kartoza/geoserver:2.15.2"

See: 
![image](https://user-images.githubusercontent.com/4125222/64159313-51f5d080-ce3a-11e9-8c12-ae62c4c79054.png)

**Comment by NyakudyaA** [comment]
Hi @fegyi001 I have pulled the docker image and ran the following
![logs-geos](https://user-images.githubusercontent.com/2510900/64161705-5b813780-ce3e-11e9-955b-dce47662e929.png)

And opening up Geoserver I could see the following
![postgis](https://user-images.githubusercontent.com/2510900/64161742-6cca4400-ce3e-11e9-98b8-b7fd1e82971d.png)

To check if I am not running a local image I did the following
![ubuntu](https://user-images.githubusercontent.com/2510900/64161795-85d2f500-ce3e-11e9-93f0-ab2f28ef88d9.png)

I logged in the container and I could see that there is only one PostGIS binary.
![nary](https://user-images.githubusercontent.com/2510900/64162038-ebbf7c80-ce3e-11e9-962b-2c59f96163ea.png)

Can you please try to follow the https://github.com/kartoza/docker-geoserver/issues/79

**Comment by NyakudyaA** [comment]
@fegyi001 Also please pull the latest 2.15.2 image first

**Comment by fegyi001** [comment]
Ok, I really needed to pull 2.15.2 again, and after that, after a build, now I can see the PostGIS type. But now all the other store types are missing, only the default ones are visible. Is it a desired feature?

**Comment by NyakudyaA** [comment]
@fegyi001 I will see what is happening with the gdal store maybe the gdal-plugin is not being imported properly

**Comment by NyakudyaA** [comment]
@fegyi001 please pull the latest image.
![image](https://user-images.githubusercontent.com/2510900/64430070-c2f5ec00-d0b7-11e9-9e25-cb8c0fe89faa.png)
