### ISSUE TITLE
Moving GEOSERVER_OPTS from build time to run time

### ISSUE THREAD

**Issue by Wieschie** [kartoza/docker-geoserver#93]
Is there a reason GEOSERVER_OPTS is fully baked into the image?

It'd be nice to just be able to set INITIAL_MEMORY and MAXIMUM_MEMORY at runtime by passing in the environment variables.  Couldn't we just move the `-Xms` and `-Xmx` additions [here](https://github.com/kartoza/docker-geoserver/blob/11ad33d549e1e61f836da6d15c013405708de176/Dockerfile#L51) to [entrypoint.sh](https://github.com/kartoza/docker-geoserver/blob/11ad33d549e1e61f836da6d15c013405708de176/scripts/entrypoint.sh)?

**Comment by NyakudyaA** [comment]
@Wieschie environment variables are meant to be used at run time. If you look carefully at the code the  `GEOSERVER_OPTS` are initialized from entrypoint https://github.com/kartoza/docker-geoserver/blob/master/scripts/entrypoint.sh#L7

**Comment by Wieschie** [comment]
Right, but the Dockerfile interpolates the INITIAL_MEMORY and MAXIMUM_MEMORY into GEOSERVER_OPTS at build time.  So the values the entrypoint gets just contains whatever memory values existed when the image was built.

To override them currently, you'd need to entirely redeclare GEOSERVER_OPTS or run a find/replace on it to set the correct values.

What I propose would be to only add the memory arguments in the entrypoint, leaving them out of the Dockerfile.
```
export GEOSERVER_OPTS="${GEOSERVER_OPTS} -Xms${INITIAL_MEMORY} -Xmx${MAXIMUM_MEMORY}"
```

This way, setting the MEMORY variables at run time would actually change GEOSERVER_OPTS.

**Comment by NyakudyaA** [comment]
@Wieschie thanks for picking this up. what would happen if we entirely move the whole `GEOSERVER_OPTS` declaration to entrypoint because that is where it is being used

**Comment by Wieschie** [comment]
@NyakudyaA I think either way would allow you to set the values when you create a container.

**Comment by NyakudyaA** [comment]
I would give a thumbs up on moving the geoserver_opt declaration to entrypoint script because in case we find something to parameterize we won’t have to change in multiple places

**Comment by Wieschie** [comment]
Should I make a pull request against the develop branch or against master?
